-- Notifications, infrastructure, documents and verification
--
-- Adopted from the `ajo` database, which held this schema with no
-- SQL source in version control. Generated by scripts/adopt_schema.py;
-- do not hand-edit, re-run the generator and commit the result.
--
-- 36 object(s). Tables: notification_templates, notification_preferences, notifications, idempotency_keys, webhook_events, outbox_events, document_types, documents, invitations, verification_check_types, verification_checks.

SET check_function_bodies = false;

--

CREATE TABLE public.document_types (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    requires_expiry boolean DEFAULT false NOT NULL,
    retention_class text DEFAULT 'operational'::text NOT NULL,
    is_special_category boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    sort_order smallint DEFAULT 100 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL
);


--

--

COMMENT ON TABLE public.document_types IS 'Lookup table, not an enum. The acceptable document set is a risk and compliance decision (CANONICAL.md D-04) and changes without a code deploy. is_special_category flags documents that attract heightened obligations under the Nigeria Data Protection Act 2023.';


--

--

CREATE TABLE public.documents (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    owner_user_id uuid NOT NULL,
    verification_check_id uuid,
    doc_type_id uuid NOT NULL,
    storage_bucket text NOT NULL,
    storage_path text NOT NULL,
    sha256 bytea NOT NULL,
    mime_type text NOT NULL,
    byte_size bigint NOT NULL,
    scan_status public.document_scan_status DEFAULT 'pending'::public.document_scan_status NOT NULL,
    issued_at date,
    expires_at timestamp with time zone,
    uploaded_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT documents_byte_size_check CHECK ((byte_size > 0))
);

ALTER TABLE ONLY public.documents FORCE ROW LEVEL SECURITY;


--

--

COMMENT ON COLUMN public.documents.sha256 IS 'Content hash, hex-decoded. Used for the duplicate check above and to prove the stored object is the object that was scanned.';


--

--

CREATE TABLE public.idempotency_keys (
    key text NOT NULL,
    user_id uuid NOT NULL,
    route text NOT NULL,
    method text NOT NULL,
    request_hash bytea NOT NULL,
    state public.idempotency_state DEFAULT 'in_progress'::public.idempotency_state NOT NULL,
    response_status integer,
    response_body jsonb,
    resource_type text,
    resource_id uuid,
    is_retryable boolean DEFAULT false NOT NULL,
    locked_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT idempotency_keys_completed_is_complete CHECK (((state <> 'completed'::public.idempotency_state) OR ((response_status IS NOT NULL) AND (completed_at IS NOT NULL)))),
    CONSTRAINT idempotency_keys_expiry_after_creation CHECK ((expires_at > created_at)),
    CONSTRAINT idempotency_keys_method_check CHECK ((method = ANY (ARRAY['POST'::text, 'PUT'::text, 'PATCH'::text, 'DELETE'::text])))
);


--

--

COMMENT ON TABLE public.idempotency_keys IS 'The retried-request ledger. A replayed POST with the same key and the same body returns the stored response verbatim; the same key with a different body is a 409. See section 9.7 for the algorithm and the TTL.';


--

--

CREATE TABLE public.invitations (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    ajo_id uuid NOT NULL,
    position_id uuid,
    email public.citext NOT NULL,
    token_hash bytea NOT NULL,
    status public.invitation_status DEFAULT 'pending'::public.invitation_status NOT NULL,
    message text,
    invited_by_user_id uuid NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    accepted_by_user_id uuid,
    accepted_at timestamp with time zone,
    declined_at timestamp with time zone,
    resend_count smallint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT invitations_accepted_consistent CHECK (((status <> 'accepted'::public.invitation_status) OR ((accepted_at IS NOT NULL) AND (accepted_by_user_id IS NOT NULL)))),
    CONSTRAINT invitations_resend_count_check CHECK ((resend_count >= 0))
);


--

--

COMMENT ON COLUMN public.invitations.token_hash IS 'SHA-256 of the invitation token. The plaintext is in the email only and is never stored, logged or returned by an API. GET /invitations/:token looks the row up by this hash.';


--

--

CREATE TABLE public.notification_preferences (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    push_enabled boolean DEFAULT true NOT NULL,
    email_enabled boolean DEFAULT true NOT NULL,
    sms_enabled boolean DEFAULT true NOT NULL,
    money_sms_opt_in boolean DEFAULT true NOT NULL,
    quiet_hours_start time without time zone,
    quiet_hours_end time without time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT notification_preferences_money_sms_consistent CHECK (((money_sms_opt_in = false) OR (sms_enabled = true))),
    CONSTRAINT notification_preferences_quiet_hours_paired CHECK (((quiet_hours_start IS NULL) = (quiet_hours_end IS NULL)))
);


--

--

CREATE TABLE public.notification_templates (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    event_key text NOT NULL,
    channel public.notification_channel NOT NULL,
    subject text,
    body text NOT NULL,
    is_money_critical boolean DEFAULT false NOT NULL,
    is_security boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL
);


--

--

CREATE TABLE public.notifications (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    template_id uuid NOT NULL,
    event_key text NOT NULL,
    channel public.notification_channel NOT NULL,
    status public.notification_status DEFAULT 'queued'::public.notification_status NOT NULL,
    subject text,
    body text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    dedupe_key text NOT NULL,
    scheduled_for timestamp with time zone DEFAULT now() NOT NULL,
    sent_at timestamp with time zone,
    delivered_at timestamp with time zone,
    read_at timestamp with time zone,
    failed_at timestamp with time zone,
    failure_detail text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    amount_kobo bigint,
    fee_kobo bigint,
    CONSTRAINT notifications_amount_kobo_check CHECK (((amount_kobo IS NULL) OR (amount_kobo >= 0))),
    CONSTRAINT notifications_fee_kobo_check CHECK (((fee_kobo IS NULL) OR (fee_kobo >= 0)))
);


--

--

COMMENT ON COLUMN public.notifications.dedupe_key IS 'event_key + the ids that make the event unique, e.g. contribution.received:<contribution_id> or payout.succeeded:<payout_id>. The UNIQUE on (dedupe_key, channel) is what makes a replayed webhook send the receipt once rather than four times.';


--

--

CREATE TABLE public.outbox_events (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    aggregate_type text NOT NULL,
    aggregate_id uuid NOT NULL,
    event_type text NOT NULL,
    payload jsonb NOT NULL,
    status public.outbox_status DEFAULT 'pending'::public.outbox_status NOT NULL,
    attempts smallint DEFAULT 0 NOT NULL,
    next_retry_at timestamp with time zone DEFAULT now() NOT NULL,
    published_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT outbox_events_attempts_check CHECK ((attempts >= 0))
);


--

--

COMMENT ON TABLE public.outbox_events IS 'Written in the SAME transaction as the ledger postings. A payment that posts money and then fails to send its receipt is a member who believes they were not charged; the outbox is the difference between one atomic commit and two hopeful ones. See section 9.3.8 and 9.8.';


--

--

CREATE TABLE public.verification_check_types (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    is_mandatory boolean DEFAULT false NOT NULL,
    document_type_id uuid,
    provider text,
    is_active boolean DEFAULT true NOT NULL,
    sort_order smallint DEFAULT 100 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL
);


--

--

COMMENT ON TABLE public.verification_check_types IS 'is_mandatory is false for BVN and CAC because CANONICAL.md D-04 leaves open whether they are required for all members or only above a threshold. Risk and Legal own that decision; the schema supports either answer without a migration.';


--

--

CREATE TABLE public.verification_checks (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    check_type_id uuid NOT NULL,
    status public.verification_status DEFAULT 'pending'::public.verification_status NOT NULL,
    provider text,
    provider_reference text,
    result_payload jsonb,
    failure_reason text,
    reviewed_by_user_id uuid,
    reviewed_at timestamp with time zone,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT verification_checks_review_consistent CHECK (((status = ANY (ARRAY['approved'::public.verification_status, 'rejected'::public.verification_status])) = (reviewed_at IS NOT NULL)))
);


--

--

CREATE TABLE public.webhook_events (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    provider text NOT NULL,
    provider_event_id text NOT NULL,
    event_type text NOT NULL,
    signature_verified boolean DEFAULT false NOT NULL,
    signature_algorithm text,
    raw_payload jsonb NOT NULL,
    status public.webhook_processing_status DEFAULT 'received'::public.webhook_processing_status NOT NULL,
    attempts smallint DEFAULT 0 NOT NULL,
    next_retry_at timestamp with time zone,
    processed_at timestamp with time zone,
    error_detail text,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT webhook_events_attempts_check CHECK ((attempts >= 0))
);


--

--

COMMENT ON COLUMN public.webhook_events.signature_verified IS 'A CHECK-style guarantee in the service layer: a payment is never created from an event whose signature did not verify. CANONICAL.md section 6 marks POST /webhooks/payments as unauthenticated, which makes the signature the only authentication it has.';


--

--

ALTER TABLE ONLY public.document_types
    ADD CONSTRAINT document_types_code_key UNIQUE (code);


--

--

ALTER TABLE ONLY public.document_types
    ADD CONSTRAINT document_types_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_no_duplicate_upload_per_user EXCLUDE USING gist (owner_user_id WITH =, sha256 WITH =);


--

--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_storage_path_key UNIQUE (storage_path);


--

--

ALTER TABLE ONLY public.idempotency_keys
    ADD CONSTRAINT idempotency_keys_pkey PRIMARY KEY (key);


--

--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_token_hash_key UNIQUE (token_hash);


--

--

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_user_id_key UNIQUE (user_id);


--

--

ALTER TABLE ONLY public.notification_templates
    ADD CONSTRAINT notification_templates_event_key_channel_key UNIQUE (event_key, channel);


--

--

ALTER TABLE ONLY public.notification_templates
    ADD CONSTRAINT notification_templates_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.verification_check_types
    ADD CONSTRAINT verification_check_types_code_key UNIQUE (code);


--

--

ALTER TABLE ONLY public.verification_check_types
    ADD CONSTRAINT verification_check_types_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.verification_checks
    ADD CONSTRAINT verification_checks_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.webhook_events
    ADD CONSTRAINT webhook_events_pk PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.webhook_events
    ADD CONSTRAINT webhook_events_provider_event_unique UNIQUE (provider, provider_event_id);


--
