-- Contributions, payments, fees and payouts
--
-- Adopted from the `ajo` database, which held this schema with no
-- SQL source in version control. Generated by scripts/adopt_schema.py;
-- do not hand-edit, re-run the generator and commit the result.
--
-- 14 object(s). Tables: contributions, payments, fees, payouts.

SET check_function_bodies = false;

--

CREATE TABLE public.contributions (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    schedule_id uuid NOT NULL,
    member_id uuid NOT NULL,
    position_id uuid NOT NULL,
    ajo_id uuid NOT NULL,
    round_id uuid NOT NULL,
    user_id uuid NOT NULL,
    amount_kobo bigint NOT NULL,
    fee_kobo bigint GENERATED ALWAYS AS ((((amount_kobo * 200) + 5000) / 10000)) STORED,
    total_charge_kobo bigint GENERATED ALWAYS AS ((amount_kobo + (((amount_kobo * 200) + 5000) / 10000))) STORED,
    status public.contribution_status DEFAULT 'pending'::public.contribution_status NOT NULL,
    due_date date NOT NULL,
    paid_at timestamp with time zone,
    overdue_at timestamp with time zone,
    grace_ends_at timestamp with time zone,
    defaulted_at timestamp with time zone,
    recovered_at timestamp with time zone,
    written_off_at timestamp with time zone,
    written_off_reason text,
    superseded_at timestamp with time zone,
    superseded_by_contribution_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT contributions_amount_kobo_check CHECK ((amount_kobo > 0)),
    CONSTRAINT contributions_charge_is_base_plus_fee CHECK ((total_charge_kobo = (amount_kobo + fee_kobo))),
    CONSTRAINT contributions_defaulted_has_timestamp CHECK (((status <> 'defaulted'::public.contribution_status) OR (defaulted_at IS NOT NULL))),
    CONSTRAINT contributions_fee_kobo_check CHECK ((fee_kobo >= 0)),
    CONSTRAINT contributions_paid_has_timestamp CHECK (((status <> 'paid'::public.contribution_status) OR (paid_at IS NOT NULL))),
    CONSTRAINT contributions_superseded_is_complete CHECK (((superseded_at IS NULL) = (superseded_by_contribution_id IS NULL))),
    CONSTRAINT contributions_written_off_has_reason CHECK (((status <> 'written_off'::public.contribution_status) OR ((written_off_at IS NOT NULL) AND (written_off_reason IS NOT NULL))))
);


--

--

COMMENT ON COLUMN public.contributions.amount_kobo IS 'What goes into the round pool. A recipient of a ten-member round receives the sum of these and never the sum of total_charge_kobo. That asymmetry is the entire fee model.';


--

--

COMMENT ON COLUMN public.contributions.total_charge_kobo IS 'NGN 1,020.00 for a member owing NGN 1,000.00. This is the only figure the member is debited, and it is derived, never supplied.';


--

--

CREATE TABLE public.fees (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    payment_id uuid NOT NULL,
    contribution_id uuid NOT NULL,
    contribution_amount_kobo bigint NOT NULL,
    fee_kobo bigint GENERATED ALWAYS AS ((((contribution_amount_kobo * 200) + 5000) / 10000)) STORED,
    fee_rate_bps smallint DEFAULT 200 NOT NULL,
    status public.fee_status DEFAULT 'accrued'::public.fee_status NOT NULL,
    ledger_transaction_id uuid,
    disclosed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT fees_contribution_amount_kobo_check CHECK ((contribution_amount_kobo > 0)),
    CONSTRAINT fees_fee_kobo_check CHECK ((fee_kobo >= 0)),
    CONSTRAINT fees_fee_rate_bps_check CHECK ((fee_rate_bps = 200))
);


--

--

COMMENT ON TABLE public.fees IS 'AJO.ng''s own record of the 2% charge, separate from the member''s payment so that revenue reporting never depends on joining the payment table.';


--

--

CREATE TABLE public.payments (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    contribution_id uuid NOT NULL,
    channel_id uuid NOT NULL,
    idempotency_key text NOT NULL,
    provider text NOT NULL,
    provider_reference text,
    webhook_event_id uuid,
    contribution_amount_kobo bigint NOT NULL,
    fee_kobo bigint GENERATED ALWAYS AS ((((contribution_amount_kobo * 200) + 5000) / 10000)) STORED,
    charged_amount_kobo bigint GENERATED ALWAYS AS ((contribution_amount_kobo + (((contribution_amount_kobo * 200) + 5000) / 10000))) STORED,
    fee_rate_bps smallint DEFAULT 200 NOT NULL,
    status public.payment_status DEFAULT 'initiated'::public.payment_status NOT NULL,
    provider_created_at timestamp with time zone,
    provider_completed_at timestamp with time zone,
    settled_at timestamp with time zone,
    failure_code text,
    failure_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT payments_charge_is_base_plus_fee CHECK ((charged_amount_kobo = (contribution_amount_kobo + fee_kobo))),
    CONSTRAINT payments_contribution_amount_kobo_check CHECK ((contribution_amount_kobo > 0)),
    CONSTRAINT payments_fee_is_two_percent CHECK ((fee_kobo = (((contribution_amount_kobo * 200) + 5000) / 10000))),
    CONSTRAINT payments_fee_kobo_check CHECK ((fee_kobo >= 0)),
    CONSTRAINT payments_fee_rate_bps_check CHECK ((fee_rate_bps = 200))
);

ALTER TABLE ONLY public.payments FORCE ROW LEVEL SECURITY;


--

--

CREATE TABLE public.payouts (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    round_id uuid NOT NULL,
    position_id uuid NOT NULL,
    member_id uuid NOT NULL,
    user_id uuid NOT NULL,
    ajo_id uuid NOT NULL,
    base_pool_kobo bigint NOT NULL,
    amount_kobo bigint NOT NULL,
    fee_kobo bigint DEFAULT 0 NOT NULL,
    provider_fee_kobo bigint DEFAULT 0 NOT NULL,
    status public.payout_status DEFAULT 'scheduled'::public.payout_status NOT NULL,
    provider text,
    provider_reference text,
    released_at timestamp with time zone,
    settled_at timestamp with time zone,
    failed_at timestamp with time zone,
    attempt_count smallint DEFAULT 0 NOT NULL,
    held_at timestamp with time zone,
    held_reason text,
    recognized_transaction_id uuid,
    settled_transaction_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT payouts_amount_is_base_pool CHECK ((amount_kobo = base_pool_kobo)),
    CONSTRAINT payouts_attempt_count_check CHECK ((attempt_count >= 0)),
    CONSTRAINT payouts_base_pool_kobo_check CHECK ((base_pool_kobo > 0)),
    CONSTRAINT payouts_fee_kobo_check CHECK ((fee_kobo = 0)),
    CONSTRAINT payouts_held_has_reason CHECK (((status <> 'held'::public.payout_status) OR ((held_at IS NOT NULL) AND (held_reason IS NOT NULL)))),
    CONSTRAINT payouts_provider_fee_kobo_check CHECK ((provider_fee_kobo >= 0)),
    CONSTRAINT payouts_released_has_timestamp CHECK (((status <> ALL (ARRAY['released'::public.payout_status, 'success'::public.payout_status])) OR (released_at IS NOT NULL))),
    CONSTRAINT payouts_success_requires_recognition CHECK (((status <> 'success'::public.payout_status) OR ((recognized_transaction_id IS NOT NULL) AND (settled_transaction_id IS NOT NULL))))
);

ALTER TABLE ONLY public.payouts FORCE ROW LEVEL SECURITY;


--

--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_one_per_member_per_schedule UNIQUE (schedule_id, member_id);


--

--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.fees
    ADD CONSTRAINT fees_payment_id_key UNIQUE (payment_id);


--

--

ALTER TABLE ONLY public.fees
    ADD CONSTRAINT fees_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_one_per_round_position UNIQUE (round_id, position_id);


--

--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_pkey PRIMARY KEY (id);


--
