-- Identity and access
--
-- Adopted from the `ajo` database, which held this schema with no
-- SQL source in version control. Generated by scripts/adopt_schema.py;
-- do not hand-edit, re-run the generator and commit the result.
--
-- 30 object(s). Tables: users, profiles, admins, sessions, device_tokens, roles, role_assignments.

SET check_function_bodies = false;

--

CREATE TABLE public.admins (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    operator_status public.user_status DEFAULT 'active'::public.user_status NOT NULL,
    last_active_at timestamp with time zone,
    invited_by_user_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL
);


--

--

COMMENT ON TABLE public.admins IS 'The platform-operator flag. Holds operator state, not permissions: those live in role_assignments. Absence of a row means not an operator.';


--

--

CREATE TABLE public.device_tokens (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    session_id uuid,
    platform text NOT NULL,
    push_token text NOT NULL,
    app_version text,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT device_tokens_platform_check CHECK ((platform = ANY (ARRAY['ios'::text, 'android'::text, 'web'::text])))
);


--

--

COMMENT ON TABLE public.device_tokens IS 'Push delivery targets. A token is superseded and revoked, never deleted, so a notification already in flight still reports its true outcome.';


--

--

CREATE TABLE public.profiles (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    display_name text NOT NULL,
    avatar_document_id uuid,
    preferred_locale text DEFAULT 'en-NG'::text NOT NULL,
    preferred_channel_id uuid,
    bvn_last4 character(4),
    bvn_hash bytea,
    bio text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT profiles_bvn_last4_check CHECK ((bvn_last4 ~ '^[0-9]{4}$'::text)),
    CONSTRAINT profiles_display_name_check CHECK (((length(btrim(display_name)) >= 2) AND (length(btrim(display_name)) <= 80)))
);

ALTER TABLE ONLY public.profiles FORCE ROW LEVEL SECURITY;


--

--

COMMENT ON TABLE public.profiles IS 'Presentation data, separated from users so a bio edit never takes a row lock on the account row that authentication and role checks also read.';


--

--

COMMENT ON COLUMN public.profiles.bvn_hash IS 'HMAC of the BVN under a key held in the secrets manager, never in the database. See the LEGAL callout in section 8.3.1.';


--

--

CREATE TABLE public.role_assignments (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    role_id text NOT NULL,
    user_id uuid NOT NULL,
    scope public.role_scope NOT NULL,
    ajo_id uuid,
    ajo_member_id uuid,
    granted_by_user_id uuid,
    granted_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT role_assignments_scope_target_matches CHECK (((scope = 'platform'::public.role_scope) = ((ajo_id IS NULL) AND (ajo_member_id IS NULL)))),
    CONSTRAINT role_assignments_single_target CHECK ((num_nonnulls(ajo_id, ajo_member_id) <= 1))
);


--

--

COMMENT ON TABLE public.role_assignments IS 'Scoped grants. Resolves users-to-roles (platform) and users-to-roles-within-one-Ajo. A grant is revoked, never deleted.';


--

--

CREATE TABLE public.roles (
    code text NOT NULL,
    scope public.role_scope NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--

--

CREATE TABLE public.sessions (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    refresh_token_hash bytea NOT NULL,
    device_label text,
    platform text,
    ip_address inet,
    user_agent text,
    last_active_at timestamp with time zone DEFAULT now() NOT NULL,
    revoked_at timestamp with time zone,
    revoked_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT sessions_platform_check CHECK (((platform IS NULL) OR (platform = ANY (ARRAY['web'::text, 'ios'::text, 'android'::text]))))
);


--

--

COMMENT ON TABLE public.sessions IS 'Serves GET /auth/sessions and DELETE /auth/sessions/:id, and is the source of the security.login_new_device notification in CANONICAL.md section 8. DELETE /auth/sessions/:id sets revoked_at; it never removes the row, because a revoked session that was used afterwards is the evidence.';


--

--

CREATE TABLE public.users (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    auth_subject_id public.citext,
    email public.citext NOT NULL,
    phone_e164 public.citext,
    status public.user_status DEFAULT 'pending_verification'::public.user_status NOT NULL,
    is_email_verified boolean DEFAULT false NOT NULL,
    is_phone_verified boolean DEFAULT false NOT NULL,
    last_login_at timestamp with time zone,
    last_seen_at timestamp with time zone,
    frozen_at timestamp with time zone,
    frozen_reason text,
    closed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT users_closed_has_closed_at CHECK (((status <> 'closed'::public.user_status) OR (closed_at IS NOT NULL))),
    CONSTRAINT users_frozen_reason_required CHECK (((status = 'frozen'::public.user_status) OR (frozen_at IS NULL)))
);

ALTER TABLE ONLY public.users FORCE ROW LEVEL SECURITY;


--

--

COMMENT ON TABLE public.users IS 'The account. Supabase Auth owns the credential; this row owns everything the product needs to know about the person.';


--

--

COMMENT ON COLUMN public.users.auth_subject_id IS 'References auth.users(id) in the Supabase deployment. Validated by the service layer, not by a foreign key -- see section 8.4.';


--

--

COMMENT ON COLUMN public.users.status IS 'A frozen user can still read their own history and raise a dispute. Frozen means "cannot move money", never "cannot see anything".';


--

--

COMMENT ON COLUMN public.users.deleted_at IS 'Account closure is an anonymisation, not a delete. Personal columns are nulled and the row is kept, because contributions and ledger postings reference it permanently. See section 8.9.';


--

--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_user_id_key UNIQUE (user_id);


--

--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_push_token_key UNIQUE (push_token);


--

--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);


--

--

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT role_assignments_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (code);


--

--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_auth_subject_id_key UNIQUE (auth_subject_id);


--

--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--

--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_phone_e164_key UNIQUE (phone_e164);


--

--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
