-- Extensions, the app schema, enums, and the three roles
--
-- Adopted from the `ajo` database, which held this schema with no
-- SQL source in version control. Generated by scripts/adopt_schema.py;
-- do not hand-edit, re-run the generator and commit the result.
--
-- 71 object(s).

SET check_function_bodies = false;

--

CREATE SCHEMA IF NOT EXISTS app;


--

--

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;


--

--

COMMENT ON EXTENSION btree_gist IS 'support for indexing common datatypes in GiST';


--

--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--

--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


--

--

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;


--

--

COMMENT ON EXTENSION pg_stat_statements IS 'track planning and execution statistics of all SQL statements executed';


--

--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--

--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--

--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--

--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--

--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--

--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--

--

CREATE TYPE public.ajo_status AS ENUM (
    'draft',
    'enrollment',
    'active',
    'round_in_progress',
    'completed',
    'cancelled',
    'cancelling',
    'frozen'
);


--

--

CREATE TYPE public.contribution_status AS ENUM (
    'pending',
    'paid',
    'overdue',
    'grace',
    'defaulted',
    'recovered',
    'written_off'
);


--

--

CREATE TYPE public.dispute_status AS ENUM (
    'open',
    'under_review',
    'awaiting_member',
    'awaiting_organizer',
    'resolved',
    'withdrawn',
    'escalated'
);


--

--

CREATE TYPE public.document_scan_status AS ENUM (
    'pending',
    'clean',
    'quarantined'
);


--

--

CREATE TYPE public.fee_status AS ENUM (
    'accrued',
    'invoiced',
    'refunded',
    'written_off'
);


--

--

CREATE TYPE public.idempotency_state AS ENUM (
    'in_progress',
    'completed',
    'failed'
);


--

--

CREATE TYPE public.invitation_status AS ENUM (
    'pending',
    'accepted',
    'declined',
    'expired',
    'revoked'
);


--

--

CREATE TYPE public.ledger_account_kind AS ENUM (
    'escrow_cash',
    'contributions_receivable',
    'defaults_receivable',
    'payouts_payable',
    'refunds_payable',
    'fees_income',
    'provider_clearing'
);


--

--

CREATE TYPE public.ledger_entry_type AS ENUM (
    'contribution.received',
    'fee.recognised',
    'payout.recognized',
    'payout.settled',
    'contribution.defaulted',
    'reversal'
);


--

--

CREATE TYPE public.ledger_side AS ENUM (
    'debit',
    'credit'
);


--

--

CREATE TYPE public.member_status AS ENUM (
    'invited',
    'active',
    'defaulted',
    'replaced',
    'exited',
    'removed'
);


--

--

CREATE TYPE public.notification_channel AS ENUM (
    'push',
    'email',
    'sms'
);


--

--

CREATE TYPE public.notification_status AS ENUM (
    'queued',
    'sent',
    'delivered',
    'failed',
    'read',
    'suppressed'
);


--

--

CREATE TYPE public.outbox_status AS ENUM (
    'pending',
    'published',
    'failed'
);


--

--

CREATE TYPE public.payment_status AS ENUM (
    'initiated',
    'pending',
    'success',
    'failed',
    'cancelled',
    'reversed',
    'unknown'
);


--

--

CREATE TYPE public.payout_status AS ENUM (
    'scheduled',
    'funding',
    'released',
    'success',
    'failed',
    'held'
);


--

--

CREATE TYPE public.position_status AS ENUM (
    'open',
    'claimed',
    'locked',
    'released',
    'replaced',
    'forfeited'
);


--

--

CREATE TYPE public.reconciliation_status AS ENUM (
    'running',
    'passed',
    'failed',
    'investigating'
);


--

--

CREATE TYPE public.risk_decision AS ENUM (
    'allow',
    'review',
    'block',
    'freeze'
);


--

--

CREATE TYPE public.risk_event_status AS ENUM (
    'open',
    'under_review',
    'decided',
    'dismissed',
    'escalated'
);


--

--

CREATE TYPE public.risk_severity AS ENUM (
    'low',
    'medium',
    'high',
    'critical'
);


--

--

CREATE TYPE public.risk_subject_type AS ENUM (
    'user',
    'ajo',
    'payment',
    'payout',
    'contribution'
);


--

--

CREATE TYPE public.role_scope AS ENUM (
    'platform',
    'ajo'
);


--

--

CREATE TYPE public.round_status AS ENUM (
    'scheduled',
    'in_progress',
    'funding',
    'held',
    'completed',
    'cancelled'
);


--

--

CREATE TYPE public.schedule_status AS ENUM (
    'draft',
    'open',
    'closed',
    'cancelled'
);


--

--

CREATE TYPE public.subject_type AS ENUM (
    'user',
    'profile',
    'admin',
    'role_assignment',
    'session',
    'device_token',
    'verification_check',
    'document',
    'ajo',
    'ajo_position',
    'ajo_member',
    'invitation',
    'round',
    'contribution_schedule',
    'contribution',
    'payment',
    'fee',
    'payout',
    'webhook_event',
    'idempotency_key',
    'ledger_transaction',
    'ledger_posting',
    'dispute',
    'dispute_message',
    'dispute_evidence',
    'risk_event',
    'reconciliation_run',
    'notification',
    'notification_template',
    'notification_preference',
    'support_ticket',
    'outbox_event',
    'platform_setting'
);


--

--

CREATE TYPE public.support_ticket_priority AS ENUM (
    'low',
    'normal',
    'high',
    'urgent'
);


--

--

CREATE TYPE public.support_ticket_status AS ENUM (
    'open',
    'pending',
    'resolved',
    'closed'
);


--

--

CREATE TYPE public.user_status AS ENUM (
    'pending_verification',
    'active',
    'frozen',
    'closed'
);


--

--

CREATE TYPE public.verification_status AS ENUM (
    'pending',
    'in_review',
    'approved',
    'rejected',
    'expired'
);


--

--

CREATE TYPE public.webhook_processing_status AS ENUM (
    'received',
    'processing',
    'processed',
    'failed',
    'ignored',
    'duplicate'
);


--

--

CREATE FUNCTION app.assert_draft_exit() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_positions integer;
  v_filled    integer;
  v_window    interval;
BEGIN
  IF NEW.status IN ('enrollment', 'active', 'round_in_progress', 'completed')
     AND OLD.status = 'draft' THEN
    SELECT count(*) INTO v_positions
      FROM ajo_positions
     WHERE ajo_id = NEW.id AND deleted_at IS NULL;

    IF v_positions < 2 THEN
      RAISE EXCEPTION
        'ajo % cannot leave DRAFT with % position(s); at least two are required',
        NEW.id, v_positions
        USING ERRCODE = 'check_violation',
              HINT = 'An Ajo of one is a transfer, not a rotation.';
    END IF;
  END IF;

  -- ENROLLMENT -> ACTIVE either fills every position or reaches day five.
  IF NEW.status = 'active' AND OLD.status = 'enrollment' THEN
    SELECT count(*), count(*) FILTER (WHERE p.status <> 'open')
      INTO v_positions, v_filled
      FROM ajo_positions p
     WHERE p.ajo_id = NEW.id AND p.deleted_at IS NULL;

    v_window := NEW.enrollment_closes_at - NEW.enrollment_opens_at;

    IF v_filled < v_positions AND now() < NEW.enrollment_closes_at THEN
      RAISE EXCEPTION
        'ajo % cannot activate: % of % positions filled and the window closes at %',
        NEW.id, v_filled, v_positions, NEW.enrollment_closes_at
        USING ERRCODE = 'check_violation',
              HINT = 'CANONICAL.md section 3: ENROLLMENT -> ACTIVE requires '
                     'every position filled, or day five reached.';
    END IF;

    IF v_window <> interval '5 days' THEN
      RAISE EXCEPTION
        'ajo % has an enrollment window of %, which is not exactly 5 days',
        NEW.id, v_window
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  -- BEFORE triggers return the row to keep. Returning NULL here would make
  -- PostgreSQL drop the row silently: no error, no warning, INSERT 0 0.
  RETURN NEW;
END;
$$;


--

--

CREATE FUNCTION app.assert_fee_matches_payment() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  p_base  bigint;
  p_fee   bigint;
  p_chan  uuid;
BEGIN
  SELECT contribution_amount_kobo, fee_kobo, channel_id
    INTO p_base, p_fee, p_chan
    FROM payments
   WHERE id = NEW.payment_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'fee % references payment %, which does not exist',
      NEW.id, NEW.payment_id USING ERRCODE = 'foreign_key_violation';
  END IF;

  IF NEW.contribution_amount_kobo <> p_base THEN
    RAISE EXCEPTION
      'fee % records base %, but payment % has base %',
      NEW.id, NEW.contribution_amount_kobo, NEW.payment_id, p_base
      USING ERRCODE = 'check_violation';
  END IF;

  IF NEW.fee_kobo <> p_fee THEN
    RAISE EXCEPTION
      'fee % records %, but payment % charged a fee of %',
      NEW.id, NEW.fee_kobo, NEW.payment_id, p_fee
      USING ERRCODE = 'check_violation',
            HINT = 'The fee is derived, never supplied. Read it from the '
                   'payment instead of computing it a second time.';
  END IF;

  IF NEW.fee_kobo <> ((p_base * 200 + 5000) / 10000) THEN
    RAISE EXCEPTION
      'fee % of % is not 2%% half-up of base %', NEW.id, NEW.fee_kobo, p_base
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$;


--

--

CREATE FUNCTION app.assert_ledger_balanced_for_txn() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_count integer;
  v_sum   bigint;
BEGIN
  -- Runs from the ledger_transactions side, and catches the case a posting
  -- trigger structurally cannot: a transaction row with NO postings at all.
  SELECT count(*), COALESCE(sum(signed_kobo), 0)
    INTO v_count, v_sum
    FROM ledger_postings
   WHERE transaction_id = NEW.id;

  IF v_count < 2 OR v_sum <> 0 THEN
    RAISE EXCEPTION
      'ledger transaction % (% / %) is not a valid entry: % posting(s), sum %',
      NEW.id, NEW.kind, NEW.occurred_at, v_count, v_sum
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NULL;
END;
$$;


--

--

CREATE FUNCTION app.assert_ledger_sequence() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_recognized_at timestamptz;
  v_target_kind   ledger_entry_type;
  v_count         integer;
  v_sum           bigint;
BEGIN
  IF NEW.kind = 'reversal' THEN
    -- CR-21, second half: reversals are one level deep. A reversal of a
    -- reversal is not a correction, it is an untraceable second correction.
    SELECT kind INTO v_target_kind
      FROM ledger_transactions
     WHERE id = NEW.reverses_transaction_id;

    IF v_target_kind = 'reversal' THEN
      RAISE EXCEPTION
        'transaction % reverses %, which is itself a reversal; '
        'reversals are one level deep (CR-21)',
        NEW.id, NEW.reverses_transaction_id
        USING ERRCODE = 'check_violation',
              HINT = 'If entry A was wrong and entry B corrected it, the fix '
                     'for B is a new entry C that explains itself, not a '
                     'reversal of B.';
    END IF;
    RETURN NULL;
  END IF;

  IF NEW.kind <> 'payout.settled' THEN
    RETURN NULL;
  END IF;

  SELECT min(t.occurred_at)
    INTO v_recognized_at
    FROM ledger_transactions t
   WHERE t.kind       = 'payout.recognized'
     AND t.payout_id  = NEW.payout_id
     AND t.id        <> NEW.id;

  IF v_recognized_at IS NULL THEN
    RAISE EXCEPTION
      'payout.settled % references payout % with no payout.recognized entry',
      NEW.id, NEW.payout_id
      USING ERRCODE = 'check_violation',
            HINT = 'CANONICAL.md section 4 fixes the order: contribution.'
                   'received, fee.recognised, payout.recognized, payout.settled.';
  END IF;

  IF v_recognized_at > NEW.occurred_at THEN
    RAISE EXCEPTION
      'payout.settled at % precedes payout.recognized at % for payout %',
      NEW.occurred_at, v_recognized_at, NEW.payout_id
      USING ERRCODE = 'check_violation';
  END IF;

  -- "Complete" means the recognition entry is itself a valid journal entry. A
  -- half-posted recognition satisfies the ordering check and is still wrong.
  SELECT count(*), COALESCE(sum(signed_kobo), 0)
    INTO v_count, v_sum
    FROM ledger_postings
   WHERE transaction_id = (
     SELECT id FROM ledger_transactions
      WHERE kind = 'payout.recognized' AND payout_id = NEW.payout_id
      ORDER BY occurred_at LIMIT 1);

  IF v_count < 2 OR v_sum <> 0 THEN
    RAISE EXCEPTION
      'the payout.recognized entry for payout % is incomplete (% posting(s), '
      'sum %); payout.settled requires a complete recognition',
      NEW.payout_id, v_count, v_sum
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$;


--

--

COMMENT ON FUNCTION app.assert_ledger_sequence() IS 'CR-17 and CR-21. Ordering is asserted on payout.settled, the only step in the canonical sequence with a prerequisite that the other three do not.';


--

--

CREATE FUNCTION app.assert_lifecycle_transition() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  -- CANONICAL.md section 3, the transition table, as "from>to" strings. A
  -- string rather than a two-dimensional array because unnest() over text[][]
  -- flattens in a way that has to be explained, and an adjacency list nobody
  -- can read at a glance is a table that will be edited wrongly.
  allowed text[] := ARRAY[
    'draft>enrollment',
    'enrollment>active',
    'enrollment>cancelled',
    'enrollment>frozen',
    'draft>cancelled',
    'draft>frozen',
    'active>round_in_progress',
    'active>completed',
    'active>frozen',
    'active>cancelling',
    'round_in_progress>active',
    'round_in_progress>completed',
    'round_in_progress>frozen',
    'round_in_progress>cancelling',
    'frozen>active',
    'frozen>cancelling',
    'cancelling>cancelled',
    'cancelling>active'
  ];
BEGIN
  IF NEW.status = OLD.status THEN
    RETURN NEW;   -- not a transition
  END IF;

  -- CR-19 first: terminal is terminal, in both directions. Checked before the
  -- adjacency list so the error a caller sees for a completed Ajo is the one
  -- that explains why, rather than "no such transition".
  IF OLD.status IN ('completed', 'cancelled') THEN
    RAISE EXCEPTION
      'ajo % is %, which is terminal; no further events accepted',
      OLD.id, OLD.status
      USING ERRCODE = 'check_violation',
            HINT = 'CANONICAL.md section 3: COMPLETED and CANCELLED accept no '
                   'events in either direction. Reversing one is a new Ajo.';
  END IF;

  IF NOT ((OLD.status || '>' || NEW.status) = ANY (allowed)) THEN
    RAISE EXCEPTION 'illegal Ajo transition: % -> %', OLD.status, NEW.status
      USING ERRCODE = 'check_violation',
            HINT = 'CANONICAL.md section 3 draws this state machine. The '
                   'allowed transitions from ' || OLD.status || ' are the ones '
                   'listed in app.assert_lifecycle_transition().';
  END IF;

  RETURN NEW;
END;
$$;


--

--

CREATE FUNCTION app.assert_money_critical_has_sms() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_channel notification_channel;
BEGIN
  IF NOT (NEW.is_money_critical OR NEW.is_security) THEN
    RETURN NULL;
  END IF;

  -- One of the NEW row's own channels must be SMS.
  IF NEW.channel = 'sms' THEN
    RETURN NULL;
  END IF;

  SELECT channel INTO v_channel
    FROM notification_templates
   WHERE event_key = NEW.event_key
     AND channel = 'sms'
     AND is_active;

  IF v_channel IS NULL THEN
    RAISE EXCEPTION
      'event % is flagged % but has no active SMS template',
      NEW.event_key,
      CASE WHEN NEW.is_money_critical AND NEW.is_security THEN 'money- and security-critical'
           WHEN NEW.is_money_critical                    THEN 'money-critical'
           ELSE 'security-critical' END
      USING ERRCODE = 'check_violation',
            HINT = 'CANONICAL.md section 8: SMS is reserved for money-critical '
                   'and security-critical events. Add the sms row in the same '
                   'transaction as the first push or email row for this event.';
  END IF;

  RETURN NULL;
END;
$$;


--

--

CREATE FUNCTION app.assert_positions_locked() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_status ajo_status;
BEGIN
  IF (NEW.position_number IS DISTINCT FROM OLD.position_number)
     OR (NEW.ajo_id IS DISTINCT FROM OLD.ajo_id) THEN
    SELECT status INTO v_status FROM ajos WHERE id = NEW.ajo_id;

    IF v_status IN ('active', 'round_in_progress', 'completed', 'cancelling') THEN
      RAISE EXCEPTION
        'position % in Ajo % (%): the turn order is locked at activation',
        OLD.id, NEW.ajo_id, v_status
        USING ERRCODE = 'check_violation',
              HINT = 'Reordering after activation requires a replacement or '
                     'transfer request with member consent. See section 8.8 '
                     'CR-02 and the CANONICAL.md section 3 note on positions.';
    END IF;
  END IF;

  -- Releasing or forfeiting a position must say why, or the round pool cannot
  -- explain the gap in its contribution list.
  IF NEW.status IN ('released', 'forfeited', 'replaced')
     AND OLD.status IS DISTINCT FROM NEW.status
     AND NEW.release_reason IS NULL THEN
    RAISE EXCEPTION
      'position % moved to % without a release_reason', OLD.id, NEW.status
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;


--

--

CREATE FUNCTION app.assert_risk_subject_exists() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_exists boolean;
BEGIN
  v_exists := CASE NEW.subject_type
    WHEN 'user'         THEN EXISTS (SELECT 1 FROM users         WHERE id = NEW.subject_id)
    WHEN 'ajo'          THEN EXISTS (SELECT 1 FROM ajos          WHERE id = NEW.subject_id)
    WHEN 'payment'      THEN EXISTS (SELECT 1 FROM payments      WHERE id = NEW.subject_id)
    WHEN 'payout'       THEN EXISTS (SELECT 1 FROM payouts       WHERE id = NEW.subject_id)
    WHEN 'contribution' THEN EXISTS (SELECT 1 FROM contributions WHERE id = NEW.subject_id)
  END;

  IF NOT COALESCE(v_exists, false) THEN
    RAISE EXCEPTION 'risk event % targets % %, which does not exist',
      NEW.id, NEW.subject_type, NEW.subject_id
      USING ERRCODE = 'check_violation',
            HINT = 'Checked at insert only. After this row exists the subject '
                   'may be deleted and the event stays, which is the intent.';
  END IF;

  -- BEFORE triggers return the row to keep. Returning NULL here would make
  -- PostgreSQL drop the row silently: no error, no warning, INSERT 0 0.
  RETURN NEW;
END;
$$;


--

--

CREATE FUNCTION app.assert_round_pool() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_round   uuid;
  v_stored  bigint;
  v_actual  bigint;
  v_members integer;
  v_paid    integer;
BEGIN
  -- The same function guards both sides of the invariant: a round must match
  -- its contributions, and a contribution must not change without the round
  -- being restated. The round is named `id` on rounds and `round_id` on
  -- contributions, so which one to read is a property of the table, not
  -- something to guess at.
  IF TG_TABLE_NAME = 'rounds' THEN
    v_round := NEW.id;
  ELSE
    v_round := COALESCE(NEW.round_id, OLD.round_id);
  END IF;

  SELECT base_pool_kobo INTO v_stored FROM rounds WHERE id = v_round;

  SELECT count(*),
         COALESCE(sum(c.amount_kobo) FILTER (WHERE c.status = 'paid'), 0),
         count(*) FILTER (WHERE c.status = 'paid')
    INTO v_members, v_actual, v_paid
    FROM contributions c
   WHERE c.round_id      = v_round
     AND c.superseded_at IS NULL
     AND c.deleted_at    IS NULL;

  IF v_stored IS DISTINCT FROM v_actual THEN
    RAISE EXCEPTION
      'round % records a base pool of % but its paid, unsuperseded '
      'contributions total % (% of % paid)',
      v_round, v_stored, v_actual, v_paid, v_members
      USING ERRCODE = 'check_violation',
            HINT = 'base_pool_kobo is a stored aggregate, not a field anybody '
                   'types. Restate it as coalesce(sum(amount_kobo), 0) over '
                   'paid, unsuperseded contributions in the SAME statement that '
                   'changed the contributions. The trigger is deferred to '
                   'COMMIT, so the restatement may come later in the same '
                   'transaction -- but not in the next one.';
  END IF;

  RETURN NULL;
END;
$$;


--

--

CREATE FUNCTION app.assert_terminal_timestamps() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF NEW.status = 'completed' AND NEW.completed_at IS NULL THEN
    RAISE EXCEPTION 'ajo % is COMPLETED but has no completed_at',
      NEW.id USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.status <> 'completed' AND NEW.completed_at IS NOT NULL THEN
    RAISE EXCEPTION 'ajo % has completed_at but status is %', NEW.id, NEW.status
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.status = 'cancelled' AND NEW.cancelled_at IS NULL THEN
    RAISE EXCEPTION 'ajo % is CANCELLED but has no cancelled_at',
      NEW.id USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.status <> 'cancelled' AND NEW.cancelled_at IS NOT NULL THEN
    RAISE EXCEPTION 'ajo % has cancelled_at but status is %', NEW.id, NEW.status
      USING ERRCODE = 'check_violation';
  END IF;
  -- BEFORE triggers return the row to keep. Returning NULL here would make
  -- PostgreSQL drop the row silently: no error, no warning, INSERT 0 0.
  RETURN NEW;
END;
$$;


--

--

CREATE FUNCTION app.assert_transaction_balanced() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_txn     uuid;
  v_count   integer;
  v_sum     bigint;
BEGIN
  v_txn := COALESCE(NEW.transaction_id, OLD.transaction_id);

  SELECT count(*), COALESCE(sum(signed_kobo), 0)
    INTO v_count, v_sum
    FROM ledger_postings
   WHERE transaction_id = v_txn;

  IF v_count < 2 THEN
    RAISE EXCEPTION
      'ledger transaction % has % posting(s); a transaction needs at least two',
      v_txn, v_count
      USING ERRCODE = 'check_violation',
            HINT = 'Every entry moves money between two accounts. If you meant '
                   'to delete an entry, post a reversal instead.';
  END IF;

  IF v_sum <> 0 THEN
    RAISE EXCEPTION
      'ledger transaction % does not balance: sum(signed_kobo) = % kobo',
      v_txn, v_sum
      USING ERRCODE = 'check_violation',
            HINT = 'A balanced entry debits and credits the same total.';
  END IF;

  RETURN NULL;
END;
$$;


--

--

COMMENT ON FUNCTION app.assert_transaction_balanced() IS 'CR-16. Deferred to COMMIT so a multi-statement entry is judged as a whole.';


--

--

CREATE FUNCTION app.audit_row() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'app', 'public'
    AS $$
DECLARE
  v_subject_id uuid;
  v_before     jsonb;
  v_after      jsonb;
  v_amount     bigint;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_subject_id := OLD.id;
    v_before     := to_jsonb(OLD);
    v_after      := NULL;
  ELSIF TG_OP = 'INSERT' THEN
    v_subject_id := NEW.id;
    v_before     := NULL;
    v_after      := to_jsonb(NEW);
  ELSE
    v_subject_id := NEW.id;
    v_before     := to_jsonb(OLD);
    v_after      := to_jsonb(NEW);
    -- An UPDATE that changed nothing is not an audit event. Recording it puts
    -- rows in a table that investigators read, and the cost of a noisy audit
    -- trail is that nobody reads it.
    IF v_before = v_after THEN
      RETURN NULL;
    END IF;
  END IF;

  -- Money columns touched, for the finance audit view. NULL means the row is
  -- not a money row, which is most of them. The values themselves stay in the
  -- ledger; this is a pointer, not a copy of the money.
  IF v_after IS NOT NULL AND v_after ? 'amount_kobo' THEN
    v_amount := (v_after ->> 'amount_kobo')::bigint;
  END IF;

  -- subject_type is the table name minus its plural, which is the convention
  -- every table here already follows. An audited table whose singular is not
  -- in the subject_type enum is a gap in the taxonomy, and this cast is where
  -- it surfaces -- loudly, at migration time, rather than as an unqueryable
  -- NULL six months later.
  INSERT INTO audit_logs
    (actor_user_id, actor_type, action, subject_type, subject_id,
     before_state, after_state, request_id, ip_address, amount_kobo)
  VALUES
    (NULLIF(current_setting('app.actor_user_id', true), '')::uuid,
     COALESCE(NULLIF(current_setting('app.actor_type', true), ''), 'service'),
     lower(TG_OP),
     (rtrim(TG_TABLE_NAME, 's'))::subject_type,
     v_subject_id, v_before, v_after,
     NULLIF(current_setting('app.request_id', true), ''),
     NULLIF(current_setting('app.ip_address', true), '')::inet,
     v_amount);

  RETURN NULL;
END;
$$;


--

--

COMMENT ON FUNCTION app.audit_row() IS 'SECURITY DEFINER because the auditing role must be able to write audit_logs even where it has been denied INSERT on it. The trigger fires as the table owner, which is the point: the audit trail is not writable by the role it audits, and not deletable by it either.';


--

--

CREATE FUNCTION app.current_ajo_ids() RETURNS SETOF uuid
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public', 'app'
    AS $$
  SELECT m.ajo_id
    FROM ajo_members m
   WHERE m.user_id  = app.request_user_id()
     AND m.deleted_at IS NULL
     AND m.status   IN ('invited','active','defaulted');
$$;


--

--

CREATE FUNCTION app.has_platform_role(p_role text) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public', 'app'
    AS $$
  SELECT EXISTS (
           SELECT 1
             FROM role_assignments ra
             JOIN roles r ON r.code = ra.role_id AND r.is_active
            WHERE ra.user_id    = app.request_user_id()
              AND ra.scope      = 'platform'
              AND ra.role_id    = p_role
              AND ra.revoked_at IS NULL
              AND ra.deleted_at IS NULL
              AND (ra.expires_at IS NULL OR ra.expires_at > now())
         );
$$;


--

--

CREATE FUNCTION app.is_ajo_member(p_ajo_id uuid) RETURNS boolean
    LANGUAGE sql STABLE
    AS $$
  -- Written as EXISTS rather than `= ANY(array(...))`: a set-returning
  -- function is not an array, and the two forms look interchangeable until the
  -- first one fails to compile.
  SELECT EXISTS (SELECT 1 FROM app.current_ajo_ids() AS live
                  WHERE live = p_ajo_id);
$$;


--

--

CREATE FUNCTION app.is_platform_staff() RETURNS boolean
    LANGUAGE sql STABLE
    AS $$
  SELECT app.has_platform_role('support')
      OR app.has_platform_role('risk_officer');
$$;


--

--

CREATE FUNCTION app.reject_mutation() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  RAISE EXCEPTION
    'table %.% is append-only; % is not permitted (txid=%)',
    TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP, txid_current()
    USING ERRCODE = 'restrict_violation',
          HINT = 'Corrections are made by posting a reversing entry, never by '
                 'editing or removing history.';
END;
$$;


--

--

CREATE FUNCTION app.request_actor_type() RETURNS text
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$
  SELECT COALESCE(
           nullif(current_setting('app.actor_type', true), ''),
           CASE WHEN app.request_user_id() IS NULL THEN 'anon' ELSE 'member' END
         );
$$;


--

--

CREATE FUNCTION app.request_user_id() RETURNS uuid
    LANGUAGE sql STABLE PARALLEL SAFE
    AS $$
  SELECT COALESCE(
           nullif(current_setting('app.user_id', true), '')::uuid,
           (nullif(current_setting('request.jwt.claim.sub', true), ''))::uuid
         );
$$;


--

--

COMMENT ON FUNCTION app.request_user_id() IS 'The authenticated user for this request, or null for an anonymous one. app.user_id is authoritative; request.jwt.claim.sub is the PostgREST path.';


--

--

CREATE FUNCTION app.shares_ajo_with(p_user_id uuid) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public', 'app'
    AS $$
  SELECT EXISTS (
           SELECT 1
             FROM ajo_members mine
             JOIN ajo_members theirs ON theirs.ajo_id = mine.ajo_id
            WHERE mine.user_id    = app.request_user_id()
              AND theirs.user_id   = p_user_id
              AND mine.deleted_at  IS NULL
              AND theirs.deleted_at IS NULL
              AND mine.status   IN ('invited','active','defaulted')
              AND theirs.status  IN ('invited','active','defaulted')
         );
$$;


--

--

CREATE FUNCTION app.touch_row() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at := now();
  NEW.version    := OLD.version + 1;
  RETURN NEW;
END;
$$;


--

--

CREATE FUNCTION app.uuidv7() RETURNS uuid
    LANGUAGE plpgsql PARALLEL SAFE
    AS $$
DECLARE
  b bytea;
BEGIN
  -- 48 bits of epoch milliseconds, big-endian, no sign bit issues.
  b := substring(int8send((EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::bigint) FROM 3);
  -- 80 bits of randomness: the last 10 bytes of a v4 UUID.
  b := b || substring(uuid_send(gen_random_uuid()) FROM 7);
  -- RFC 9562 version 7 -> high nibble of byte 6 is 0111.
  b := set_byte(b, 6, (get_byte(b, 6) & 15) | 112);
  -- RFC 9562 variant -> top two bits of byte 8 are 10.
  b := set_byte(b, 8, (get_byte(b, 8) & 63) | 128);
  RETURN encode(b, 'hex')::uuid;
END;
$$;


--

--

COMMENT ON FUNCTION app.uuidv7() IS 'RFC 9562 UUID version 7. Used as the DEFAULT for every primary key. Time-ordered, so B-tree index inserts stay local and `ORDER BY id` is a chronological ordering for free.';


--
