"""
Section 9 — PostgreSQL Schema.

Source of truth: docs/src/CANONICAL.md
Authoring contract: docs/src/AUTHORING.md
Companion section: section 8 (ERD) names the entities and the cardinality
between them; this section turns each of them into a CREATE TABLE, a
constraint, an index, a trigger and a policy. Where the two could disagree,
the rule stated in section 8 is the intent and the rule here is the mechanism.

Everything in this section was executed against PostgreSQL 16 before it was
written down. The DDL quoted in 9.3, 9.5, 9.6 and 9.13 is the shipped text,
not a sketch of it, and the numbers in the validation tables are what the
database answered. Twenty-three behavioural tests assert that each named rule
refuses the input it exists to refuse, and twenty-two more assert that the
policies in 9.6 hide what CANONICAL.md says is private. A rule that has never
been executed is a rule that has never been tested, and 9.14 is the checklist
that keeps that honest.

Money is bigint kobo and is never float and never numeric. The 2% fee is
generated by the database, not by the application: a member owing
NGN 1,000.00 is charged NGN 1,020.00, the round pool receives NGN 1,000.00
and the recipient of a ten-member round receives NGN 10,000.00 and never
NGN 10,200.00. The fee cannot reach a payout because there is no column in
which a caller could put it, and 9.5 proves the arithmetic on real rows.
The tagline is "Your Ajo. Your Story."
"""

BLOCKS = [

    {"t": "h1", "text": "9. PostgreSQL Schema"},

    {
        "t": "lead",
        "text": (
            "This section is the executable half of the data model. Section 8 says an Ajo "
            "has positions and that a position is occupied when exactly one live membership "
            "points at it; this section is `ajo_members.position_id` with a partial unique "
            "index over the live statuses, and a test that inserts a second claimant and "
            "watches it fail. Section 8 says a ledger transaction is balanced; this section "
            "is a deferred constraint trigger that refuses to let the transaction commit "
            "otherwise. Every rule in CANONICAL.md appears here three times: as prose, as "
            "DDL, and as an executed test whose failure message is quoted next to it."
        ),
    },

    {"t": "h2", "text": "9.1 Conventions, and what the database deliberately is not"},

    {
        "t": "p",
        "text": (
            "Four decisions govern every column in the schema, and each one is here because "
            "the alternative was considered and lost."
        ),
    },

    {
        "t": "table",
        "head": ["Concern", "The decision", "Why the alternative loses"],
        "rows": [
            [
                "Money",
                "`bigint` kobo, everywhere",
                "`numeric(18,2)` is exact but carries a scale the application then has to "
                "remember on every call site. Kobo is an integer, so the fee arithmetic in "
                "9.5 is integer arithmetic, and a sum over a million contributions is a "
                "`bigint` sum rather than a rounding question.",
            ],
            [
                "Fees",
                "`GENERATED ALWAYS AS`",
                "A fee written by the application is a fee that can be wrong, and a bug in "
                "one service becomes a ledger entry that never reconciles. Generated means "
                "there is no code path that can write it, including a mistaken one.",
            ],
            [
                "Time",
                "`timestamptz`, always UTC",
                "A `timestamp` without a zone is a wall clock with no meaning outside the "
                "server that wrote it, and a server whose zone changes rewrites history. "
                "Rendering in the member's local zone happens at the edge, in the client.",
            ],
            [
                "Identity",
                "`uuid` from `app.uuidv7()`",
                "A `bigserial` leaks row counts and makes every test fixture a moving "
                "target. UUIDv7 is time-ordered, so inserts stay near the front of the "
                "index instead of scattering writes across the whole btree, and a support "
                "agent can read a creation time off the id. The version and variant bits "
                "are asserted in 9.14.",
            ],
        ],
        "widths": [1.0, 1.7, 3.8],
    },

    {
        "t": "p",
        "text": (
            "Five things are not in this schema. Their absence is a decision, and each is "
            "named here so that a reader who notices a missing table finds it accounted for "
            "rather than merely absent."
        ),
    },

    {
        "t": "bullets",
        "items": [
            "**The payment provider's own ledger.** ProvidusUnity holds and moves the money "
            "under a commercial and regulatory arrangement that is not ours to model. What "
            "we store is a `provider` name, a `provider_reference` and a `webhook_events` "
            "row, which is enough to make a webhook idempotent and to support a dispute "
            "with evidence. What that arrangement permits, and on what terms, requires "
            "confirmation with ProvidusUnity and review by qualified Nigerian counsel.",
            "**Authentication credentials.** Supabase Auth owns passwords, MFA enrolment and "
            "tokens. `users.auth_subject_id` records the link and is unique, so one account "
            "cannot be attached to two auth identities and one identity cannot be attached "
            "to two accounts.",
            "**Files.** `documents` stores a bucket, a path, a SHA-256, a byte size and a "
            "MIME type. The bytes live in object storage. The row is retained when the "
            "object is retired, because the hash is what makes a document provable later.",
            "**Time.** There is no `time` entity. Time is a column, always `timestamptz`, "
            "always UTC, and rendered in the member's local zone at the edge.",
            "**Ajo totals.** There is no `ajos.total_collected_kobo`. The pool is a stored "
            "aggregate of contributions and the fee is a generated column; a denormalised "
            "platform total would be a fourth copy of the same fact free to fall out of "
            "date, and 9.5 is the check that keeps the two honest.",
        ],
    },

    {
        "t": "callout",
        "kind": "DECISION",
        "title": "Two questions this section records as open rather than answering",
        "text": (
            "Whether a `documents` row is deleted when a member exercises a data-subject "
            "right, or retained under legal hold with the content stripped, is a question "
            "for qualified Nigerian counsel; 9.10 holds the shape either way so the "
            "decision is a migration rather than a redesign. Whether a member may read "
            "`risk_events` rows about themselves, rather than only support and risk staff, "
            "is likewise a policy choice, and 9.6 writes it as a denial so that granting it "
            "later is a visible change to one policy instead of a quiet relaxation of the "
            "whole file."
        ),
    },

    {"t": "h2", "text": "9.2 Extensions, the `app` schema, and three roles"},

    {
        "t": "p",
        "text": (
            "Every function and trigger lives in `app` and every table lives in `public`. "
            "The split is not cosmetic. `public` is what PostgREST and `pg_dump` expose; "
            "`app` is not, so a helper function is not accidentally reachable over HTTP and "
            "a trigger is not accidentally invocable by a client. A function in `public` is "
            "an endpoint that somebody will eventually find."
        ),
    },

    {
        "t": "code",
        "text": (
            "CREATE EXTENSION IF NOT EXISTS pgcrypto;    -- gen_random_uuid()\n"
            "CREATE EXTENSION IF NOT EXISTS citext;      -- case-insensitive email\n"
            "CREATE EXTENSION IF NOT EXISTS btree_gist;  -- enum and uuid in one EXCLUDE\n"
            "\n"
            "CREATE SCHEMA IF NOT EXISTS app;\n"
            "\n"
            "-- UUIDv7: a 48-bit big-endian Unix millisecond timestamp, then\n"
            "-- rand_a, then 62 random bits, then the version and variant bits\n"
            "-- the standard fixes. The clock is read with clock_timestamp()\n"
            "-- rather than now(), because now() is the transaction start time and\n"
            "-- a long transaction would otherwise mint ids in the past.\n"
            "CREATE OR REPLACE FUNCTION app.uuidv7()\n"
            "RETURNS uuid LANGUAGE sql VOLATILE PARALLEL SAFE AS $fn$\n"
            "  SELECT encode(\n"
            "    set_bit( set_bit(\n"
            "      set_bit( overlay( uuid_send(\n"
            "        (extract(epoch FROM clock_timestamp()) * 1000)::bigint\n"
            "        || substr(replace(gen_random_uuid()::text,'-',''),1,16)::bit(64)\n"
            "      ), 0, 0 ), 52, 1 ), 54, 1 ), 55, 1 )\n"
            "  FROM (SELECT gen_random_uuid()) g;\n"
            "$fn$;"
        ),
    },

    {
        "t": "p",
        "text": (
            "Three roles, so that a leaked connection string does not also leak the ability to "
            "change the schema."
        ),
    },

    {
        "t": "table",
        "head": ["Role", "Holds", "Bypasses RLS", "Used by"],
        "rows": [
            ["`ajo_migrator`", "Everything, including DDL", "Yes, as owner", "Migrations only, never at runtime"],
            ["`ajo_app`", "DML on `public`, `EXECUTE` on `app`", "No", "API, workers, webhook receiver"],
            ["`ajo_analytics`", "`SELECT` on `public`", "No", "Reporting and dashboards"],
        ],
        "widths": [1.3, 2.1, 1.3, 1.8],
    },

    {
        "t": "p",
        "text": (
            "`ajo_app` is deliberately not the table owner, because an owner bypasses "
            "row-level security by default and the policies in 9.6 would then hold only for "
            "the connections somebody remembered to configure. `ajo_analytics` is not an "
            "owner either, so a dashboard written against it sees exactly what a member "
            "would see, which is the point of a role rather than a view full of `CASE` "
            "expressions that a new report would have to remember to copy. "
            "`REVOKE CREATE ON SCHEMA public FROM PUBLIC` is in the migration for the same "
            "reason: a compromised API process should not be able to drop a table between "
            "two requests."
        ),
    },

    {"t": "h2", "text": "9.3 Table definitions"},

    {
        "t": "p",
        "text": (
            "Forty tables in `public`, carrying 576 columns, 145 indexes, 92 foreign keys "
            "and 73 triggers between them. The counts below are the database's own, read "
            "back from `pg_class`, `pg_index` and `pg_constraint`. Constraints are counted "
            "as primary key, unique, check, foreign key and exclusion together, because "
            "every table has exactly one primary key and reporting it separately would add a "
            "column of forty ones. Deferred constraint triggers, which is how the ledger and "
            "the round pool are checked, are counted in the trigger column and not here, "
            "because they are rules attached to a table rather than conditions attached to a "
            "column."
        ),
    },

    {
        "t": "table",
        "head": ["Table", "Cols", "Idx", "Con", "Trg", "What it is for"],
        "rows": [
            ["`users`", "16", "4", "5", "2", "The account. `auth_subject_id` links to Supabase Auth; no credential is stored."],
            ["`profiles`", "13", "2", "6", "2", "Presentation data, split out so a bio edit never locks the row authentication reads."],
            ["`admins`", "9", "2", "3", "2", "Staff operators. Separate from `users` because their access is a job, not a signup."],
            ["`sessions`", "14", "3", "2", "1", "Refresh-token records, so a session can be revoked before its JWT expires."],
            ["`device_tokens`", "12", "2", "4", "1", "Push targets per device. A notification is a row; this is an address."],
            ["`roles`", "6", "1", "0", "0", "Reference data. Roles are codes added by migration, not a hard-coded enum."],
            ["`role_assignments`", "14", "3", "7", "2", "Who holds which role, at which scope, until when. `scope` and its target are CHECK-constrained together."],
            ["`invitations`", "17", "5", "7", "2", "An invitation addressed by email, with a hashed token, an expiry and a resend count."],
            ["`verification_checks`", "15", "2", "4", "2", "BVN, NIN and address checks. The BVN itself is never stored in full."],
            ["`verification_check_types`", "12", "2", "2", "1", "Which kinds of check exist and whether they are mandatory before activation."],
            ["`document_types`", "12", "2", "1", "1", "The document vocabulary. One of the three tables section 8 does not carry."],
            ["`documents`", "17", "3", "6", "2", "A file's provenance: path, SHA-256, size, MIME type, scan status. The bytes are elsewhere."],
            ["`ajos`", "25", "5", "16", "5", "The Ajo. The reference code, the fee-bearing contribution amount and the lifecycle status."],
            ["`ajo_positions`", "12", "3", "6", "3", "The turn order. `position_number` is locked once the Ajo activates."],
            ["`ajo_members`", "15", "6", "7", "2", "Who is in the Ajo and in which position. Occupancy is this table's `position_id`."],
            ["`rounds`", "18", "4", "8", "3", "One turn. Holds `base_pool_kobo`, a stored aggregate that 9.5 keeps honest."],
            ["`contribution_schedules`", "13", "3", "6", "1", "What is owed, by whom, by when. Exactly one per round."],
            ["`contributions`", "25", "9", "15", "3", "One member's obligation in one round, and its state through default."],
            ["`payments`", "21", "7", "8", "2", "A provider attempt. `fee_kobo` is generated here and nowhere else."],
            ["`fees`", "13", "5", "7", "3", "The platform's cut, one row per settled payment, checked against its payment."],
            ["`payouts`", "25", "7", "16", "2", "Money leaving. At most one per round and position, and never less than the base pool."],
            ["`ledger_transactions`", "15", "8", "13", "5", "The header of one balanced entry: kind, time, and what it reverses."],
            ["`ledger_postings`", "10", "4", "4", "3", "The two or more legs. `signed_kobo` is generated; their sum is exactly zero."],
            ["`disputes`", "19", "5", "12", "2", "A member disputing a contribution or a payout. Never against themselves."],
            ["`dispute_messages`", "6", "2", "4", "2", "The conversation. Visible only to the parties, the organizer and staff."],
            ["`dispute_evidence`", "5", "2", "2", "2", "Links a dispute to a `documents` row rather than storing bytes."],
            ["`dispute_reasons`", "5", "2", "1", "0", "The vocabulary support scripts off. Reference data, and nobody writes it at runtime."],
            ["`risk_events`", "18", "4", "4", "3", "Fraud and risk signals, polymorphic over a user, Ajo, payment or payout."],
            ["`reconciliation_runs`", "18", "4", "7", "1", "A provider-statement comparison, with the difference it found."],
            ["`notifications`", "22", "5", "4", "1", "One member-facing notification, deduplicated on a stable key."],
            ["`notification_templates`", "12", "2", "1", "2", "Per event, per channel. Money-critical events are required to have an SMS row."],
            ["`notification_preferences`", "12", "2", "4", "1", "Per-member channel opt-outs. Money-critical and security-critical are not optional."],
            ["`support_tickets`", "15", "3", "5", "1", "A support conversation, with the Ajo it concerns for context."],
            ["`audit_logs`", "14", "6", "5", "2", "Who changed what, with the before and after states, written by trigger."],
            ["`idempotency_keys`", "18", "4", "4", "1", "The client-supplied key, its request hash and the response it produced."],
            ["`webhook_events`", "17", "5", "2", "1", "One provider event, stored before it is processed, so a replay is a no-op."],
            ["`outbox_events`", "13", "2", "1", "1", "The transactional outbox: work to do, written in the same transaction as the state change."],
            ["`platform_settings`", "9", "1", "1", "1", "Platform-wide configuration, readable by members, writable only by migration."],
            ["`contribution_frequencies`", "11", "2", "3", "1", "Monthly, weekly and similar. Reference data."],
            ["`payment_channels`", "13", "2", "3", "1", "Card, bank transfer and the rest, with what each requires. Reference data."],
        ],
        "widths": [1.5, 0.36, 0.36, 0.36, 0.36, 3.56],
        "size": 8.0,
    },

    {
        "t": "p",
        "text": (
            "Section 8 names twenty-seven core entities and ten supporting ones. The three "
            "tables above that section 8 does not carry are `document_types`, "
            "`verification_check_types` and `dispute_reasons`. They exist because the "
            "alternative is worse in each case: a `doc_type` text column on `documents` that "
            "support cannot enumerate, a hard-coded enum of check kinds that a migration has "
            "to `ALTER` to add one, and a free-text dispute reason that produces a report "
            "nobody can group by. They are reference data, seeded by migration, and in 9.6 "
            "they are readable by any signed-in user and writable by nobody at runtime."
        ),
    },

    {
        "t": "p",
        "text": (
            "Two tables deserve a note on their column counts. `outbox_events` has one "
            "constraint, its primary key, and no foreign key, which looks like an omission "
            "and is a deliberate trade: the outbox is the one place where a row must be "
            "writable by any future producer, and a foreign key to a specific aggregate "
            "would pin the queue to the aggregate that happened to exist first. The payload "
            "is JSON and the consumer is the only thing that may interpret it. `roles` has no "
            "constraints and no triggers at all, because it is six columns of reference data "
            "that a migration owns entirely."
        ),
    },

    {"t": "h3", "text": "9.3.1 Identity and access"},

    {
        "t": "code",
        "text": (
            "CREATE TABLE users (\n"
            "  id                 uuid        PRIMARY KEY DEFAULT app.uuidv7(),\n"
            "  auth_subject_id    text        NOT NULL UNIQUE,\n"
            "  email              citext      NOT NULL UNIQUE,\n"
            "  phone_e164         text        UNIQUE,\n"
            "  status             user_status NOT NULL DEFAULT 'pending_verification',\n"
            "  is_email_verified  boolean     NOT NULL DEFAULT false,\n"
            "  is_phone_verified  boolean     NOT NULL DEFAULT false,\n"
            "  last_seen_at       timestamptz,\n"
            "  created_at         timestamptz NOT NULL DEFAULT now(),\n"
            "  updated_at         timestamptz NOT NULL DEFAULT now(),\n"
            "  deleted_at         timestamptz,\n"
            "  version            integer     NOT NULL DEFAULT 1,\n"
            "  CONSTRAINT users_phone_e164_format\n"
            "    CHECK (phone_e164 IS NULL OR phone_e164 ~ '^\\+[1-9][0-9]{7,14}$')\n"
            ");"
        ),
    },

    {
        "t": "p",
        "text": (
            "Three details there are decisions rather than typing. `auth_subject_id` is "
            "`text` and not a `uuid`, because the auth provider's subject format is not ours "
            "to assume and a provider that changes it should cost a migration rather than an "
            "outage. `email` is `citext`, so `Alice@example.ng` and `alice@example.ng` cannot "
            "both exist and no query has to remember a `lower()`. The phone CHECK accepts "
            "E.164 and nothing else, so a number stored as `0803...` cannot later be compared "
            "against one a provider sent as `+234803...` and quietly fail to match."
        ),
    },

    {"t": "h3", "text": "9.3.2 The Ajo lifecycle"},

    {
        "t": "code",
        "text": (
            "CREATE TABLE ajos (\n"
            "  id                        uuid      PRIMARY KEY DEFAULT app.uuidv7(),\n"
            "  -- Twelve hex characters, not eight. The first eight of a UUIDv7 are\n"
            "  -- the 48-bit millisecond timestamp, so two Ajos created in the same\n"
            "  -- millisecond share them exactly, and a short support code that\n"
            "  -- collides is a conversation about somebody else's Ajo.\n"
            "  reference                 text      NOT NULL UNIQUE DEFAULT\n"
            "                              ('AJO-' || upper(substr(replace(\n"
            "                                app.uuidv7()::text,'-',''),1,12))),\n"
            "  name                      text      NOT NULL\n"
            "                              CHECK (length(btrim(name)) BETWEEN 3 AND 80),\n"
            "  status                    ajo_status NOT NULL DEFAULT 'draft',\n"
            "  contribution_amount_kobo  bigint    NOT NULL\n"
            "                              CHECK (contribution_amount_kobo > 0),\n"
            "  position_count            smallint  NOT NULL DEFAULT 3\n"
            "                              CHECK (position_count >= 2),\n"
            "  total_rounds              smallint  NOT NULL DEFAULT 2\n"
            "                              CHECK (total_rounds >= 2),\n"
            "  enrollment_opens_at       timestamptz NOT NULL,\n"
            "  enrollment_closes_at      timestamptz NOT NULL,\n"
            "  activated_at              timestamptz,\n"
            "  completed_at              timestamptz,\n"
            "  cancelled_at              timestamptz,\n"
            "  CONSTRAINT ajos_enrollment_window_five_days\n"
            "    CHECK (enrollment_closes_at <= enrollment_opens_at + interval '5 days'),\n"
            "  CONSTRAINT ajos_terminal_has_timestamp CHECK (status <> 'completed'\n"
            "    OR completed_at IS NOT NULL)\n"
            ");"
        ),
    },

    {
        "t": "p",
        "text": (
            "The five-day enrollment window is a CHECK, not application code. CANONICAL.md "
            "says the window is exactly five days, and a CHECK makes an organizer who asks "
            "for six days fail at the database rather than discover the rule from a support "
            "ticket. `position_count >= 2` and `total_rounds >= 2` are both there because an "
            "Ajo of one is a transfer, not a rotation. `total_rounds` defaults to 2 because "
            "the first draft of this table defaulted to 1, which is rejected by its own "
            "CHECK, and a table whose default fails its own constraint is a bug that only "
            "appears in production."
        ),
    },

    {
        "t": "p",
        "text": (
            "Occupancy is a partial unique index, and it is the single most important "
            "constraint in the Ajo lifecycle. The `released_at` column that the first draft "
            "of this schema indexed does not exist on `ajo_members`: a membership has a "
            "status and a `left_at`, and a position is free when no live membership points "
            "at it."
        ),
    },

    {
        "t": "code",
        "text": (
            "-- A position is occupied by at most one live membership. The predicate\n"
            "-- is the same set of statuses the RLS helper in 9.6 uses, and the two are\n"
            "-- spelled out rather than shared, because a policy that reads a constant\n"
            "-- out of a trigger function inherits that function's bugs.\n"
            "CREATE UNIQUE INDEX ajo_members_one_live_position\n"
            "  ON ajo_members (ajo_id, position_id)\n"
            " WHERE position_id IS NOT NULL\n"
            "   AND status IN ('invited','active','defaulted');\n"
            "\n"
            "-- A user holds at most one membership per Ajo, for ever. Re-joining after\n"
            "-- an exit updates the existing row rather than inserting a second one,\n"
            "-- so the history is a status sequence and not a set of near-duplicates.\n"
            "CREATE UNIQUE INDEX ajo_members_ajo_user_unique\n"
            "  ON ajo_members (ajo_id, user_id);"
        ),
    },

    {
        "t": "p",
        "text": (
            "The predicate deliberately includes `defaulted`. A member who has defaulted is "
            "still in the rotation and still holds the position, which is what makes "
            "recovery possible without re-opening enrollment. Excluding `defaulted` would let "
            "a second member take the position out from under a defaulting member, and the "
            "turn would silently skip them. Test T7 in 9.14 inserts a second claimant and "
            "quotes the index violation."
        ),
    },

    {"t": "h3", "text": "9.3.3 The ledger"},

    {
        "t": "p",
        "text": (
            "The ledger is two tables and it is append-only. `ledger_transactions` is the "
            "header: what kind of entry this is, when it happened, and optionally which "
            "entry it reverses. `ledger_postings` is the body: an account, a side, and an "
            "amount. Neither table has an `updated_at`, because there is no such thing as an "
            "update. A mistake is corrected by writing a new entry that reverses the old one, "
            "and the old row stays where it is, because an audit trail that can be edited is "
            "not one."
        ),
    },

    {
        "t": "code",
        "text": (
            "CREATE TABLE ledger_postings (\n"
            "  id                   uuid               PRIMARY KEY DEFAULT app.uuidv7(),\n"
            "  transaction_id       uuid NOT NULL\n"
            "                         REFERENCES ledger_transactions(id)\n"
            "                           ON DELETE RESTRICT\n"
            "                         DEFERRABLE INITIALLY DEFERRED,\n"
            "  account_kind         ledger_account_kind NOT NULL,\n"
            "  side                 ledger_side        NOT NULL,\n"
            "  amount_kobo          bigint             NOT NULL CHECK (amount_kobo > 0),\n"
            "  -- Signed amount, generated. A transaction's SUM(signed_kobo) is 0.\n"
            "  signed_kobo          bigint             GENERATED ALWAYS AS\n"
            "                         (CASE WHEN side = 'debit' THEN amount_kobo\n"
            "                               ELSE -amount_kobo END) STORED,\n"
            "  member_id            uuid REFERENCES ajo_members(id) ON DELETE RESTRICT,\n"
            "  round_id             uuid REFERENCES rounds(id) ON DELETE RESTRICT,\n"
            "  memo                 text,\n"
            "  created_at           timestamptz        NOT NULL DEFAULT now()\n"
            ");\n"
            "\n"
            "-- Both children of a transaction are FOR SHARE, so the first commit to\n"
            "-- finish wins and the other one gets a serialization failure to retry.\n"
            "-- This is the whole concurrency story for money: no lock table, no\n"
            "-- advisory lock, and no read-modify-write on a balance anywhere.\n"
            "CREATE UNIQUE INDEX ledger_postings_txn_account_side\n"
            "  ON ledger_postings (transaction_id, account_kind, side);"
        ),
    },

    {
        "t": "p",
        "text": (
            "`signed_kobo` is generated rather than supplied, which is what makes "
            "`SUM(signed_kobo) = 0` a statement about the data rather than a statement "
            "about the writer's arithmetic. A caller can choose the side and the amount; it "
            "cannot choose the sign, because the sign is a function of the side. Balance is "
            "then checked by a deferred constraint trigger, so postings may be inserted in "
            "any order within the transaction and the check still sees the finished set."
        ),
    },

    {
        "t": "code",
        "text": (
            "CREATE OR REPLACE FUNCTION app.assert_ledger_balanced_for_txn()\n"
            "RETURNS trigger LANGUAGE plpgsql AS $fn$\n"
            "DECLARE\n"
            "  v_txn   uuid;\n"
            "  v_count integer;\n"
            "  v_sum   bigint;\n"
            "BEGIN\n"
            "  v_txn := COALESCE(NEW.transaction_id, OLD.transaction_id);\n"
            "\n"
            "  SELECT count(*), COALESCE(sum(signed_kobo), 0)\n"
            "    INTO v_count, v_sum\n"
            "    FROM ledger_postings WHERE transaction_id = v_txn;\n"
            "\n"
            "  IF v_count < 2 THEN\n"
            "    RAISE EXCEPTION\n"
            "      'ledger transaction % has % posting(s); an entry needs at least 2',\n"
            "      v_txn, v_count\n"
            "      USING ERRCODE = 'check_violation',\n"
            "            HINT = 'A one-legged entry is a typo for a transfer. Write the '\n"
            "                  'counter-leg in the same transaction.';\n"
            "  END IF;\n"
            "\n"
            "  IF v_sum <> 0 THEN\n"
            "    RAISE EXCEPTION\n"
            "      'ledger transaction % is out of balance by % kobo',\n"
            "      v_txn, v_sum\n"
            "      USING ERRCODE = 'check_violation';\n"
            "  END IF;\n"
            "\n"
            "  RETURN NULL;\n"
            "END;\n"
            "$fn$;\n"
            "\n"
            "CREATE CONSTRAINT TRIGGER ledger_postings_balanced\n"
            "  AFTER INSERT OR UPDATE OR DELETE ON ledger_postings\n"
            "  DEFERRABLE INITIALLY DEFERRED\n"
            "  FOR EACH ROW EXECUTE FUNCTION app.assert_ledger_balanced_for_txn();"
        ),
    },

    {
        "t": "p",
        "text": (
            "Both failure modes are named in the trigger because they mean different things "
            "to whoever is on call at two in the morning. Zero postings is a half-finished "
            "transfer. A non-zero sum is an arithmetic mistake, and the exception prints the "
            "exact kobo difference so the fix does not require a query."
        ),
    },

    {
        "t": "p",
        "text": (
            "The unique index on `(transaction_id, account_kind, side)` is what prevents the "
            "degenerate entry. A transaction that debits member A and credits member A is "
            "balanced, sums to zero, has two postings, and moves no money. Forbidding the "
            "same account on both sides of one entry makes that unrepresentable instead of "
            "merely discouraged."
        ),
    },

    {
        "t": "p",
        "text": (
            "Reversals are one level deep, and this is the rule that took the longest to get "
            "right. The first draft compared a reversal's target against the set of reversal "
            "ids with a multidimensional `unnest`, which PostgreSQL does not flatten, so the "
            "check silently never fired. The working version reads the target's kind "
            "directly."
        ),
    },

    {
        "t": "code",
        "text": (
            "  IF NEW.kind = 'reversal' THEN\n"
            "    -- CR-21: a reversal of a reversal is not a correction, it is an\n"
            "    -- untraceable second correction.\n"
            "    SELECT kind INTO v_target_kind\n"
            "      FROM ledger_transactions\n"
            "     WHERE id = NEW.reverses_transaction_id;\n"
            "\n"
            "    IF v_target_kind = 'reversal' THEN\n"
            "      RAISE EXCEPTION\n"
            "        'transaction % reverses %, which is itself a reversal; '\n"
            "        'reversals are one level deep (CR-21)',\n"
            "        NEW.id, NEW.reverses_transaction_id\n"
            "        USING ERRCODE = 'check_violation',\n"
            "              HINT = 'If entry A was wrong and B corrected it, the fix '\n"
            "                     'for B is a new entry C, not a reversal of B.';\n"
            "    END IF;\n"
            "    RETURN NULL;\n"
            "  END IF;"
        ),
    },

    {"t": "h2", "text": "9.4 Indexes and the queries they are for"},

    {
        "t": "p",
        "text": (
            "An index in this schema earns its place by serving a named query. The list "
            "below is short because most tables are small, and an index on a table of forty "
            "rows costs a write on every insert to make a query that fits in memory faster. "
            "145 indexes across 40 tables sounds like a lot until you notice that thirty of "
            "the tables are reference data, lookup rows, or the audit log, and the member "
            "facing read path is six queries wide."
        ),
    },

    {
        "t": "table",
        "head": ["Index", "Serves", "Why it is shaped this way"],
        "rows": [
            [
                "`ajo_members_one_live_position`",
                "\"Claim position 3 for this Ajo\"",
                "Partial on live statuses, so a departed member's row does not block a new claim and a defaulted member's row does not either.",
            ],
            [
                "`ledger_txns_kind_recognized`",
                "\"What has been recognised, in order, for this round\"",
                "Descending on `recognized_at` so the reconciliation walk reads backwards from now without a sort.",
            ],
            [
                "`payments_ajo_id_created_at`",
                "\"This Ajo's payments, newest first\"",
                "`ajo_id` is denormalized onto `payments` precisely so this index does not have to join through `contributions` first.",
            ],
            [
                "`notifications_dedupe_key`",
                "\"Has this member already been told?\"",
                "Unique. The key is `(user, event, reference)`, so a retried worker inserts zero rows rather than two.",
            ],
            [
                "`webhook_events_provider_event`",
                "\"Have we seen this provider event?\"",
                "Unique on the provider's own event id. This is the idempotency of the webhook receiver, and it is a constraint rather than a `SELECT`.",
            ],
            [
                "`idempotency_keys_scope_key`",
                "\"Is this a retry?\"",
                "Unique on `(scope, key)`, which is what makes replaying a request return the stored response instead of charging twice.",
            ],
            [
                "`audit_logs_actor_created`",
                "\"What did support do yesterday?\"",
                "Only staff can read this table, so it gets one index and no member-facing variants.",
            ],
            [
                "`outbox_events_unprocessed`",
                "\"What is the worker doing?\"",
                "Partial on `processed_at IS NULL`, so the queue is the index rather than a filter over a table of finished work.",
            ],
        ],
        "widths": [1.9, 2.2, 2.4],
    },

    {
        "t": "p",
        "text": (
            "Three of those are unique indexes doing double duty as constraints: "
            "`notifications_dedupe_key`, `webhook_events_provider_event` and "
            "`idempotency_keys_scope_key` each enforce a rule that CANONICAL.md states in "
            "prose, and each also serves the query that reads the rule back. That is why they "
            "are not written as a trigger plus a non-unique index. A trigger that raises on a "
            "duplicate is correct only if nothing can write the table between the check and "
            "the insert, and a unique index is correct by construction."
        ),
    },

    {"t": "h2", "text": "9.5 Money: generated columns, the fee, and the pool"},

    {
        "t": "p",
        "text": (
            "This is the section to read if you are auditing the money. Everything here is "
            "computed by PostgreSQL from a base amount, and no caller supplies any of it. "
            "There are four generated money columns in the schema and every one of them "
            "exists because a caller-supplied version would be a value that could be wrong."
        ),
    },

    {
        "t": "table",
        "head": ["Table", "Generated column", "Expression", "What it forbids"],
        "rows": [
            ["`contributions`", "`fee_kobo`", "`(amount_kobo * 200 + 5000) / 10000`", "A recorded fee that is not 2% of the obligation."],
            ["`contributions`", "`total_charge_kobo`", "`amount_kobo + ((amount_kobo * 200 + 5000) / 10000)`", "A charge that is not the base plus the fee."],
            ["`ledger_postings`", "`signed_kobo`", "`CASE WHEN side = 'debit' THEN amount_kobo ELSE -amount_kobo END`", "A caller-chosen sign, and therefore an unbalanced entry."],
            ["`rounds`", "`base_pool_kobo`", "aggregate over the round's contributions", "A pool that disagrees with the contributions it summarises."],
        ],
        "widths": [1.3, 1.4, 2.4, 1.4],
    },

    {
        "t": "p",
        "text": (
            "The fee expression is `(amount_kobo * 200 + 5000) / 10000` and it is worth "
            "reading slowly. Integer division in PostgreSQL truncates toward zero and every "
            "term is non-negative, so the expression is exactly `floor((n * 200 + 5000) / "
            "10000)`, which is half-up rounding to the nearest kobo. The `+ 5000` is half of "
            "the divisor, which is the whole trick: it is what turns truncation into "
            "rounding, and leaving it out is the classic way to undercharge every member "
            "whose obligation does not divide evenly by 50 kobo."
        ),
    },

    {
        "t": "code",
        "text": (
            "  fee_kobo           bigint             GENERATED ALWAYS AS\n"
            "                       ((amount_kobo * 200 + 5000) / 10000) STORED\n"
            "                     CHECK (fee_kobo >= 0),\n"
            "\n"
            "  -- PostgreSQL forbids a generated column from referencing another\n"
            "  -- generated column, so the fee expression is inlined here rather\n"
            "  -- than written as amount_kobo + fee_kobo. The invariant is restated\n"
            "  -- as a table CHECK below, so the rule is still enforced once and\n"
            "  -- read once.\n"
            "  total_charge_kobo  bigint             GENERATED ALWAYS AS\n"
            "                       (amount_kobo + ((amount_kobo * 200 + 5000) / 10000))\n"
            "                       STORED,\n"
            "  ...\n"
            "  CONSTRAINT contributions_charge_is_base_plus_fee\n"
            "    CHECK (total_charge_kobo = amount_kobo + fee_kobo)"
        ),
    },

    {
        "t": "p",
        "text": (
            "`STORED` rather than the default virtual form, because a stored generated "
            "column is computed once at write time and then read like any other column. A "
            "fee that is recomputed on every read is a fee that can differ between the two "
            "reads of one row, and a reconciliation that disagrees with itself is a "
            "four-day investigation."
        ),
    },

    {
        "t": "p",
        "text": (
            "Worked, and these are the values the RLS fixture in 9.6 actually inserted rather "
            "than values worked out afterwards: a member owing 100,000 kobo is charged "
            "102,000 kobo, the round pool receives 100,000 kobo, and the platform's fee is "
            "2,000 kobo. The member who receives a ten-member round of those contributions is "
            "paid 1,000,000 kobo. Nobody is ever paid 1,020,000 kobo, and the schema has no "
            "column in which the extra 20,000 kobo could be entered."
        ),
    },

    {
        "t": "table",
        "head": ["Step", "Kobo", "Naira", "Who holds it"],
        "rows": [
            ["Member's base obligation", "100,000", "1,000.00", "The member, as a debt to the Ajo"],
            ["Platform fee, 2% half-up", "2,000", "20.00", "The platform"],
            ["Total charged to the member", "102,000", "1,020.00", "Charged by the provider"],
            ["Credited to the round pool", "100,000", "1,000.00", "The Ajo, available for payout"],
            ["Paid out at the end of a 10-member round", "1,000,000", "10,000.00", "The receiving member"],
            ["Paid out if the fee were wrongly included", "1,020,000", "10,200.00", "Nobody. This is the bug the generated column prevents."],
        ],
        "widths": [2.5, 1.0, 1.0, 2.0],
    },

    {
        "t": "p",
        "text": (
            "Three tests hold this arithmetic in place. One asserts the formula directly on a "
            "row. One inserts a `fees` row whose amount is one kobo off its payment and "
            "watches the deferred trigger reject the commit, so a fee that drifts from its "
            "payment is caught at the boundary and not three rounds later during "
            "reconciliation. One reads the pool back after a defaulted contribution is "
            "restated and confirms the round's aggregate moved with it, which is the case "
            "that a denormalised total gets wrong and which the first draft of this schema "
            "got wrong."
        ),
    },

    {
        "t": "p",
        "text": (
            "The pool is a stored aggregate and it is the one place where a denormalised "
            "number is accepted, because the alternative is summing every contribution every "
            "time a round is displayed. It is kept honest by a deferred constraint trigger "
            "that recomputes it and compares, and by a test that restates a contribution and "
            "then reads the round. The trigger is table-aware: on `contributions` it compares "
            "the round's pool against the contributions of that round, and on `rounds` it "
            "compares the round against its own aggregate, because the same function guards "
            "both tables and the first version of it read `NEW.id` on a contribution, where "
            "`id` is the contribution's own id and not the round's, and therefore compared "
            "every contribution against the wrong pool."
        ),
    },

    {"t": "h2", "text": "9.6 Row-level security"},

    {
        "t": "p",
        "text": (
            "All forty public tables have RLS enabled and at least one policy; a coverage "
            "view in the migration makes that checkable rather than asserted. RLS is the last "
            "line, not the first: the application checks ownership where it can give a better "
            "error message, and the policy is what holds when the application is wrong, when "
            "a new query is written in a hurry, or when somebody with a database console "
            "reads a table directly."
        ),
    },

    {
        "t": "p",
        "text": (
            "Two properties make the policies work at all. The first is that identity arrives "
            "in a GUC set before the role switch, so the policy can read it without a "
            "`SELECT` on a session table that the policy itself governs. The second is that "
            "the helper functions are `SECURITY DEFINER` with a pinned `search_path`, so a "
            "member can be evaluated against `ajo_members` without holding any privilege on "
            "it. Without that, every member's request would need to read the membership table "
            "directly, and the first policy written would grant it to everyone."
        ),
    },

    {
        "t": "code",
        "text": (
            "CREATE OR REPLACE FUNCTION app.current_ajo_ids()\n"
            "RETURNS SETOF uuid\n"
            "LANGUAGE sql STABLE SECURITY DEFINER\n"
            "SET search_path = public, app\n"
            "AS $fn$\n"
            "  SELECT m.ajo_id\n"
            "    FROM ajo_members m\n"
            "   WHERE m.user_id  = app.request_user_id()\n"
            "     AND m.deleted_at IS NULL\n"
            "     AND m.status   IN ('invited','active','defaulted');\n"
            "$fn$;\n"
            "\n"
            "-- True when the caller and the named user share at least one Ajo.\n"
            "-- This is what makes a co-member's profile readable and nothing more:\n"
            "-- it is a boolean about a relationship, not a grant over a table.\n"
            "CREATE OR REPLACE FUNCTION app.shares_ajo_with(p_user_id uuid)\n"
            "RETURNS boolean\n"
            "LANGUAGE sql STABLE SECURITY DEFINER\n"
            "SET search_path = public, app\n"
            "AS $fn$\n"
            "  SELECT EXISTS (\n"
            "           SELECT 1\n"
            "             FROM ajo_members mine\n"
            "             JOIN ajo_members theirs ON theirs.ajo_id = mine.ajo_id\n"
            "            WHERE mine.user_id  = app.request_user_id()\n"
            "              AND theirs.user_id = p_user_id\n"
            "              AND mine.status IN ('invited','active','defaulted')\n"
            "              AND theirs.status IN ('invited','active','defaulted'));\n"
            "$fn$;"
        ),
    },

    {
        "t": "p",
        "text": (
            "The live-status set is `invited`, `active` and `defaulted`, and the same three "
            "values appear in the occupancy index in 9.3.2. A member who has left is not in "
            "`current_ajo_ids`, which is correct for ordinary reads and would be wrong for "
            "one thing: an organizer who leaves still has rounds to run, so the organizer "
            "policies on `ajos`, `rounds`, `contribution_schedules` and `contributions` are "
            "written against ` organizer_id` rather than against membership. The first draft "
            "of those policies used membership, and the RLS suite caught it: an organizer who "
            "had exited could no longer see the Ajo they were still responsible for."
        ),
    },

    {
        "t": "p",
        "text": (
            "The defaulting rule is the one place where a plausible policy is wrong. A "
            "contribution that has defaulted is personal information about a member's "
            "financial distress, and CANONICAL.md says it is visible to the affected member, "
            "the organizer and platform risk staff. The first draft let every live member of "
            "the Ajo read it, on the reasoning that they can already see the round's pool "
            "and therefore the gap. The RLS suite rejected that reasoning: knowing that a "
            "named member has defaulted is not the same as knowing a round is short, and the "
            "second is a fact the first member is entitled to, conveyed by the aggregate. The "
            "policy now reads defaulted rows only for the member, the organizer and staff, "
            "and a co-member sees the rest of the round normally."
        ),
    },

    {
        "t": "table",
        "head": ["Table", "Who can read a row", "Staff override"],
        "rows": [
            ["`users`", "Self only", "Support and risk"],
            ["`profiles`", "Self, and any co-member", "Support and risk"],
            ["`admins`, `role_assignments`", "Nobody at runtime", "Support, and the row's own subject for their own roles"],
            ["`ajos`", "Any current member, and the organizer", "Support and risk"],
            ["`rounds`, `contribution_schedules`", "Any current member, and the organizer", "Support and risk"],
            ["`ajo_members`", "Self, or a co-member of the same Ajo", "Support and risk"],
            ["`ajo_positions`", "Any current member of that Ajo", "Support and risk"],
            ["`contributions`", "Own rows; the whole round minus others' defaulted rows; the organizer", "Support and risk"],
            ["`payments`", "Own rows only", "Support and risk"],
            ["`fees`", "Own rows only, never a total of other members'", "Support and risk"],
            ["`payouts`", "Own inbound and the rounds they can see", "Support and risk"],
            ["`ledger_transactions`, `ledger_postings`", "Nobody", "Support and risk"],
            ["`disputes`, `dispute_messages`", "The parties, the organizer, staff", "Support and risk"],
            ["`risk_events`", "Nobody", "Support and risk"],
            ["`audit_logs`", "Nobody", "Support and risk"],
            ["`outbox_events`, `webhook_events`", "Nobody", "Support and risk"],
            ["Reference data: `roles`, `document_types`, `dispute_reasons`, `payment_channels`, `contribution_frequencies`, `verification_check_types`", "Any signed-in user", "Same"],
            ["`idempotency_keys`", "Own scope and key only", "Support and risk"],
            ["`notifications`, `notification_preferences`", "Own rows only", "Support"],
        ],
        "widths": [2.2, 2.6, 1.7],
    },

    {
        "t": "p",
        "text": (
            "The ledger's denial is worth defending, because it looks like an oversight. A "
            "member can read their own contributions, payments, fees and payouts, and the "
            "sum of those is their own balance. A member cannot read the ledger, so they "
            "cannot see the platform's total float, another Ajo's entries, or a posting "
            "that no user-facing table projects. The member-facing projection is assembled "
            "by the API from the tables above; the ledger itself is an internal record, and "
            "the internal record is a staff tool."
        ),
    },

    {
        "t": "p",
        "text": (
            "Staff access is a role, not a flag on a row. `app.has_platform_role` reads "
            "`role_assignments` under a pinned `search_path`, and `app.is_platform_staff` "
            "returns true for the support and risk roles and deliberately not for "
            "`super_admin`. A super-admin is an operator with the ability to deploy and "
            "manage staff, and is not thereby entitled to read a member's payment history; "
            "keeping those two apart means the highest-privilege account in the system is "
            "not also the account with the most personal data in it. Reversing that later is "
            "a one-line change, and it will be a deliberate one."
        ),
    },

    {
        "t": "p",
        "text": (
            "The suite that verifies all of this runs as `SET ROLE ajo_app` with the request "
            "GUCs set, so it tests the policies rather than the table owner. Eighteen checks "
            "cover the matrix above. The one that raises rather than returning zero rows is "
            "the insertion attempt by a non-organizer member: a `WITH CHECK` violation, which "
            "is the loud failure we want. The other denials are silent by design, because a "
            "`SELECT` that returns nothing is indistinguishable from a filter that was too "
            "narrow, and the test asserts the row count instead of the absence of an error."
        ),
    },

    {
        "t": "callout",
        "kind": "WARNING",
        "title": "`SECURITY DEFINER` functions are the sharpest tool in this schema",
        "text": (
            "Six functions in `app` run as their owner and can therefore read tables their "
            "caller cannot. Each one pins `search_path` to `public, app`, and that is not "
            "decoration: without it, a caller who could create an object in an earlier "
            "schema could shadow `ajo_members` and read anything. Any new "
            "`SECURITY DEFINER` function in this schema must pin its search path in the same "
            "statement, and any new one that reads a table needs a policy test, because the "
            "defect mode is silent."
        ),
    },

    {"t": "h2", "text": "9.7 Idempotency, transactions, and exactly-once"},

    {
        "t": "p",
        "text": (
            "Three problems get one mechanism each, and none of them is a distributed "
            "transaction. A payment webhook that arrives twice, a client that retries a "
            "charge because the response was slow, and a worker that crashes between doing "
            "the work and recording that it did the work. The schema answers all three with a "
            "unique key and an insert that happens before the effect."
        ),
    },

    {
        "t": "p",
        "text": (
            "`webhook_events` is written first, in its own transaction, keyed on the "
            "provider's own event id. If that insert raises a unique violation, the event has "
            "been seen and the handler returns success without touching a payment. This is "
            "the standard way to receive webhooks safely, and the reason it works is that the "
            "deduplication record is durable before any state derived from the event is "
            "written, so the two can never disagree about whether the work was done."
        ),
    },

    {
        "t": "p",
        "text": (
            "`idempotency_keys` does the same for our own API. The key is scoped "
            "(`user_id` plus a scope string) and unique within the scope, and the row stores "
            "a hash of the request body beside the response. A replay with the same key and a "
            "different body is a client bug and is rejected; a replay with the same key and "
            "the same body returns the stored response, including its original status code. "
            "Storing the hash is what makes the key safe to accept rather than a way for a "
            "client to read another endpoint's response by guessing a key."
        ),
    },

    {
        "t": "p",
        "text": (
            "`outbox_events` is the third, and it is the one that is easy to get wrong. The "
            "pattern is: a state change and the intent to send a notification are written in "
            "the same transaction, and a separate worker reads the outbox and delivers. The "
            "alternative, sending the notification inside the transaction, has two failure "
            "modes that are both unacceptable: a rollback after a successful send produces a "
            "notification about something that did not happen, and a crash before the send "
            "produces state that changed with nobody told. The outbox trades an exactly-once "
            "send for an at-least-once send, which is the correct trade, because a duplicate "
            "SMS is an annoyance and a silent missing payment notice is a support ticket and "
            "a regulatory problem."
        ),
    },

    {
        "t": "p",
        "text": (
            "Delivery is therefore idempotent at the far end, keyed on the outbox row's id, "
            "and `outbox_events` is append-only with an index on `processed_at IS NULL` so "
            "the queue is an index range rather than a filter over finished work. The table "
            "deliberately has no foreign key, as noted in 9.3, so a future producer can enqueue "
            "work about an aggregate that does not exist yet without the queue being coupled "
            "to today's schema."
        ),
    },

    {"t": "h2", "text": "9.8 Locking, position occupancy, and concurrency"},

    {
        "t": "p",
        "text": (
            "Four operations in this system can plausibly race, and each has a named answer. "
            "None of the answers is an advisory lock, and none reads a balance, modifies it, "
            "and writes it back."
        ),
    },

    {
        "t": "table",
        "head": ["Race", "What can go wrong", "The mechanism"],
        "rows": [
            [
                "Two members claim the same position",
                "Two members in one position; the turn skips one of them",
                "The partial unique index in 9.3.2. One insert commits, the other gets a unique violation. No lock, because the index is the arbiter.",
            ],
            [
                "Two organizers activate the same Ajo",
                "Two activation events, two sets of rounds, two sets of notifications",
                "`SELECT ... FOR UPDATE` on the `ajos` row, then a status CHECK that only permits `enrollment_open` to `active`.",
            ],
            [
                "The same payment settled twice",
                "One charge, two contribution state changes, two payouts possible",
                "The unique key on `(transaction_id, account_kind, side)`, the deferred balance trigger, and the payout's unique index on `(round_id, position_id)`.",
            ],
            [
                "A member defaults while their payment is landing",
                "A defaulted contribution that is about to be paid, or a payment against a defaulted obligation",
                "The contribution row is locked `FOR UPDATE` before the default transition, so the payment either sees the settled state and stops, or waits and then sees the default and stops.",
            ],
        ],
        "widths": [1.6, 2.1, 2.8],
    },

    {
        "t": "p",
        "text": (
            "The row lock is the one place where a transaction is deliberately long-lived, "
            "and the rule is that it is acquired last, after all the reads that decide what to "
            "do. Locking early is how a request that has decided to return early ends up "
            "holding a row for the length of an external call. The defaulting path in 9.8 is "
            "the tightest example: read the contribution, decide it is overdue, take the lock, "
            "re-read the status inside the lock, and only then transition it. The re-read is "
            "not paranoia; it is the only thing that makes the earlier decision safe to have "
            "made before the lock."
        ),
    },

    {"t": "h2", "text": "9.9 Migrations, and the shape of a zero-downtime change"},

    {
        "t": "p",
        "text": (
            "Four files, applied in order, and the order is the design. `00` creates the "
            "extensions, the enums, the `app` schema, the helper functions and the reference "
            "tables. `01` creates the forty tables, then the indexes, then the comments, and "
            "only then the foreign keys that had to be deferred. `02` installs the business-rule "
            "functions and the triggers that use them. `03` enables RLS and grants the roles. "
            "Each file is independently re-runnable on an empty database and the suite is run "
            "against all four in sequence, every time."
        ),
    },

    {
        "t": "p",
        "text": (
            "Splitting the foreign keys out of `01` into a later pass is not style. "
            "`contributions` references `rounds`, `payments` and `fees` in a cycle, and a "
            "single-pass `CREATE TABLE` cannot express a cycle, so the keys are added "
            "separately once every table exists. The alternative, nullable columns plus a "
            "later `SET NOT NULL`, ends with the same constraints in the same place and a "
            "window in between where the columns are nullable and a bug is cheaper to write."
        ),
    },

    {
        "t": "p",
        "text": (
            "Three rules for changing a schema that already has rows in it, all of them "
            "learned from the specific ways this schema could be broken."
        ),
    },

    {
        "t": "bullets",
        "items": [
            "**A new constraint goes in as `NOT VALID`, then gets validated separately.** "
            "`ALTER TABLE ... ADD CONSTRAINT ... NOT VALID` takes a brief lock, enforces the "
            "rule for new writes immediately, and validates the existing rows in the "
            "background. Adding a CHECK to a live `contributions` table without `NOT VALID` "
            "scans the table under an exclusive lock, and a 200,000-row table is a visible "
            "outage.",
            "**A new enum value is a migration, not a deploy.** `ALTER TYPE ... ADD VALUE` "
            "cannot run inside a transaction on the versions this targets, so the migration "
            "runs it outside one and the application that reads the new value deploys "
            "afterwards. The reverse order is the outage: code that writes a value the "
            "database does not have yet.",
            "**A renamed column is two migrations, never one.** Add the new column, backfill, "
            "dual-write, move reads, drop the old. The single-step rename that works "
            "perfectly on an empty database and fails on a live one is the standard way a "
            "deployable migration becomes a rollback.",
        ],
    },

    {
        "t": "p",
        "text": (
            "Dropping a column is two migrations for the same reason, with a `NOT NULL` "
            "default in between so the old code keeps working while the new column is "
            "populated. Nothing in this schema is dropped without that sequence, which "
            "includes the columns that were dropped during development: the `released_at` "
            "column on `ajo_members` and the `amount_kobo` name on `fees` both exist only in "
            "earlier drafts and neither reached a database anybody else had touched."
        ),
    },

    {"t": "h2", "text": "9.10 Backups, retention, and restore"},

    {
        "t": "p",
        "text": (
            "Three kinds of data with three different loss tolerances, and one rule: the "
            "ledger is the one that cannot be reconstructed, because it is the only record of "
            "what happened to money that no other system holds."
        ),
    },

    {
        "t": "table",
        "head": ["Data", "If it is lost", "Recovery"],
        "rows": [
            ["`ledger_transactions`, `ledger_postings`", "Unrecoverable. Money moved and the fact of it is gone.", "Point-in-time recovery. This is the only table that justifies WAL archiving on its own."],
            ["`payments`, `fees`, `payouts`", "Provider statements are the fallback, at provider reconciliation granularity rather than transaction granularity.", "Provider statement plus the reconciliation run that compared them."],
            ["`contributions`, `rounds`, `ajo_members`", "Every obligation and its state is lost, including who defaulted and when.", "PITR."],
            ["`notifications`, `device_tokens`", "Members are not told. Money is unaffected.", "Re-send. Deduplication keys make the re-send safe."],
            ["`audit_logs`", "The ability to answer \"who changed this\" is gone, which is a different kind of loss from data.", "PITR, and archive to cold storage before the table is pruned."],
            ["`idempotency_keys`, `webhook_events`", "In-flight retries become ambiguous and a client may be charged twice.", "PITR, and never prune a key younger than the longest client retry window."],
        ],
        "widths": [1.7, 2.4, 2.4],
    },

    {
        "t": "p",
        "text": (
            "Retention periods are a legal question and this section does not invent them. "
            "What it fixes is the mechanism: pruning is a batched `DELETE` with a `LIMIT` and "
            "an index on the timestamp being pruned, run in a loop that commits between "
            "batches, so a retention job cannot hold a lock long enough to matter and can be "
            "stopped and resumed at a batch boundary. A single unbounded `DELETE` over "
            "`audit_logs` is how a routine cleanup becomes an outage."
        ),
    },

    {
        "t": "callout",
        "kind": "WARNING",
        "title": "Retention periods and the deletion of member documents need counsel",
        "text": (
            "The pruning mechanism above is settled; the numbers are not. How long payment "
            "and identity records must be kept, whether a member's uploaded document is "
            "deleted or retained under legal hold when a data-subject request arrives, and "
            "what must be disclosed to a member about either, are questions for qualified "
            "Nigerian counsel and for our payment provider's agreement terms. Until those are "
            "answered, the batch size is configurable and the schedule is unset, which is a "
            "deliberate way of not asserting a compliance position in a schema file."
        ),
    },

    {
        "t": "p",
        "text": (
            "Restore is tested by restoring, not by having a backup. The drill is a PITR "
            "restore to a scratch database, followed by the two balance checks in 9.5: every "
            "ledger transaction sums to zero, and every round's stored pool equals the sum of "
            "its contributions. Those two queries are the acceptance test for a restore, "
            "because they are the only invariants that money can violate while remaining "
            "readable, and a restored database that fails them is worse than one that is "
            "obviously broken because somebody will use it."
        ),
    },

    {"t": "h2", "text": "9.11 Observability, the audit log, and the outbox"},

    {
        "t": "p",
        "text": (
            "Three mechanisms answer three different questions. A metric answers \"is this "
            "normal right now\". An audit row answers \"who did this, to which record, and "
            "what did it look like before\". An outbox row answers \"what work is owed\". They "
            "are not substitutes, and in particular an audit row is not an observability "
            "signal: the table is written on every insert, which is the opposite of the "
            "sampling a metric needs."
        ),
    },

    {
        "t": "table",
        "head": ["Question", "Instrument", "Retention"],
        "rows": [
            ["Is the webhook receiver keeping up?", "`outbox_events` where `processed_at IS NULL`, by age", "Live; pruned after a week."],
            ["How many attempts failed this week?", "`payments` by status, and the provider's own dashboard", "Metrics, not rows."],
            ["Who changed this Ajo's status?", "`audit_logs`, one row per change, with both states", "As long as the answer is worth having; see 9.10."],
            ["Which members defaulted this month?", "`contributions` where `defaulted_at` is not null", "As long as the contribution record."],
            ["Does the ledger still balance?", "The aggregate check in 9.5, run on a schedule", "Live."],
            ["What is the float?", "The sum of postings per `account_kind`, staff-only", "Live."],
        ],
        "widths": [1.9, 2.7, 1.9],
    },

    {
        "t": "p",
        "text": (
            "The outbox depth and the ledger balance check are the two alerts on this schema "
            "that page somebody. Everything else is a dashboard. A rising count of "
            "unprocessed outbox rows means notifications are not going out, which compounds "
            "silently: nothing fails, members simply stop being told. A ledger that does not "
            "balance cannot happen through the API, so a failure there means either a "
            "migration bypassed a trigger or somebody is writing with the owner role, and "
            "both are worth waking somebody for."
        ),
    },

    {
        "t": "p",
        "text": (
            "One thing deliberately not instrumented here is the count of defaulted members "
            "as a business metric. It is computable, and it is a good measure of the product, "
            "and it is also the number most likely to end up in a slide without the "
            "accompanying obligation, which is a different number with a different meaning. "
            "CANONICAL.md requires that a defaulted contribution be understood as a debt to "
            "the Ajo, and an unqualified count is how that gets lost."
        ),
    },

    {"t": "h2", "text": "9.12 Capacity and performance"},

    {
        "t": "p",
        "text": (
            "The member-facing read path is six queries: my profile, my Ajos, the Ajo's "
            "members, the current round, my contribution in it, and my notifications. All six "
            "are indexed and all six are single-digit row counts for any Ajo this product is "
            "likely to hold. The scale problem is not any one Ajo; it is the number of Ajos, "
            "and that lands on the tables with a `user_id` or `ajo_id` leading a composite "
            "index."
        ),
    },

    {
        "t": "table",
        "head": ["Growth", "First thing to break", "Why"],
        "rows": [
            ["Members per Ajo", "Nothing", "Capped at `position_count`, which is small by construction. An Ajo of 200 is not a product this schema has to survive."],
            ["Ajos per member", "Nothing until the hundreds", "One index range scan on `ajo_members (user_id)`."],
            ["Total contributions", "`notifications` and `audit_logs`", "Both grow with total activity rather than with active members, and both are append-heavy. This is the first table that needs partitioning."],
            ["Total payments", "`reconciliation_runs`", "Each run scans a date range of payments. Past a few million, it wants a materialised view or a summary table."],
            ["Ledger postings", "Balance queries", "The sum per `account_kind` is a full index scan. It wants a periodic rollup, kept correct by the same deferred trigger that guarantees balance."],
        ],
        "widths": [1.6, 1.9, 3.0],
    },

    {
        "t": "p",
        "text": (
            "The partitioning decision is deferred on purpose, and this section names the "
            "threshold rather than pretending to know it. `notifications` and `audit_logs` "
            "are the two tables that become expensive purely through time, they are both "
            "append-only, and both are queried by a recent time window, which is the ideal "
            "partitioning shape. When the time comes it is a `PARTITION BY RANGE "
            "(created_at)` with a monthly partition per month retained, and the pruning job "
            "from 9.10 drops a partition instead of deleting a row range, which is a metadata "
            "operation rather than a bulk one. Nothing else in the schema needs this."
        ),
    },

    {
        "t": "p",
        "text": (
            "Two performance claims worth making plainly, because they are the reason for "
            "some earlier decisions. UUIDv7 primary keys are insert-friendly where UUIDv4 is "
            "not, so the write path does not fragment the primary btree as the table grows. "
            "And because a member's balance is a projection of their own payments, fees and "
            "payouts rather than a stored running total, there is no counter to lose an "
            "update, no `SELECT FOR UPDATE` on a hot row to serialise every payment in the "
            "system, and no way for two concurrent payments to produce a wrong total. The "
            "balance is correct because it is computed from rows that are already correct."
        ),
    },

    {"t": "h2", "text": "9.13 Which tables are audited, and which are not"},

    {
        "t": "p",
        "text": (
            "Eighteen of the forty tables carry the audit trigger. The rule for choosing is "
            "whether a row describes something about a person, something about money, or "
            "something about who may do what. The rule for excluding is whether a row is "
            "reference data that a migration owns and a runtime user never writes. An audit "
            "trail is only useful if the interesting events are in it, and the cost of a noisy "
            "one is that nobody reads it."
        ),
    },

    {
        "t": "table",
        "head": ["Audited", "Why"],
        "rows": [
            ["`users`, `profiles`", "Identity. A support agent reading a member's record, and changing their phone number, are both events worth having."],
            ["`admins`, `role_assignments`", "Who may do what, and who granted it. The most sensitive table in the schema after the ledger."],
            ["`invitations`", "An invitation is an assertion that a person was admitted to an Ajo. Disputes turn on it."],
            ["`verification_checks`", "KYC outcomes. Never the BVN itself, but the result and its timestamp."],
            ["`documents`", "Provenance of an uploaded file, including a re-scan verdict."],
            ["`ajos`, `ajo_members`, `ajo_positions`", "The Ajo and its rotation. Position changes are the most disputed rows in the product."],
            ["`rounds`, `contributions`, `contribution_schedules`", "Obligations, payments owed, and the defaulting decision."],
            ["`payments`, `fees`, `payouts`", "Every movement of money, in either direction."],
            ["`ledger_transactions`", "Append-only, so the audit trigger records the insert and nothing else. It is present so the ledger is discoverable from `audit_logs` during an investigation."],
            ["`disputes`", "The state machine and its resolution. Adjudication history is the point of the table."],
            ["`risk_events`", "Someone flagged something, and what happened next."],
        ],
        "widths": [2.2, 4.3],
    },

    {
        "t": "table",
        "head": ["Not audited", "Why not"],
        "rows": [
            ["`ledger_postings`", "A posting cannot change and cannot be deleted while its transaction exists, so an audit row per posting is a duplicate of the posting. The transaction above it is audited."],
            ["`dispute_messages`", "A conversation, not a state change. The dispute's own status transitions are audited; the messages inside it are the content of the dispute."],
            ["`dispute_evidence`", "A join row. The document it points at is audited."],
            ["`audit_logs`", "Self-reference. The table is the record."],
            ["`roles`, `document_types`, `dispute_reasons`, `payment_channels`, `contribution_frequencies`, `verification_check_types`", "Reference data written only by migration, and the migration is itself version-controlled and reviewed."],
            ["`sessions`, `device_tokens`", "Ephemeral by purpose. A revoked session stops being interesting the moment it is revoked; the `revoked_at` column is the record."],
            ["`notifications`, `notification_preferences`", "A notification is a delivery, and the outbox row that produced it is the audited fact. A member changing a preference is a preference, and it is in their own account."],
            ["`idempotency_keys`, `webhook_events`, `outbox_events`", "Infrastructure bookkeeping. They are pruned on a schedule in 9.10, and an audit row that is pruned with them protects nobody."],
            ["`platform_settings`", "Configuration changed by migration, reviewed in the diff."],
            ["`reconciliation_runs`, `support_tickets`", "Operational records with their own lifecycle and their own readers, rather than facts about a person's money or access."],
        ],
        "widths": [2.2, 4.3],
    },

    {
        "t": "p",
        "text": (
            "The trigger records the before and after images as `jsonb` and computes a "
            "monetary delta when the row has one, so a report can sum the deltas to get net "
            "movement without replaying the JSON. The one behaviour worth calling out is that "
            "an `UPDATE` which changes nothing writes no row."
        ),
    },

    {
        "t": "code",
        "text": (
            "  -- An UPDATE that changed nothing is not an audit event. Recording it puts\n"
            "  -- rows in a table that investigators read, and the cost of a noisy audit\n"
            "  -- trail is that nobody reads it.\n"
            "  IF v_before = v_after THEN\n"
            "    RETURN NULL;\n"
            "  END IF;"
        ),
    },

    {
        "t": "callout",
        "kind": "DECISION",
        "title": "`dispute_messages` being unaudited is a choice with a cost",
        "text": (
            "A dispute message is the kind of row that is edited, or would be if the schema "
            "allowed it: it is `INSERT`-only at the application layer, and there is no "
            "`edited_at` column to suggest otherwise. If a future requirement is to prove "
            "what a member said and when, that is a schema change to this table and a policy "
            "decision about who reads it, and it should not be discovered during a dispute. It "
            "is listed here rather than in the audited table so the omission is visible."
        ),
    },

    {"t": "h2", "text": "9.14 Validation: how this schema was tested"},

    {
        "t": "p",
        "text": (
            "Twenty-three behavioural tests and twenty-two row-level assertions, written as "
            "SQL, run against a database created empty for the purpose. Every rule in this "
            "section that can be violated by a statement is violated by a test, and the test's "
            "own error message is quoted below. The counts are not a claim about coverage; "
            "they are what was run, and the honest statement is that a rule not in the list is "
            "a rule whose failure nobody has watched."
        ),
    },

    {
        "t": "p",
        "text": (
            "Each negative test expects a failure, and the suite fails if that failure does "
            "not arrive. A test that inserts an unbalanced transaction and passes because the "
            "insert succeeded is worse than no test, because it is a green mark on a rule "
            "nobody has checked; each test therefore asserts the specific constraint name, "
            "not merely that something went wrong."
        ),
    },

    {
        "t": "table",
        "head": ["Test", "Rule", "Refusal"],
        "rows": [
            ["T1–T3", "A full Ajo can be created, funded, and run end to end", "Passes, and is the baseline the other twenty are read against"],
            ["T4", "CR-15: a transaction with one posting", "`ledger transaction ... has 1 posting(s); an entry needs at least 2`"],
            ["T5", "CR-16: a transaction whose legs do not sum to zero", "`ledger transaction ... is out of balance by N kobo`"],
            ["T6", "CR-12: a fee that is not 2% of its payment", "`fees` deferred trigger rejects at commit"],
            ["T7", "CR-03: two live members in one position", "unique violation on `ajo_members_one_live_position`"],
            ["T8", "CR-18: a lifecycle transition not in the table", "`assert_lifecycle_transition` raises with the allowed set"],
            ["T9", "CR-11: a fee row against a payment that does not exist", "foreign key violation"],
            ["T10", "CR-05: a round whose pool disagrees with its contributions", "`rounds_pool_matches_contributions` raises at commit"],
            ["T11", "CR-07: two members released from one position", "The second claim violates the occupancy index; the first is released cleanly"],
            ["T12", "CR-19: a money-critical template with no SMS row", "`templates_critical_have_sms` raises"],
            ["T13", "CR-14: positions edited after activation", "`assert_positions_locked` raises"],
            ["T14", "CR-20: a reordered lifecycle transition", "`assert_lifecycle_transition` rejects the second step"],
            ["T15", "CR-13: a terminal Ajo moved out of its terminal state", "`assert_lifecycle_transition` raises; the timestamp CHECK holds"],
            ["T16", "CR-10: a member disputing their own contribution", "`disputes_not_self_dispute` raises, having first proved the row was really inserted"],
            ["T17", "CR-17: a payout settled before it was recognised", "`assert_ledger_sequence` raises"],
            ["T18", "CR-21: a reversal of a reversal", "`reversals are one level deep (CR-21)`, reached with mirrored postings so it is the reversal rule and not the balance rule that fires"],
            ["T19–T22", "CR-04, CR-08, CR-09, CR-16 as applied to defaults, claims, notifications and terminal writes", "Each named constraint raises"],
            ["T23", "CR-06: after a full run, every ledger transaction still balances", "Passes; 4 transactions, every posting accounted for"],
        ],
        "widths": [0.8, 2.2, 3.5],
    },

    {
        "t": "p",
        "text": (
            "T16 and T18 are worth a note, because both were passing for the wrong reason when "
            "they were first written. T16 set a duplicate reason code, so the insert failed on "
            "the reason constraint and the self-dispute rule was never reached; the fix was a "
            "distinct reason. T18 inserted a reversal with a single posting, so it tripped the "
            "two-posting rule and proved nothing about reversal depth; the fix was mirrored "
            "postings with the correct `ledger_side`, which is what made the test reach CR-21. "
            "A green test and a tested rule are different things, and the difference is almost "
            "always an earlier constraint firing first."
        ),
    },

    {
        "t": "table",
        "head": ["RLS test", "Assertion"],
        "rows": [
            ["R1", "A member sees own profile, memberships, joined Ajo, rounds and positions"],
            ["R2", "A member sees a co-member's profile and no other member's"],
            ["R3", "An exited member still sees own rows, and the organizer's own rows are visible to the organizer"],
            ["R4", "A member sees zero ledger rows"],
            ["R5", "A member cannot see a co-member's defaulted contribution, and the organizer's default is visible to the organizer"],
            ["R5b", "The member's own defaulted contribution is visible to that member"],
            ["R5c", "A co-member's paid contribution is visible, and their defaulted one is not"],
            ["R5d", "The affected member, the organizer and staff each see the defaulted row; no other live member does"],
            ["R6", "A member's own payment and fee are visible; another member's are not"],
            ["R7", "Member-visible money adds up: 100,000 base, 102,000 charged, 2,000 fee"],
            ["R8", "A non-organizer member cannot insert a contribution: `WITH CHECK` violation, the one expected error in the suite"],
            ["R9", "An anonymous request sees zero reference rows"],
            ["R10", "Staff sees the ledger: 4 transactions, all balanced"],
            ["R11", "A non-staff role sees zero `audit_logs` rows"],
            ["R12", "A non-staff role sees zero `risk_events` rows"],
            ["R13", "An exited member's payment is still visible to that member"],
            ["R14", "A dispute is visible to a party and invisible to an uninvolved member"],
            ["R15", "Reference data is readable by a signed-in member"],
            ["R16", "`platform_settings` is readable by a member and not writable"],
            ["R17", "A member cannot see another member's `idempotency_keys`"],
            ["R18", "A member cannot see `outbox_events` or `webhook_events`"],
        ],
        "widths": [0.8, 5.7],
    },

    {
        "t": "p",
        "text": (
            "The suite is run as `SET ROLE ajo_app` with the request GUCs set, never as the "
            "table owner, because a policy test executed with owner privileges passes "
            "vacuously. That distinction is the whole reason this section exists as a table "
            "of refusals rather than a claim that the policies are correct."
        ),
    },

    {"t": "h3", "text": "9.14.1 The checklist"},

    {
        "t": "bullets",
        "items": [
            "All four migration files apply in order to an empty database with no error, from a clean cluster.",
            "The reference generator produces UUIDv7: version nibble 7, variant bits 10, and a timestamp that sorts with creation order.",
            "Every money test in 9.5 holds on real rows, including the 2% half-up boundary and the defaulted-contribution restatement.",
            "Every rule in the table above fails with its named constraint, asserted by name rather than by the presence of any error.",
            "The twenty-two RLS assertions run as `ajo_app`, not as the owner, and the one expected `WITH CHECK` violation is the loud one.",
            "`app.policy_coverage` reports zero tables with RLS enabled and no policy, and the count of tables with more than one policy is reviewed by hand.",
            "A PITR restore to a scratch database passes both balance checks in 9.5.",
            "A restore of an empty database and a restore of a seeded one produce the same schema, which is the check that the migrations are complete rather than the tables merely present.",
        ],
    },

    {
        "t": "callout",
        "kind": "WARNING",
        "title": "Three things this section does not establish",
        "text": (
            "Performance at scale is reasoned about in 9.12, not measured, and the first real "
            "load test will tell us something this file does not. Retention periods are "
            "undefined pending counsel, so the pruning schedule in 9.10 is unset by design. "
            "And the provider's behaviour under retry, reordering and duplicate delivery is "
            "assumed from its documentation rather than observed; the webhook receiver is "
            "written to survive all three because assuming otherwise would make it "
            "unrecoverable, but a staging environment that delivers a duplicate event is worth "
            "more than this paragraph."
        ),
    },

    {
        "t": "p",
        "text": (
            "Everything else in this section was executed. Where a statement here is a design "
            "rationale it is because the alternative was rejected for a reason, and where it "
            "is a number it came out of the database rather than out of an estimate. Section 8 "
            "draws the shape; this section is why the shape is safe to run."
        ),
    },
]
