"""Section 11 — API Specification."""

def _ep(method, path, purpose, auth, authz, body, params, resp, errors, rules):
    return {
        "t": "h3", "text": f"{method} {path}",
    }, [
        {"t": "kv", "pairs": [
            ("Purpose", purpose),
            ("Authentication", auth),
            ("Authorization", authz),
            ("Request body", body),
            ("Path parameters", params),
            ("Query parameters", "None unless stated. List endpoints accept `cursor` and `limit` (default 25, max 100)."),
            ("Success response", resp),
            ("Error responses", errors),
            ("Validation rules", rules),
        ]},
    ]

BLOCKS = [
    {"t": "h1", "text": "11. API Specification"},

    {"t": "lead", "text": "A versioned REST API over HTTPS. The contract is defined "
     "once in `packages/contracts` as Zod schemas and generated into OpenAPI, so the "
     "mobile app, the web app and the documentation cannot drift apart."},

    {"t": "h2", "text": "11.1 Conventions"},

    {"t": "h3", "text": "11.1.1 Base and versioning"},
    {"t": "bullets", "items": [
        "Base path: `/api/v1`. The version is in the path, not a header, so a cached response can never be served to the wrong client version.",
        "Breaking changes require `/api/v2`. Additive changes (new optional field, new endpoint, new enum value that clients can ignore) ship in v1.",
        "An enum value the client does not recognise must degrade gracefully, not crash. This matters because the provider and the regulatory position can both change.",
        "v1 is deprecated with a minimum 6-month notice and a sunset header before removal.",
    ]},

    {"t": "h3", "text": "11.1.2 Authentication"},
    {"t": "bullets", "items": [
        "Access token: short-lived JWT, 15 minutes, sent as `Authorization: Bearer <token>`.",
        "Refresh token: opaque, 30 days, rotation on every use, stored server-side with a device fingerprint. Reuse of a rotated token revokes the whole family — this is the standard theft-detection control.",
        "Refresh tokens are held in an httpOnly, Secure, SameSite=Strict cookie. Access tokens are held in memory only, never localStorage, to limit the blast radius of XSS.",
        "Every request carries `X-Request-Id` (client-generated UUID) which is echoed in the response and stamped on every log line for that request.",
    ]},

    {"t": "h3", "text": "11.1.3 Idempotency"},
    {"t": "callout", "kind": "WARNING", "title": "Mandatory on every money-moving POST.",
     "text": "`POST /contributions/:id/pay`, `POST /payments`, `POST /payouts/:id/release` "
     "and every admin money action require an `Idempotency-Key` header (UUID v4). The key "
     "is stored with a hash of the request body. A repeat with the same key returns the "
     "original response with `200` and an `Idempotent-Replay: true` header. A repeat with "
     "the same key but a different body returns `409`. A request without a key returns "
     "`400`. A timeout followed by an impatient retry is the normal case this exists for."},

    {"t": "h3", "text": "11.1.4 Pagination, filtering, sorting"},
    {"t": "table", "head": ["Concern", "Convention"], "widths": [1.2, 5.3], "size": 8.4, "rows": [
        ["Pagination", "Opaque cursor: `?cursor=<token>&limit=25`. Never offset — offsets shift under concurrent writes and produce duplicates and skips in a financial list"],
        ["Response envelope", "`{ \"data\": [...], \"page\": { \"nextCursor\": \"...\", \"hasMore\": true } }`"],
        ["Filtering", "Explicit allow-listed query parameters only, e.g. `?status=ACTIVE&from=2026-01-01`. Unknown parameters are rejected, not ignored — a silently-ignored filter means a member sees fewer records than they asked for"],
        ["Sorting", "One `sort` parameter from a fixed allow-list, e.g. `?sort=-created_at`. Always paired with a stable tiebreaker so pages never reorder"],
        ["Field selection", "`?fields=` allow-list, to keep mobile payloads small. Defaults return the documented shape"],
        ["Date/time", "RFC 3339 UTC (`2026-01-15T14:30:00Z`). Displayed in Africa/Lagos in the client"],
    ]},

    {"t": "h3", "text": "11.1.5 Rate limiting"},
    {"t": "table", "head": ["Scope", "Limit", "Window", "On breach"], "widths": [1.9, 1.1, 1.1, 2.4], "size": 8.4, "rows": [
        ["Login, OTP, password reset", "5", "per 15 min per identifier", "429 + generic message; never reveal whether the account exists"],
        ["Registration", "3", "per hour per device + IP", "429"],
        ["Payment initiation", "10", "per hour per member", "429 — this also limits fraud blast radius"],
        ["General API", "300", "per 15 min per member", "429"],
        ["Webhooks", "600", "per minute per provider IP", "429; provider retries"],
        ["Read-heavy listing", "600", "per minute", "429"],
    ]},
    {"t": "p", "text": "Responses include `X-RateLimit-Limit`, `X-RateLimit-Remaining`, "
     "`X-RateLimit-Reset` and `Retry-After`. Rate limits are per member and per identifier, "
     "never per IP alone — a shared NAT in Lagos would otherwise lock out an entire office."},

    {"t": "h3", "text": "11.1.6 Error format"},
    {"t": "code", "size": 8.2, "text": """
{
  "error": {
    "type": "https://ajo.ng/errors/insufficient-funds",
    "title": "Insufficient funds",
    "status": 402,
    "code": "PAYMENT_INSUFFICIENT_FUNDS",
    "detail": "Your bank declined the payment of NGN 1,020.00.",
    "instance": "/api/v1/contributions/cnt_9f2a/pay",
    "requestId": "req_01HQ8Z4K2M9X",
    "timestamp": "2026-01-15T14:30:00Z",
    "fieldErrors": [
      { "field": "amountKobo", "code": "OUT_OF_RANGE",
        "message": "Must be greater than 0" }
    ]
  }
}
"""},
    {"t": "p", "text": "The shape is modelled on RFC 7807 problem details with an added "
     "`code` for programmatic handling and `requestId` for support. `fieldErrors` appears "
     "only on `422` validation failures. **Never leak internal detail** — a database error "
     "returns a generic `500` with the `requestId`; the detail goes to the log, not to the member."},
    {"t": "table", "head": ["Status", "Meaning", "When used"], "widths": [0.6, 1.9, 4.0], "size": 8.4, "rows": [
        ["400", "Bad request", "Missing Idempotency-Key, malformed parameter"],
        ["401", "Unauthenticated", "Absent, expired or invalid token"],
        ["403", "Forbidden", "Authenticated but not permitted — not a member of this Ajo, wrong role"],
        ["404", "Not found", "Also returned for resources the caller may not see, so existence is not leaked"],
        ["409", "Conflict", "Idempotency key reused with a different body; duplicate email; position already taken"],
        ["422", "Unprocessable", "Field validation failed; a business rule rejected a well-formed request"],
        ["402", "Payment required", "Insufficient funds, declined, payment required before the next step"],
        ["429", "Rate limited", "Retry-After supplied"],
        ["500", "Server error", "Unexpected. Always carries a requestId"],
        ["503", "Unavailable", "Provider or database unavailable. Retryable — members see a clear 'try again shortly'"],
    ]},

    {"t": "h2", "text": "11.2 Authentication endpoints"},
    *_ep("POST", "/api/v1/auth/register", "Create an account and send email verification.",
         "None", "Public. Rate limited to 3/hour per device+IP.",
         "`{ email, password, fullName, phoneNumber, acceptedTerms: true, acceptedPrivacy: true }`",
         "None",
         "`201` `{ user: { id, email, fullName, phoneNumber, emailVerified: false, status: 'PENDING_VERIFICATION' }, nextStep: 'VERIFY_EMAIL' }`",
         "`409` email already registered · `422` weak password / invalid phone / terms not accepted",
         "Password ≥ 12 chars, at least one of each class; checked against a breached-password list. Phone in E.164, Nigerian numbers normalised to +234. `acceptedTerms` must be explicitly true — it is written to `audit_logs` as consent evidence."),
    *_ep("POST", "/api/v1/auth/login", "Exchange credentials for an access token and set a refresh cookie.",
         "None", "Public. 5 attempts/15 min per identifier.",
         "`{ email, password, deviceFingerprint }`",
         "None",
         "`200` `{ accessToken, expiresIn: 900, user: {...} }` + `Set-Cookie` refresh token (HttpOnly, Secure, SameSite=Strict). Optional TOTP challenge response.",
         "`401` invalid credentials (generic message — never reveal which of email or password was wrong) · `403` account frozen or suspended · `429` rate limited",
         "Timing-safe credential comparison. On success, all other sessions for that member may be revoked per policy. A new-device login triggers `security.login_new_device`."),
    *_ep("POST", "/api/v1/auth/refresh", "Rotate the refresh token and issue a new access token.",
         "Refresh cookie", "Member with a valid, unrevoked session.",
         "None", "None",
         "`200` `{ accessToken, expiresIn: 900 }` + rotated refresh cookie",
         "`401` invalid or expired · `401` reuse detected — the entire token family is revoked and the member is notified",
         "Single-use rotation. Reuse of an already-rotated token is treated as theft and forces re-authentication on all devices."),
    *_ep("POST", "/api/v1/auth/logout", "Revoke the current session.", "Refresh cookie or Bearer", "Authenticated member.", "None", "None",
         "`204`", "None", "Revokes the presented refresh token and its family."),
    *_ep("GET", "/api/v1/auth/sessions", "List the member's active devices.", "Bearer", "Member.", "None", "None",
         "`200` `{ sessions: [{ id, deviceName, platform, ipAddress, lastActiveAt, current }] }`", "None",
         "Enables a member to revoke a device they do not recognise."),
    *_ep("DELETE", "/api/v1/auth/sessions/:id", "Revoke one session or all others.", "Bearer", "Member, owning that session.",
         "None", "`id`", "`204`", "`404` not owned by caller", "A member can only revoke their own sessions."),
    *_ep("POST", "/api/v1/auth/verify-email", "Confirm an email address from the emailed token.", "None", "Public.",
         "`{ token }`", "None", "`200` `{ verified: true }`", "`400` invalid or expired token",
         "Token is single-use and expires in 24 hours. Verification is required before creating or joining an Ajo."),
    *_ep("POST", "/api/v1/auth/otp/request", "Send a one-time password by SMS or email.", "None", "Public. 5/15 min.",
         "`{ identifier, channel: 'SMS' | 'EMAIL', purpose }`", "None",
         "`202` `{ expiresIn: 300 }`", "`429` rate limited",
         "Always responds 202 regardless of whether the account exists, so the endpoint cannot be used to enumerate members. 6 digits, 5-minute expiry, max 3 attempts, single use."),
    *_ep("POST", "/api/v1/auth/otp/verify", "Verify an OTP.", "Bearer", "Authenticated member.", "`{ code, purpose }`", "None",
         "`200` `{ verified: true }`", "`400` invalid · `429` attempts exhausted",
         "After 3 failed attempts a new OTP must be requested and a cooldown applies."),
    *_ep("POST", "/api/v1/auth/password/forgot", "Start a password reset.", "None", "Public. 5/15 min.",
         "`{ email }`", "None", "`202` `{ message: 'If the account exists, a reset link has been sent.' }`",
         "`429` rate limited",
         "Response is identical whether or not the account exists. The emailed link is single-use, expires in 1 hour, and invalidates all existing sessions on use."),
    *_ep("POST", "/api/v1/auth/password/reset", "Complete a password reset.", "None", "Public, with a valid reset token.",
         "`{ token, newPassword }`", "None", "`200` `{ reset: true }`", "`400` invalid/expired · `422` weak password",
         "All sessions revoked. A `security.password_changed` alert is sent to every registered address/device."),

    {"t": "h2", "text": "11.3 Profile and identity"},
    *_ep("GET", "/api/v1/profile", "Read the caller's profile.", "Bearer", "Member.", "None", "None",
         "`200` `{ profile: { fullName, phoneNumber, email, bvnVerified, avatarUrl, kycStatus, joinedAjoCount, defaultsCount } }`", "None", "Returns only the caller's own profile."),
    *_ep("PATCH", "/api/v1/profile", "Update the caller's profile.", "Bearer", "Member. Cannot change own role or status.",
         "`{ fullName?, phoneNumber?, avatarUrl? }`", "None", "`200` `{ profile }`",
         "`422` invalid phone · `409` phone already in use",
         "Changing a phone number requires OTP verification of the new number first, and triggers a security notification."),
    *_ep("GET", "/api/v1/profile/financial-summary", "Aggregate position across all Ajos.", "Bearer", "Member.", "None", "None",
         "`200` `{ totalContributedKobo, totalReceivedKobo, totalFeesPaidKobo, activeAjoCount, nextDue: {...}, defaultsCount }`", "None",
         "All figures in kobo, summed from the ledger. Never computed from cached denormalised totals without ledger reconciliation."),
    *_ep("POST", "/api/v1/verification/identity", "Submit identity documents for KYC.", "Bearer", "Member, unverified.",
         "`{ documentType: 'NIN' | 'PASSPORT' | 'DRIVERS_LICENSE' | 'BVN', documentNumber, dateOfBirth, documentIds: [uuid] }`", "None",
         "`202` `{ verificationId, status: 'PENDING' }`", "`422` invalid document · `409` already verified or already under review",
         "Creates a `verification_checks` row and a `risk_events` entry. An MVP gate requiring BVN should be treated as a **verified requirement to confirm with Providus and counsel**, not an assumption."),
    *_ep("GET", "/api/v1/verification/:id", "Poll verification status.", "Bearer", "Owning member only.",
         "None", "`id`", "`200` `{ status: 'PENDING'|'APPROVED'|'REJECTED', reason?, submittedAt, decidedAt? }`", "`404` not found",
         "A rejection reason must be actionable, e.g. 'The document image is unreadable', never 'Verification failed'."),

    {"t": "h2", "text": "11.4 Ajo endpoints"},
    *_ep("POST", "/api/v1/ajos", "Create an Ajo in DRAFT.", "Bearer", "Member, email-verified.",
         "`{ name, contributionKobo, currency: 'NGN', frequency: 'WEEKLY'|'BIWEEKLY'|'MONTHLY', collectionDay: 'FRIDAY', durationRounds, maxMembers, description?, startDate }`", "None",
         "`201` `{ ajo: {...}, positions: [...] }`", "`422` invalid configuration · `403` not verified · `409` duplicate active Ajo",
         "Contribution between NGN 1,000.00 and NGN 5,000,000.00, and duration × maxMembers subject to the platform cap (open decision D-08). The creator is assigned a position and becomes `ajo_organizer` + `ajo_member`. Membership is zero at creation — positions are claimed by invitees."),
    *_ep("GET", "/api/v1/ajos", "List Ajos the caller belongs to.", "Bearer", "Member.",
         "None", "None",
         "`200` `{ data: [{ id, name, status, yourPosition, yourRole, contributionKobo, nextDueAt, currentRound, totalRounds, membersCount, positionsFilled }], page: {...} }`", "None",
         "Scoped by membership. RLS enforces that a member can only ever see their own Ajos."),
    *_ep("GET", "/api/v1/ajos/:id", "Full Ajo detail.", "Bearer", "Member of that Ajo.",
         "None", "`id`", "`200` `{ ajo, positions, members, schedule, yourCommitment, rules }`", "`403` not a member · `404` not found",
         "Includes the Ajo's rules document and, for the organizer, a `rulesAcknowledged` flag per member."),
    *_ep("PATCH", "/api/v1/ajos/:id", "Edit Ajo configuration.", "Bearer", "ajo_organizer, and only while DRAFT or ENROLLMENT.",
         "`{ name?, description?, contributionKobo?, collectionDay?, startDate? }`", "`id`",
         "`200` `{ ajo }`", "`409` not editable in current status (locked on activation) · `422` invalid value",
         "**Any field that affects money or a member's obligation is immutable once the Ajo is ACTIVE.** This is where the position lock and the contribution lock are enforced."),
    *_ep("POST", "/api/v1/ajos/:id/activate", "Close enrollment and activate.", "Bearer", "ajo_organizer.",
         "`{ confirm: true }`", "`id`", "`200` `{ ajo, positionsLocked: true, schedule: [...] }`",
         "`409` enrollment not full · `409` already active · `422` schedule could not be generated",
         "The schedule is generated and all positions lock in a single serialisable transaction. Two concurrent activation attempts must produce exactly one success."),
    *_ep("POST", "/api/v1/ajos/:id/cancel", "Cancel the Ajo and refund contributions.", "Bearer", "ajo_organizer or super_admin.",
         "`{ reason }`", "`id`", "`202` `{ status: 'CANCELLING', refundJobId }`",
         "`409` already terminal · `422` reason required",
         "Asynchronous: every unsettled contribution is refunded and every settled one queued for refund. Triggers `refunds_payable` entries. **Decision D-05 is open: whether the 2% fee is refundable on cancellation.** Until decided, the conservative assumption is that the fee is not refunded, and this must be disclosed in the cancellation flow."),
    *_ep("POST", "/api/v1/ajos/:id/freeze", "Freeze the Ajo and halt collections and payouts.", "Bearer", "risk_officer, support (with reason) or super_admin.",
         "`{ reason }`", "`id`", "`200` `{ ajo, frozenReason }`", "`422` reason required",
         "A frozen Ajo accepts no contributions and releases no payouts. Used for fraud investigation, provider outage or legal instruction."),
    *_ep("POST", "/api/v1/ajos/:id/unfreeze", "Resume a frozen Ajo.", "Bearer", "risk_officer or super_admin.", "`{ reason }`", "`id`",
         "`200` `{ ajo }`", "`409` not frozen", "Requires a recorded reason and writes a `risk_events` row."),
    *_ep("GET", "/api/v1/ajos/:id/summary", "Aggregate Ajo state for the dashboard.", "Bearer", "Member of that Ajo.", "None", "`id`",
         "`200` `{ status, round, collectedThisRoundKobo, expectedThisRoundKobo, membersPaid, membersTotal, yourOutstandingKobo, nextPayoutAt, nextPayoutRecipient }`",
         "`403` not a member", "Reads the ledger, not a cached counter. Never cached (section 10.10)."),
    *_ep("GET", "/api/v1/ajos/:id/positions", "List payout positions.", "Bearer", "Member of that Ajo.", "None", "`id`",
         "`200` `{ positions: [{ positionNumber, memberId, memberName, status: 'OPEN'|'CLAIMED'|'LOCKED', roundNumber, claimedAt? }] }`", "None",
         "Before activation a position is OPEN or CLAIMED. After activation every position is LOCKED and immutable."),
    *_ep("POST", "/api/v1/ajos/:id/positions/claim", "Claim a payout position.", "Bearer", "Member of that Ajo, in ENROLLMENT.",
         "`{ positionNumber }`", "`id`", "`200` `{ position }`", "`409` position already claimed · `409` member already holds a position · `403` not in ENROLLMENT",
         "Executed under `SELECT ... FOR UPDATE` or SERIALIZABLE isolation. **Two members claiming the last position must result in exactly one success.** No member may hold more than one position, and may not choose their own round."),
    *_ep("POST", "/api/v1/ajos/:id/positions/lock", "Lock all positions on activation.", "Bearer", "ajo_organizer (or automatic on activate).", "None", "`id`",
         "`200` `{ positionsLocked: true }`", "`409` not all positions filled", "Idempotent."),

    {"t": "h2", "text": "11.5 Membership and invitations"},
    *_ep("GET", "/api/v1/ajos/:id/members", "List members.", "Bearer", "Member of that Ajo.", "None", "`id`",
         "`200` `{ members: [{ memberId, name, role, position, contributionStatus, outstandingKobo, defaultCount, status, joinedAt }] }`", "None",
         "**Defaulting status is never displayed to other members** — no public shaming (business rule BR-019). Only the organizer sees default status, and only as 'needs attention'."),
    *_ep("PATCH", "/api/v1/ajos/:id/members/:memberId", "Update a member's role or state.", "Bearer", "ajo_organizer (pre-activation) or risk_officer.",
         "`{ role?, status?, reason? }`", "`id`, `memberId`", "`200` `{ member }`", "`409` not permitted after activation",
         "Cannot change a member's position or contribution amount — those are locked."),
    *_ep("DELETE", "/api/v1/ajos/:id/members/:memberId", "Remove a member.", "Bearer", "ajo_organizer, pre-activation only.",
         "`{ reason }`", "`id`, `memberId`", "`204`", "`409` cannot remove after activation · `422` reason required",
         "After activation the only exit is the formal replacement/transfer process. Removing a member must cascade-close any unsettled contribution obligations."),
    *_ep("POST", "/api/v1/ajos/:id/members/:memberId/replace", "Start a replacement for a defaulting member.", "Bearer", "ajo_organizer.",
         "`{ replacementMemberId?, reason, acknowledgeDebt: boolean }`", "`id`, `memberId`", "`202` `{ replacement: {...} }`",
         "`422` reason required · `409` no open default · `409` replacement not eligible",
         "The defaulting member's outstanding debt is **not** automatically transferred to the replacement. AJO.ng does not charge other members extra (BR-018). The debt remains on the defaulting member and the Ajo enters a defined recovery state until resolved."),
    *_ep("POST", "/api/v1/invitations", "Invite members to an Ajo.", "Bearer", "ajo_organizer.",
         "`{ ajoId, contacts: [{ name?, email?, phoneNumber }], personalMessage?, expiresInHours? }`", "None",
         "`202` `{ invitations: [{ id, token, channel, status, expiresAt }], deliverySummary }`", "`422` invalid contact · `409` Ajo full or not in ENROLLMENT",
         "Invites are **not** a disclosure of the Ajo to a stranger: a phone-number invite reveals only the organizer's name and the Ajo name. Channels: SMS, email, in-app. Default expiry 72 hours (open decision)."),
    *_ep("GET", "/api/v1/invitations", "List invitations the caller sent or received.", "Bearer", "Member.", "None", "None",
         "`200` `{ invitations: [...] }`", "None", "Scope depends on role: organizer sees sent, invitee sees received."),
    *_ep("GET", "/api/v1/invitations/:token", "Preview an invitation before accepting.", "None (or Bearer if already signed in)",
         "Token holder. Reveals minimal info.", "None", "`token`",
         "`200` `{ ajo: { name, contributionKobo, frequency, collectionDay, durationRounds, membersCount, maxMembers, endsAt }, organizer: { name }, positionOptions, feeDisclosure, rules }`",
         "`410` expired or revoked · `404` invalid",
         "**The 2% fee must be disclosed here, in plain terms, before the invitee accepts.** A person cannot consent to a fee they were not shown."),
    *_ep("POST", "/api/v1/invitations/:token/accept", "Accept an invitation and join.", "Bearer", "Authenticated invitee.",
         "`{ positionNumber, rulesAccepted: true }`", "`token`", "`200` `{ membership, contributionObligation }`",
         "`410` expired · `409` Ajo full or activation reached · `422` rules not accepted · `403` not verified",
         "Position claim and membership creation occur in one transaction. Rules acceptance is recorded as consent evidence in `audit_logs`. Reaching the last position triggers enrollment evaluation."),
    *_ep("POST", "/api/v1/invitations/:token/decline", "Decline an invitation.", "Bearer or None", "Token holder.",
         "`{ reason? }`", "`token`", "`200` `{ declined: true }`", "None", "Idempotent."),
    *_ep("POST", "/api/v1/invitations/resend", "Resend an invitation.", "Bearer", "ajo_organizer.", "`{ invitationId }`", "None",
         "`202` `{ resent: true }`", "`429` resend rate limited (max 3 per invitation per day)", "Prevents an organizer from using AJO.ng to spam a phone number."),

    {"t": "h2", "text": "11.6 Contributions and payments"},
    *_ep("GET", "/api/v1/ajos/:id/contributions", "Contribution history for an Ajo.", "Bearer", "Member of that Ajo.", "None", "`id`",
         "`200` `{ data: [{ id, roundNumber, dueAt, status, amountKobo, feeKobo, totalKobo, paidAt?, paymentId? }], page }`",
         "None", "Scoped to the calling member unless the caller is the organizer, who sees the aggregate but not other members' bank details."),
    *_ep("GET", "/api/v1/ajos/:id/schedule", "The full generated contribution schedule.", "Bearer", "Member of that Ajo.", "None", "`id`",
         "`200` `{ schedule: [{ roundNumber, dueAt, collectionDay, expectedKobo, collectedKobo, status, payoutRecipient }] }`", "None",
         "Generated once at activation and immutable thereafter."),
    *_ep("GET", "/api/v1/contributions/:id", "One contribution obligation.", "Bearer", "Owning member or Ajo organizer.",
         "None", "`id`", "`200` `{ contribution: {...} }`", "`404`", "Includes the exact amount due including the fee."),
    *_ep("POST", "/api/v1/contributions/:id/pay", "Pay a contribution. **Idempotency-Key required.**", "Bearer", "Owning member; contribution must be `PENDING` or `OVERDUE`.",
         "`{ bankAccountId, saveCard?: boolean }` — **never a client-supplied amount**", "`id`",
         "`202` `{ paymentId, status: 'PENDING', amountKobo, feeKobo, totalKobo, authorizationUrl }`",
         "`402` insufficient funds · `409` already paid or past grace · `422` no verified bank account · `429` rate limited",
         "**The amount is recomputed server-side from the database.** The client may display an amount; it may not assert one. The response echoes the exact split: contribution, 2% fee, total. The contribution is not marked paid until the provider confirms."),
    *_ep("POST", "/api/v1/contributions/:id/retry", "Retry a failed payment.", "Bearer", "Owning member, with a failed payment.",
         "None", "`id`", "`202` `{ paymentId, authorizationUrl }`", "`409` no retryable failure", "Creates a new payment; the previous failure is retained for audit."),
    *_ep("POST", "/api/v1/payments", "Create a payment against a contribution.", "Bearer", "Owning member. **Idempotency-Key required.**",
         "`{ contributionId, bankAccountId, amountKobo? }`", "None", "`202` `{ payment, authorizationUrl }`",
         "`409` contribution not payable · `422` invalid bank account", "Used by mobile where the payment is initiated natively. `amountKobo` is ignored if present — the server value always wins."),
    *_ep("POST", "/api/v1/payments/:id/verify", "Actively confirm a payment's final state.", "Bearer", "Owning member.", "None", "`id`",
         "`200` `{ payment: { status, state, settledAt? } }`", "`503` provider unavailable",
         "The member-facing 'I have paid' button. Queries the provider directly rather than waiting for a webhook. **This is the safety net for a lost webhook**, and it must be available even if the webhook system is broken."),
    *_ep("GET", "/api/v1/payments/:id", "Payment detail.", "Bearer", "Owning member or admin.", "None", "`id`",
         "`200` `{ payment }`", "`404`", "Includes provider reference and the ledger transaction id."),
    *_ep("GET", "/api/v1/payments/:id/receipt", "Receipt for a settled payment.", "Bearer", "Owning member.",
         "None", "`id`", "`200` `{ receipt: { receiptNumber, issuedAt, contributionKobo, feeKobo, totalKobo, ajoName, roundNumber, providerReference, signatureHash } }`",
         "`404` not settled",
         "The receipt shows the contribution and the 2% fee as separate lines. A `signatureHash` allows a later integrity check."),

    {"t": "h2", "text": "11.7 Payouts and transactions"},
    *_ep("GET", "/api/v1/ajos/:id/payouts", "Payout history for an Ajo.", "Bearer", "Member of that Ajo.", "None", "`id`",
         "`200` `{ payouts: [{ id, roundNumber, recipientId, recipientName, amountKobo, status, scheduledAt, releasedAt?, settledAt?, failureReason? }] }`", "None",
         "The amount is always the base pool, never reduced by the platform fee."),
    *_ep("GET", "/api/v1/payouts/:id", "Payout detail.", "Bearer", "Recipient, Ajo organizer, or admin.", "None", "`id`",
         "`200` `{ payout, fundingCheck: { expectedKobo, availableKobo, sufficient } }`", "`404`",
         "Exposing the funding check is how a member or the organizer sees *why* a payout is held."),
    *_ep("POST", "/api/v1/payouts/:id/release", "Request release of a due payout. **Idempotency-Key required.**", "Bearer",
         "ajo_organizer, or automatic once all contributions are confirmed.",
         "`{ confirm: true }`", "`id`", "`202` `{ payout, status: 'RELEASED' }`",
         "`409` not yet due · `422` funding insufficient — the payout is placed in `HELD`, not partially paid",
         "**The payout funding principle is absolute: if the expected amount is not fully available, the payout is held. AJO.ng must never silently reduce a payout and must never use corporate funds to make one good.**"),
    *_ep("GET", "/api/v1/payouts", "Payouts across all of the caller's Ajos.", "Bearer", "Member.", "None", "None",
         "`200` `{ data: [...], page }`", "None", "Default sort is most recent."),
    *_ep("GET", "/api/v1/transactions", "The caller's unified transaction ledger view.", "Bearer", "Member.", "None", "None",
         "`200` `{ data: [{ id, type: 'CONTRIBUTION'|'PAYOUT'|'REFUND'|'FEE', ajoId, ajoName, amountKobo, direction, status, occurredAt, reference }], page }`", "None",
         "A read model projected from `ledger_transactions`. `direction` is explicit so a member never has to infer a sign."),
    *_ep("GET", "/api/v1/transactions/:id", "A single ledger transaction with its postings.", "Bearer", "Member with a posting in it.",
         "None", "`id`", "`200` `{ transaction: { id, kind, occurredAt, postings: [{ account, side, amountKobo }], reversesTransactionId? } }`", "Not found",
         "Exposes the double-entry postings. This is what makes a disputed figure explainable rather than arguable."),
    *_ep("GET", "/api/v1/statements", "Generate a period statement.", "Bearer", "Member.",
         "None", None, "`200` `{ statementUrl, period: { from, to }, totals: {...} }`", "`422` invalid period",
         "Asynchronous for long ranges. Statement content must match the ledger exactly, including fee lines."),

    {"t": "h2", "text": "11.8 Notifications"},
    *_ep("GET", "/api/v1/notifications", "The caller's notifications.", "Bearer", "Member.", "None", "None",
         "`200` `{ data: [{ id, type, priority, title, body, data, readAt?, createdAt }], page }`", "None",
         "Types match the catalogue in section 16. Unread count is returned in a header for the badge."),
    *_ep("POST", "/api/v1/notifications/:id/read", "Mark one read.", "Bearer", "Owning member.", "None", "`id`", "`204`", "`404`", "Idempotent."),
    *_ep("POST", "/api/v1/notifications/read-all", "Mark all read.", "Bearer", "Member.", "None", "None", "`204`", "None", "Idempotent."),
    *_ep("GET", "/api/v1/notification-preferences", "Read channel preferences.", "Bearer", "Member.", "None", "None",
         "`200` `{ preferences: [{ eventType, push, email, sms, enabled }] }`", "None", "Mirrors the catalogue in section 16."),
    *_ep("PUT", "/api/v1/notification-preferences", "Update channel preferences.", "Bearer", "Member.", "`{ preferences: [...] }`", "None",
         "`200` `{ preferences }`", "`422` unknown event type",
         "**Money-critical and security notifications cannot be switched off.** A member may change the channel but never the delivery obligation for a due contribution, a payout, or a security alert."),

    {"t": "h2", "text": "11.9 Disputes"},
    *_ep("POST", "/api/v1/disputes", "Raise a dispute.", "Bearer", "Member of the Ajo concerned.",
         "`{ ajoId, type: 'MISSING_PAYOUT'|'INCORRECT_AMOUNT'|'WRONG_RECIPIENT'|'UNAUTHORISED_DEDUCTION'|'OTHER', subject, description, transactionId?, expectedOutcome? }`", "None",
         "`201` `{ dispute: { id, reference, status: 'OPEN', priority, slaAt } }`", "`422` invalid type · `409` open dispute already exists for this transaction",
         "A dispute **freezes the affected payout** automatically and raises a risk event. The reference is shown to the member for support."),
    *_ep("GET", "/api/v1/disputes", "The caller's disputes.", "Bearer", "Member.", "None", "None", "`200` `{ data: [...], page }`", "None", "Default sort most recent."),
    *_ep("GET", "/api/v1/disputes/:id", "Dispute detail and timeline.", "Bearer", "Party to the dispute or admin.", "None", "`id`",
         "`200` `{ dispute, messages: [...], timeline: [...] }`", "`403` not a party", "Every admin action on the dispute is timestamped in the timeline."),
    *_ep("POST", "/api/v1/disputes/:id/evidence", "Attach evidence.", "Bearer", "Party to the dispute.",
         "`{ documentIds: [uuid], note? }`", "`id`", "`201` `{ evidence: [...] }`",
         "`422` unsupported type or oversized file", "Scanned files only; validated by MIME type **and** magic bytes, virus-scanned, stored privately, served via short-lived signed URLs."),
    *_ep("POST", "/api/v1/disputes/:id/messages", "Add a message to the dispute thread.", "Bearer", "Party or admin.", "`{ body }`", "`id`",
         "`201` `{ message }`", "None", "Full thread is retained; messages are never deleted."),

    {"t": "h2", "text": "11.10 Webhooks (inbound)"},
    *_ep("POST", "/api/v1/webhooks/payments", "Provider payment notification.", "HMAC signature over the raw body", "Provider only. **Unauthenticated by design** — auth is the signature.",
         "Provider-defined payload. The raw body is required for signature verification before parsing.", "None",
         "`200` `{ received: true }` — always 200 once the signature verifies, even for a duplicate, so the provider stops retrying",
         "`401` signature invalid · `400` unparseable after valid signature",
         "**Dedupe by provider reference.** A duplicate is recorded as `DUPLICATE_IGNORED` in `webhook_events` and returns 200. A signature failure is logged at ERROR and alerted — it may be an attack. Always `2xx` fast: heavy processing is queued, not done inline. **The webhook is not the only path to truth** — reconciliation independently confirms state."),

    {"t": "h2", "text": "11.11 Admin endpoints"},
    {"t": "p", "text": "Admin routes are versioned separately at `/api/admin/v1`, protected "
     "by network allow-list plus role, and every call writes an `audit_logs` row. `support` "
     "may read but may not move money; `risk_officer` may freeze and decide risk but may not "
     "edit the ledger; only `super_admin` may assign roles."},
    *_ep("GET", "/api/admin/v1/overview", "Operational dashboard aggregates.", "Bearer + admin role", "support, risk_officer, super_admin.",
         "None", "None", "`200` `{ totalUsers, activeAjos, volumeTodayKobo, feesTodayKobo, openDisputes, riskQueueCount, payoutFailures24h, reconciliationStatus }`", "`403`", "Aggregates only, no member data."),
    *_ep("GET", "/api/admin/v1/users", "Search members.", "Bearer + admin role", "support, risk_officer, super_admin.",
         "None", "`q`, `status`, `kycStatus`, `cursor`, `limit`", "`200` `{ data: [...], page }`", "`403`",
         "Bank details are redacted unless the caller holds `pii.read` permission. Every search is audited — searching for a person is a sensitive act."),
    *_ep("GET", "/api/admin/v1/ajos", "Search and filter Ajos.", "Bearer + admin role", "Any admin role.",
         "None", "`status`, `organizerId`, `hasDefaults`, `from`, `to`", "`200` `{ data: [...], page }`", "`403`", "Supports the incident workflow 'show me every Ajo with an open default'."),
    *_ep("GET", "/api/admin/v1/disputes", "Dispute queue.", "Bearer + admin role", "Any admin role.",
         "None", "`status`, `priority`, `slaBreached`, `assignee`", "`200` `{ data: [...], page }`", "`403`", "Default sort: SLA ascending, so the most urgent is first."),
    *_ep("GET", "/api/admin/v1/risk", "Risk event queue.", "Bearer + admin role", "risk_officer, super_admin.",
         "None", "`severity`, `type`, `status`", "`200` `{ data: [{ id, type, severity, subject, signals, status }], page }`", "`403`", "Never returned to `support`."),
    *_ep("POST", "/api/admin/v1/risk/:id/decision", "Record a risk decision.", "Bearer + admin role", "risk_officer, super_admin.",
         "`{ decision: 'CLEAR'|'MONITOR'|'RESTRICT'|'FREEZE'|'ESCALATE', reason, restrictions? }`", "`id`", "`200` `{ riskEvent }`",
         "`409` already decided · `422` reason required", "`support` is explicitly denied. Restrictions are enforced by the API, not only displayed."),
    *_ep("POST", "/api/admin/v1/users/:id/freeze", "Freeze a member account.", "Bearer + admin role", "risk_officer, super_admin.",
         "`{ reason, scope: 'CONTRIBUTIONS'|'ALL' }`", "`id`", "`200` `{ user, frozenScope }`", "`422` reason required",
         "`CONTRIBUTIONS` blocks new payments but allows the member to receive a payout they are already owed — **freezing a member must never trap their own money**."),
    *_ep("GET", "/api/admin/v1/audit-logs", "Audit trail query.", "Bearer + admin role", "super_admin only.",
         "None", "`actorId`, `action`, `subjectType`, `subjectId`, `from`, `to`", "`200` `{ data: [...], page }`", "`403`",
         "Append-only; there is no write, update or delete endpoint anywhere in the admin API."),
    *_ep("GET", "/api/admin/v1/reports/:type", "Operational and financial reports.", "Bearer + admin role", "Any admin role, filtered by report type.",
         "None", "`type`, `from`, `to`, `format`", "`200` `{ reportUrl, generatedAt, rowCount }`", "`403` report type not permitted · `422` invalid date range",
         "Types: volume, fees, defaults, reconciliation, user-growth, payout-failure."),

    {"t": "h2", "text": "11.12 API security controls summary"},
    {"t": "table", "head": ["Control", "Implementation"], "widths": [1.9, 4.6], "size": 8.4, "rows": [
        ["Authentication", "Short-lived JWT access token, rotating opaque refresh token in an httpOnly cookie"],
        ["Token theft detection", "Refresh-token reuse revokes the entire family and notifies the member"],
        ["Authorization", "Role-based (section 12) plus PostgreSQL RLS as a second layer"],
        ["Object-level authorization", "Every resource query is scoped by membership; a `403` and a `404` are distinguished only where that does not leak existence"],
        ["Input validation", "Zod at the boundary. The database additionally enforces CHECK and FK constraints"],
        ["SQL injection", "Parameterised queries exclusively; string-built SQL is banned by lint rule"],
        ["Mass assignment", "Explicit allow-listed field maps. A `role` or `status` in a request body is never bound"],
        ["Rate limiting", "Per member and per identifier, not per IP (section 11.1.5)"],
        ["Idempotency", "Required header on every money-moving POST, with request-body hashing"],
        ["Webhook security", "HMAC over the raw body, constant-time comparison, timestamp tolerance window, replay protection via stored event IDs"],
        ["PII exposure", "Bank account numbers and BVN never returned to a client that lacks `pii.read`; masked in all logs"],
        ["Response hygiene", "`Cache-Control: no-store` on every authenticated response containing financial data"],
    ]},
]
