-- Foreign keys, indexes, triggers, and row-level security
--
-- Adopted from the `ajo` database, which held this schema with no
-- SQL source in version control. Generated by scripts/adopt_schema.py;
-- do not hand-edit, re-run the generator and commit the result.
--
-- 352 object(s).

SET check_function_bodies = false;

--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_invited_by_user_id_fkey FOREIGN KEY (invited_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.ajo_members
    ADD CONSTRAINT ajo_members_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ajo_members
    ADD CONSTRAINT ajo_members_invitation_fk FOREIGN KEY (invitation_id) REFERENCES public.invitations(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ajo_members
    ADD CONSTRAINT ajo_members_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.ajo_positions(id) ON DELETE SET NULL;


--

--

ALTER TABLE ONLY public.ajo_members
    ADD CONSTRAINT ajo_members_replaced_by_membership_id_fkey FOREIGN KEY (replaced_by_membership_id) REFERENCES public.ajo_members(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ajo_members
    ADD CONSTRAINT ajo_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ajo_positions
    ADD CONSTRAINT ajo_positions_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ajos
    ADD CONSTRAINT ajos_frequency_id_fkey FOREIGN KEY (frequency_id) REFERENCES public.contribution_frequencies(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ajos
    ADD CONSTRAINT ajos_organizer_user_id_fkey FOREIGN KEY (organizer_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ajos
    ADD CONSTRAINT ajos_preferred_channel_id_fkey FOREIGN KEY (preferred_channel_id) REFERENCES public.payment_channels(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_actor_role_code_fkey FOREIGN KEY (actor_role_code) REFERENCES public.roles(code) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.contribution_schedules
    ADD CONSTRAINT contribution_schedules_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.contribution_schedules
    ADD CONSTRAINT contribution_schedules_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.ajo_members(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.ajo_positions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.contribution_schedules(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_superseded_by_contribution_id_fkey FOREIGN KEY (superseded_by_contribution_id) REFERENCES public.contributions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.dispute_evidence
    ADD CONSTRAINT dispute_evidence_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES public.disputes(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.dispute_evidence
    ADD CONSTRAINT dispute_evidence_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.dispute_messages
    ADD CONSTRAINT dispute_messages_author_user_id_fkey FOREIGN KEY (author_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.dispute_messages
    ADD CONSTRAINT dispute_messages_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES public.disputes(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.dispute_messages
    ADD CONSTRAINT dispute_messages_resulting_transaction_id_fkey FOREIGN KEY (resulting_transaction_id) REFERENCES public.ledger_transactions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_against_user_id_fkey FOREIGN KEY (against_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_contribution_id_fkey FOREIGN KEY (contribution_id) REFERENCES public.contributions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES public.payouts(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_raised_by_user_id_fkey FOREIGN KEY (raised_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_reason_id_fkey FOREIGN KEY (reason_id) REFERENCES public.dispute_reasons(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_resolved_by_user_id_fkey FOREIGN KEY (resolved_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_doc_type_id_fkey FOREIGN KEY (doc_type_id) REFERENCES public.document_types(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_verification_check_id_fkey FOREIGN KEY (verification_check_id) REFERENCES public.verification_checks(id) ON DELETE SET NULL;


--

--

ALTER TABLE ONLY public.fees
    ADD CONSTRAINT fees_contribution_id_fkey FOREIGN KEY (contribution_id) REFERENCES public.contributions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.fees
    ADD CONSTRAINT fees_ledger_transaction_fk FOREIGN KEY (ledger_transaction_id) REFERENCES public.ledger_transactions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.fees
    ADD CONSTRAINT fees_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.idempotency_keys
    ADD CONSTRAINT idempotency_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_accepted_by_user_id_fkey FOREIGN KEY (accepted_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_invited_by_user_id_fkey FOREIGN KEY (invited_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.ajo_positions(id) ON DELETE SET NULL;


--

--

ALTER TABLE ONLY public.ledger_postings
    ADD CONSTRAINT ledger_postings_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.ajo_members(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ledger_postings
    ADD CONSTRAINT ledger_postings_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ledger_postings
    ADD CONSTRAINT ledger_postings_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.ledger_transactions(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;


--

--

ALTER TABLE ONLY public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_idempotency_fk FOREIGN KEY (idempotency_key) REFERENCES public.idempotency_keys(key) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.ajo_members(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES public.payouts(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_reverses_transaction_id_fkey FOREIGN KEY (reverses_transaction_id) REFERENCES public.ledger_transactions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.notification_templates(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.payment_channels(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_contribution_id_fkey FOREIGN KEY (contribution_id) REFERENCES public.contributions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_webhook_event_fk FOREIGN KEY (webhook_event_id) REFERENCES public.webhook_events(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.ajo_members(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.ajo_positions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_recognized_transaction_fk FOREIGN KEY (recognized_transaction_id) REFERENCES public.ledger_transactions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_round_id_fkey FOREIGN KEY (round_id) REFERENCES public.rounds(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_settled_transaction_fk FOREIGN KEY (settled_transaction_id) REFERENCES public.ledger_transactions(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_avatar_document_fk FOREIGN KEY (avatar_document_id) REFERENCES public.documents(id) ON DELETE SET NULL;


--

--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_preferred_channel_fk FOREIGN KEY (preferred_channel_id) REFERENCES public.payment_channels(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.reconciliation_runs
    ADD CONSTRAINT reconciliation_runs_triggered_by_user_id_fkey FOREIGN KEY (triggered_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.risk_events
    ADD CONSTRAINT risk_events_assigned_to_user_id_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.risk_events
    ADD CONSTRAINT risk_events_decided_by_user_id_fkey FOREIGN KEY (decided_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT role_assignments_ajo_fk FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT role_assignments_ajo_member_fk FOREIGN KEY (ajo_member_id) REFERENCES public.ajo_members(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT role_assignments_granted_by_user_id_fkey FOREIGN KEY (granted_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT role_assignments_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(code) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.role_assignments
    ADD CONSTRAINT role_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.rounds
    ADD CONSTRAINT rounds_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.support_tickets
    ADD CONSTRAINT support_tickets_ajo_id_fkey FOREIGN KEY (ajo_id) REFERENCES public.ajos(id) ON DELETE SET NULL;


--

--

ALTER TABLE ONLY public.support_tickets
    ADD CONSTRAINT support_tickets_assigned_to_user_id_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--

--

ALTER TABLE ONLY public.support_tickets
    ADD CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--

--

ALTER TABLE ONLY public.verification_check_types
    ADD CONSTRAINT verification_check_types_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES public.document_types(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.verification_checks
    ADD CONSTRAINT verification_checks_check_type_id_fkey FOREIGN KEY (check_type_id) REFERENCES public.verification_check_types(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.verification_checks
    ADD CONSTRAINT verification_checks_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

ALTER TABLE ONLY public.verification_checks
    ADD CONSTRAINT verification_checks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--

--

CREATE INDEX ajo_members_ajo_idx ON public.ajo_members USING btree (ajo_id, status) WHERE (deleted_at IS NULL);


--

--

CREATE UNIQUE INDEX ajo_members_one_live_position ON public.ajo_members USING btree (ajo_id, position_id) WHERE ((position_id IS NOT NULL) AND (deleted_at IS NULL) AND (status <> ALL (ARRAY['exited'::public.member_status, 'replaced'::public.member_status, 'removed'::public.member_status])));


--

--

CREATE UNIQUE INDEX ajo_members_one_per_invitation ON public.ajo_members USING btree (invitation_id) WHERE (invitation_id IS NOT NULL);


--

--

CREATE INDEX ajo_members_user_idx ON public.ajo_members USING btree (user_id, status) WHERE (deleted_at IS NULL);


--

--

CREATE INDEX ajo_positions_claimable_idx ON public.ajo_positions USING btree (ajo_id, position_number) WHERE ((status = 'open'::public.position_status) AND (deleted_at IS NULL));


--

--

CREATE INDEX ajos_live_idx ON public.ajos USING btree (organizer_user_id, status) WHERE ((deleted_at IS NULL) AND (status <> ALL (ARRAY['completed'::public.ajo_status, 'cancelled'::public.ajo_status])));


--

--

CREATE INDEX ajos_organizer_idx ON public.ajos USING btree (organizer_user_id, created_at DESC);


--

--

CREATE INDEX ajos_status_idx ON public.ajos USING btree (status);


--

--

CREATE INDEX audit_logs_action_idx ON public.audit_logs USING btree (action, occurred_at DESC);


--

--

CREATE INDEX audit_logs_actor_idx ON public.audit_logs USING btree (actor_user_id, occurred_at DESC);


--

--

CREATE INDEX audit_logs_request_idx ON public.audit_logs USING btree (request_id) WHERE (request_id IS NOT NULL);


--

--

CREATE INDEX audit_logs_subject_idx ON public.audit_logs USING btree (subject_type, subject_id, occurred_at DESC);


--

--

CREATE INDEX audit_logs_time_idx ON public.audit_logs USING btree (occurred_at DESC);


--

--

CREATE INDEX contribution_schedules_ajo_due_idx ON public.contribution_schedules USING btree (ajo_id, due_date);


--

--

CREATE INDEX contributions_ajo_status_idx ON public.contributions USING btree (ajo_id, status) WHERE (deleted_at IS NULL);


--

--

CREATE INDEX contributions_due_sweep_idx ON public.contributions USING btree (due_date) WHERE ((status = ANY (ARRAY['pending'::public.contribution_status, 'overdue'::public.contribution_status, 'grace'::public.contribution_status])) AND (deleted_at IS NULL));


--

--

CREATE INDEX contributions_member_idx ON public.contributions USING btree (member_id) WHERE (deleted_at IS NULL);


--

--

CREATE UNIQUE INDEX contributions_one_live_per_slot ON public.contributions USING btree (schedule_id, position_id) WHERE ((superseded_at IS NULL) AND (deleted_at IS NULL));


--

--

CREATE UNIQUE INDEX contributions_one_per_user_per_round ON public.contributions USING btree (user_id, round_id) WHERE ((superseded_at IS NULL) AND (deleted_at IS NULL));


--

--

CREATE INDEX contributions_round_status_idx ON public.contributions USING btree (round_id, status) WHERE ((superseded_at IS NULL) AND (deleted_at IS NULL));


--

--

CREATE INDEX contributions_user_status_idx ON public.contributions USING btree (user_id, status, due_date DESC) WHERE (deleted_at IS NULL);


--

--

CREATE UNIQUE INDEX dispute_evidence_unique ON public.dispute_evidence USING btree (dispute_id, document_id);


--

--

CREATE INDEX dispute_messages_dispute_idx ON public.dispute_messages USING btree (dispute_id, created_at);


--

--

CREATE INDEX disputes_ajo_status_idx ON public.disputes USING btree (ajo_id, status, created_at DESC);


--

--

CREATE INDEX disputes_open_queue_idx ON public.disputes USING btree (status, created_at) WHERE ((status <> ALL (ARRAY['resolved'::public.dispute_status, 'withdrawn'::public.dispute_status])) AND (deleted_at IS NULL));


--

--

CREATE INDEX disputes_raised_by_idx ON public.disputes USING btree (raised_by_user_id, created_at DESC);


--

--

CREATE INDEX fees_ledger_idx ON public.fees USING btree (ledger_transaction_id) WHERE (ledger_transaction_id IS NOT NULL);


--

--

CREATE INDEX fees_period_idx ON public.fees USING btree (created_at);


--

--

CREATE INDEX fees_status_idx ON public.fees USING btree (status, created_at DESC);


--

--

CREATE INDEX idempotency_keys_expiry_idx ON public.idempotency_keys USING btree (expires_at);


--

--

CREATE INDEX idempotency_keys_resource_idx ON public.idempotency_keys USING btree (resource_type, resource_id) WHERE (resource_id IS NOT NULL);


--

--

CREATE INDEX idempotency_keys_user_idx ON public.idempotency_keys USING btree (user_id, created_at DESC);


--

--

CREATE INDEX invitations_email_idx ON public.invitations USING btree (email, status);


--

--

CREATE INDEX invitations_expiry_idx ON public.invitations USING btree (expires_at) WHERE (status = 'pending'::public.invitation_status);


--

--

CREATE UNIQUE INDEX invitations_one_pending_per_ajo_email ON public.invitations USING btree (ajo_id, email) WHERE (status = 'pending'::public.invitation_status);


--

--

CREATE INDEX ledger_postings_account_idx ON public.ledger_postings USING btree (account_kind, created_at);


--

--

CREATE INDEX ledger_postings_member_idx ON public.ledger_postings USING btree (member_id) WHERE (member_id IS NOT NULL);


--

--

CREATE INDEX ledger_postings_transaction_idx ON public.ledger_postings USING btree (transaction_id);


--

--

CREATE INDEX ledger_transactions_ajo_occurred_idx ON public.ledger_transactions USING btree (ajo_id, occurred_at DESC);


--

--

CREATE UNIQUE INDEX ledger_transactions_idempotency_unique ON public.ledger_transactions USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);


--

--

CREATE INDEX ledger_transactions_kind_occurred_idx ON public.ledger_transactions USING btree (kind, occurred_at);


--

--

CREATE INDEX ledger_transactions_member_occurred_idx ON public.ledger_transactions USING btree (member_id, occurred_at DESC);


--

--

CREATE UNIQUE INDEX ledger_transactions_one_reversal_each ON public.ledger_transactions USING btree (reverses_transaction_id) WHERE (reverses_transaction_id IS NOT NULL);


--

--

CREATE INDEX ledger_transactions_payout_idx ON public.ledger_transactions USING btree (payout_id) WHERE (payout_id IS NOT NULL);


--

--

CREATE INDEX ledger_transactions_round_occurred_idx ON public.ledger_transactions USING btree (round_id, occurred_at);


--

--

CREATE UNIQUE INDEX notifications_dedupe_unique ON public.notifications USING btree (dedupe_key, channel);


--

--

CREATE INDEX notifications_event_idx ON public.notifications USING btree (event_key, created_at DESC);


--

--

CREATE INDEX notifications_inbox_idx ON public.notifications USING btree (user_id, created_at DESC) WHERE (deleted_at IS NULL);


--

--

CREATE INDEX notifications_queue_idx ON public.notifications USING btree (scheduled_for) WHERE ((status = 'queued'::public.notification_status) AND (deleted_at IS NULL));


--

--

CREATE INDEX notifications_unread_idx ON public.notifications USING btree (user_id) WHERE ((read_at IS NULL) AND (deleted_at IS NULL));


--

--

CREATE UNIQUE INDEX outbox_events_dedupe_unique ON public.outbox_events USING btree (event_type, aggregate_id);


--

--

CREATE INDEX outbox_events_pending_idx ON public.outbox_events USING btree (next_retry_at) WHERE (status = 'pending'::public.outbox_status);


--

--

CREATE INDEX payments_contribution_idx ON public.payments USING btree (contribution_id, created_at DESC);


--

--

CREATE UNIQUE INDEX payments_idempotency_key_unique ON public.payments USING btree (idempotency_key);


--

--

CREATE UNIQUE INDEX payments_one_per_webhook_event ON public.payments USING btree (webhook_event_id) WHERE (webhook_event_id IS NOT NULL);


--

--

CREATE UNIQUE INDEX payments_one_success_per_contribution ON public.payments USING btree (contribution_id) WHERE (status = 'success'::public.payment_status);


--

--

CREATE UNIQUE INDEX payments_provider_reference_unique ON public.payments USING btree (provider, provider_reference) WHERE (provider_reference IS NOT NULL);


--

--

CREATE INDEX payments_status_idx ON public.payments USING btree (status, created_at DESC) WHERE (deleted_at IS NULL);


--

--

CREATE INDEX payouts_ajo_idx ON public.payouts USING btree (ajo_id, status);


--

--

CREATE UNIQUE INDEX payouts_one_live_per_slot ON public.payouts USING btree (round_id, position_id) WHERE ((status = ANY (ARRAY['scheduled'::public.payout_status, 'funding'::public.payout_status, 'released'::public.payout_status, 'held'::public.payout_status])) AND (deleted_at IS NULL));


--

--

CREATE UNIQUE INDEX payouts_provider_reference_unique ON public.payouts USING btree (provider, provider_reference) WHERE (provider_reference IS NOT NULL);


--

--

CREATE INDEX payouts_status_idx ON public.payouts USING btree (status, created_at DESC) WHERE (deleted_at IS NULL);


--

--

CREATE INDEX payouts_user_idx ON public.payouts USING btree (user_id, created_at DESC);


--

--

CREATE INDEX reconciliation_runs_blocking_idx ON public.reconciliation_runs USING btree (started_at DESC) WHERE ((status = 'failed'::public.reconciliation_status) AND blocks_disbursement);


--

--

CREATE INDEX reconciliation_runs_status_idx ON public.reconciliation_runs USING btree (status, started_at DESC);


--

--

CREATE INDEX reconciliation_runs_window_idx ON public.reconciliation_runs USING btree (window_start DESC, window_end DESC);


--

--

CREATE INDEX risk_events_open_idx ON public.risk_events USING btree (severity DESC, created_at) WHERE (status = ANY (ARRAY['open'::public.risk_event_status, 'under_review'::public.risk_event_status, 'escalated'::public.risk_event_status]));


--

--

CREATE INDEX risk_events_queue_idx ON public.risk_events USING btree (assigned_to_user_id, status);


--

--

CREATE INDEX risk_events_subject_idx ON public.risk_events USING btree (subject_type, subject_id, created_at DESC);


--

--

CREATE UNIQUE INDEX role_assignments_ajo_unique ON public.role_assignments USING btree (role_id, user_id, ajo_id) WHERE ((scope = 'ajo'::public.role_scope) AND (revoked_at IS NULL) AND (deleted_at IS NULL));


--

--

CREATE UNIQUE INDEX role_assignments_platform_unique ON public.role_assignments USING btree (role_id, user_id) WHERE ((scope = 'platform'::public.role_scope) AND (revoked_at IS NULL) AND (deleted_at IS NULL));


--

--

CREATE INDEX rounds_due_idx ON public.rounds USING btree (due_date) WHERE (status = ANY (ARRAY['scheduled'::public.round_status, 'in_progress'::public.round_status, 'funding'::public.round_status, 'held'::public.round_status]));


--

--

CREATE UNIQUE INDEX rounds_one_in_progress_per_ajo ON public.rounds USING btree (ajo_id) WHERE (status = 'in_progress'::public.round_status);


--

--

CREATE UNIQUE INDEX sessions_one_active_per_device ON public.sessions USING btree (user_id, platform, device_label) WHERE ((revoked_at IS NULL) AND (deleted_at IS NULL));


--

--

CREATE UNIQUE INDEX sessions_refresh_token_hash_unique ON public.sessions USING btree (refresh_token_hash);


--

--

CREATE INDEX support_tickets_assignee_idx ON public.support_tickets USING btree (assigned_to_user_id, status) WHERE (assigned_to_user_id IS NOT NULL);


--

--

CREATE INDEX support_tickets_queue_idx ON public.support_tickets USING btree (status, priority DESC, created_at) WHERE (deleted_at IS NULL);


--

--

CREATE INDEX support_tickets_user_idx ON public.support_tickets USING btree (user_id, created_at DESC);


--

--

CREATE INDEX verification_checks_user_created_idx ON public.verification_checks USING btree (user_id, created_at DESC);


--

--

CREATE INDEX webhook_events_received_idx ON public.webhook_events USING btree (received_at DESC);


--

--

CREATE INDEX webhook_events_retry_idx ON public.webhook_events USING btree (next_retry_at) WHERE (status = ANY (ARRAY['received'::public.webhook_processing_status, 'failed'::public.webhook_processing_status]));


--

--

CREATE UNIQUE INDEX webhook_events_success_once ON public.webhook_events USING btree (provider_event_id) WHERE (status = 'processed'::public.webhook_processing_status);


--

--

ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.ajo_members ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.ajo_positions ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.ajos ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.contribution_frequencies ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.contribution_schedules ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.contributions ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.device_tokens ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.dispute_evidence ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.dispute_messages ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.dispute_reasons ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.disputes ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.document_types ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.fees ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.idempotency_keys ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.ledger_postings ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.ledger_transactions ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.notification_templates ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.outbox_events ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.payment_channels ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.payouts ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.reconciliation_runs ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.risk_events ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.role_assignments ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.rounds ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.verification_check_types ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.verification_checks ENABLE ROW LEVEL SECURITY;

--

--

ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;

--

--

CREATE TRIGGER admins_audit AFTER INSERT OR DELETE OR UPDATE ON public.admins FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER admins_touch BEFORE UPDATE ON public.admins FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER ajo_members_audit AFTER INSERT OR DELETE OR UPDATE ON public.ajo_members FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER ajo_members_touch BEFORE UPDATE ON public.ajo_members FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER ajo_positions_audit AFTER INSERT OR DELETE OR UPDATE ON public.ajo_positions FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER ajo_positions_locked BEFORE UPDATE ON public.ajo_positions FOR EACH ROW EXECUTE FUNCTION app.assert_positions_locked();


--

--

CREATE TRIGGER ajo_positions_touch BEFORE UPDATE ON public.ajo_positions FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER ajos_audit AFTER INSERT OR DELETE OR UPDATE ON public.ajos FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER ajos_draft_exit BEFORE UPDATE ON public.ajos FOR EACH ROW EXECUTE FUNCTION app.assert_draft_exit();


--

--

CREATE TRIGGER ajos_lifecycle BEFORE UPDATE ON public.ajos FOR EACH ROW EXECUTE FUNCTION app.assert_lifecycle_transition();


--

--

CREATE TRIGGER ajos_terminal_timestamps BEFORE INSERT OR UPDATE ON public.ajos FOR EACH ROW EXECUTE FUNCTION app.assert_terminal_timestamps();


--

--

CREATE TRIGGER ajos_touch BEFORE UPDATE ON public.ajos FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER audit_logs_append_only BEFORE DELETE OR UPDATE ON public.audit_logs FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE TRIGGER audit_logs_no_truncate BEFORE TRUNCATE ON public.audit_logs FOR EACH STATEMENT EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE TRIGGER contribution_frequencies_touch BEFORE UPDATE ON public.contribution_frequencies FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER contribution_schedules_touch BEFORE UPDATE ON public.contribution_schedules FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER contributions_audit AFTER INSERT OR DELETE OR UPDATE ON public.contributions FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE CONSTRAINT TRIGGER contributions_pool_still_matches AFTER INSERT OR UPDATE ON public.contributions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_round_pool();


--

--

CREATE TRIGGER contributions_touch BEFORE UPDATE ON public.contributions FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER device_tokens_touch BEFORE UPDATE ON public.device_tokens FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER dispute_evidence_append_only BEFORE DELETE OR UPDATE ON public.dispute_evidence FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE TRIGGER dispute_evidence_no_truncate BEFORE TRUNCATE ON public.dispute_evidence FOR EACH STATEMENT EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE TRIGGER dispute_messages_append_only BEFORE DELETE OR UPDATE ON public.dispute_messages FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE TRIGGER dispute_messages_no_truncate BEFORE TRUNCATE ON public.dispute_messages FOR EACH STATEMENT EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE TRIGGER disputes_audit AFTER INSERT OR DELETE OR UPDATE ON public.disputes FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER disputes_touch BEFORE UPDATE ON public.disputes FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER document_types_touch BEFORE UPDATE ON public.document_types FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER documents_audit AFTER INSERT OR DELETE OR UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER documents_touch BEFORE UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER fees_audit AFTER INSERT OR DELETE OR UPDATE ON public.fees FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE CONSTRAINT TRIGGER fees_match_payment AFTER INSERT OR UPDATE ON public.fees DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_fee_matches_payment();


--

--

CREATE TRIGGER fees_touch BEFORE UPDATE ON public.fees FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER idempotency_keys_touch BEFORE UPDATE ON public.idempotency_keys FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER invitations_audit AFTER INSERT OR DELETE OR UPDATE ON public.invitations FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER invitations_touch BEFORE UPDATE ON public.invitations FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER ledger_postings_append_only BEFORE DELETE OR UPDATE ON public.ledger_postings FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE CONSTRAINT TRIGGER ledger_postings_balanced AFTER INSERT OR DELETE OR UPDATE ON public.ledger_postings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_transaction_balanced();


--

--

CREATE TRIGGER ledger_postings_no_truncate BEFORE TRUNCATE ON public.ledger_postings FOR EACH STATEMENT EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE TRIGGER ledger_transactions_append_only BEFORE DELETE OR UPDATE ON public.ledger_transactions FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE TRIGGER ledger_transactions_audit AFTER INSERT OR DELETE OR UPDATE ON public.ledger_transactions FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE CONSTRAINT TRIGGER ledger_transactions_balanced AFTER INSERT OR UPDATE ON public.ledger_transactions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_ledger_balanced_for_txn();


--

--

CREATE TRIGGER ledger_transactions_no_truncate BEFORE TRUNCATE ON public.ledger_transactions FOR EACH STATEMENT EXECUTE FUNCTION app.reject_mutation();


--

--

CREATE CONSTRAINT TRIGGER ledger_transactions_sequence AFTER INSERT OR UPDATE ON public.ledger_transactions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_ledger_sequence();


--

--

CREATE TRIGGER notification_preferences_touch BEFORE UPDATE ON public.notification_preferences FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER notification_templates_touch BEFORE UPDATE ON public.notification_templates FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE CONSTRAINT TRIGGER templates_critical_have_sms AFTER INSERT OR UPDATE ON public.notification_templates DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_money_critical_has_sms();


--

--

CREATE TRIGGER notifications_touch BEFORE UPDATE ON public.notifications FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER outbox_events_touch BEFORE UPDATE ON public.outbox_events FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER payment_channels_touch BEFORE UPDATE ON public.payment_channels FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER payments_audit AFTER INSERT OR DELETE OR UPDATE ON public.payments FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER payments_touch BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER payouts_audit AFTER INSERT OR DELETE OR UPDATE ON public.payouts FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER payouts_touch BEFORE UPDATE ON public.payouts FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER platform_settings_touch BEFORE UPDATE ON public.platform_settings FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER profiles_audit AFTER INSERT OR DELETE OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER profiles_touch BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER reconciliation_runs_touch BEFORE UPDATE ON public.reconciliation_runs FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER risk_events_audit AFTER INSERT OR DELETE OR UPDATE ON public.risk_events FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER risk_events_subject_exists BEFORE INSERT ON public.risk_events FOR EACH ROW EXECUTE FUNCTION app.assert_risk_subject_exists();


--

--

CREATE TRIGGER risk_events_touch BEFORE UPDATE ON public.risk_events FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER role_assignments_audit AFTER INSERT OR DELETE OR UPDATE ON public.role_assignments FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER role_assignments_touch BEFORE UPDATE ON public.role_assignments FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER rounds_audit AFTER INSERT OR DELETE OR UPDATE ON public.rounds FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE CONSTRAINT TRIGGER rounds_pool_matches_contributions AFTER INSERT OR UPDATE ON public.rounds DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_round_pool();


--

--

CREATE TRIGGER rounds_touch BEFORE UPDATE ON public.rounds FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER sessions_touch BEFORE UPDATE ON public.sessions FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER support_tickets_touch BEFORE UPDATE ON public.support_tickets FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER users_audit AFTER INSERT OR DELETE OR UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER users_touch BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER verification_check_types_touch BEFORE UPDATE ON public.verification_check_types FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER verification_checks_audit AFTER INSERT OR DELETE OR UPDATE ON public.verification_checks FOR EACH ROW EXECUTE FUNCTION app.audit_row();


--

--

CREATE TRIGGER verification_checks_touch BEFORE UPDATE ON public.verification_checks FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE TRIGGER webhook_events_touch BEFORE UPDATE ON public.webhook_events FOR EACH ROW EXECUTE FUNCTION app.touch_row();


--

--

CREATE POLICY admins_select_staff ON public.admins FOR SELECT USING (app.is_platform_staff());


--

--

CREATE POLICY ajo_members_insert_own ON public.ajo_members FOR INSERT WITH CHECK ((user_id = app.request_user_id()));


--

--

CREATE POLICY ajo_members_select ON public.ajo_members FOR SELECT USING (((user_id = app.request_user_id()) OR app.is_ajo_member(ajo_id) OR app.is_platform_staff()));


--

--

CREATE POLICY ajo_members_update_own ON public.ajo_members FOR UPDATE USING ((user_id = app.request_user_id())) WITH CHECK ((user_id = app.request_user_id()));


--

--

CREATE POLICY ajo_positions_select ON public.ajo_positions FOR SELECT USING ((app.is_ajo_member(ajo_id) OR (EXISTS ( SELECT 1
   FROM public.ajos a
  WHERE ((a.id = ajo_positions.ajo_id) AND (a.organizer_user_id = app.request_user_id())))) OR app.is_platform_staff()));


--

--

CREATE POLICY ajo_positions_select_only ON public.ajo_positions FOR SELECT USING ((app.is_ajo_member(ajo_id) OR (EXISTS ( SELECT 1
   FROM public.ajos a
  WHERE ((a.id = ajo_positions.ajo_id) AND (a.organizer_user_id = app.request_user_id())))) OR app.is_platform_staff()));


--

--

CREATE POLICY ajos_insert_own ON public.ajos FOR INSERT WITH CHECK ((organizer_user_id = app.request_user_id()));


--

--

CREATE POLICY ajos_select ON public.ajos FOR SELECT USING (((organizer_user_id = app.request_user_id()) OR app.is_ajo_member(id) OR app.is_platform_staff()));


--

--

CREATE POLICY ajos_update_own ON public.ajos FOR UPDATE USING ((organizer_user_id = app.request_user_id())) WITH CHECK ((organizer_user_id = app.request_user_id()));


--

--

CREATE POLICY audit_logs_select_staff ON public.audit_logs FOR SELECT USING (app.is_platform_staff());


--

--

CREATE POLICY contribution_frequencies_read ON public.contribution_frequencies FOR SELECT USING (((app.request_user_id() IS NOT NULL) OR app.is_platform_staff()));


--

--

CREATE POLICY contribution_schedules_select ON public.contribution_schedules FOR SELECT USING ((app.is_ajo_member(ajo_id) OR (EXISTS ( SELECT 1
   FROM public.ajos a
  WHERE ((a.id = contribution_schedules.ajo_id) AND (a.organizer_user_id = app.request_user_id())))) OR app.is_platform_staff()));


--

--

CREATE POLICY contributions_select ON public.contributions FOR SELECT USING (((user_id = app.request_user_id()) OR (EXISTS ( SELECT 1
   FROM public.ajos a
  WHERE ((a.id = contributions.ajo_id) AND (a.organizer_user_id = app.request_user_id())))) OR app.is_platform_staff() OR (app.is_ajo_member(ajo_id) AND (status <> 'defaulted'::public.contribution_status))));


--

--

CREATE POLICY device_tokens_delete_own ON public.device_tokens FOR DELETE USING ((user_id = app.request_user_id()));


--

--

CREATE POLICY device_tokens_select_own ON public.device_tokens FOR SELECT USING ((user_id = app.request_user_id()));


--

--

CREATE POLICY dispute_evidence_insert_party ON public.dispute_evidence FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM public.documents d
  WHERE ((d.id = dispute_evidence.document_id) AND (d.owner_user_id = app.request_user_id())))));


--

--

CREATE POLICY dispute_evidence_select ON public.dispute_evidence FOR SELECT USING (((EXISTS ( SELECT 1
   FROM public.disputes d
  WHERE ((d.id = dispute_evidence.dispute_id) AND ((d.raised_by_user_id = app.request_user_id()) OR (d.against_user_id = app.request_user_id()) OR (EXISTS ( SELECT 1
           FROM public.ajos a
          WHERE ((a.id = d.ajo_id) AND (a.organizer_user_id = app.request_user_id())))))))) OR app.is_platform_staff()));


--

--

CREATE POLICY dispute_messages_insert_party ON public.dispute_messages FOR INSERT WITH CHECK (((author_user_id = app.request_user_id()) AND (EXISTS ( SELECT 1
   FROM public.disputes d
  WHERE ((d.id = dispute_messages.dispute_id) AND ((d.raised_by_user_id = app.request_user_id()) OR (d.against_user_id = app.request_user_id())))))));


--

--

CREATE POLICY dispute_messages_select ON public.dispute_messages FOR SELECT USING (((EXISTS ( SELECT 1
   FROM public.disputes d
  WHERE ((d.id = dispute_messages.dispute_id) AND ((d.raised_by_user_id = app.request_user_id()) OR (d.against_user_id = app.request_user_id()) OR (EXISTS ( SELECT 1
           FROM public.ajos a
          WHERE ((a.id = d.ajo_id) AND (a.organizer_user_id = app.request_user_id())))))))) OR app.is_platform_staff()));


--

--

CREATE POLICY dispute_reasons_read ON public.dispute_reasons FOR SELECT USING (((app.request_user_id() IS NOT NULL) OR app.is_platform_staff()));


--

--

CREATE POLICY disputes_insert_own ON public.disputes FOR INSERT WITH CHECK ((raised_by_user_id = app.request_user_id()));


--

--

CREATE POLICY disputes_select ON public.disputes FOR SELECT USING (((raised_by_user_id = app.request_user_id()) OR (against_user_id = app.request_user_id()) OR (EXISTS ( SELECT 1
   FROM public.ajos a
  WHERE ((a.id = disputes.ajo_id) AND (a.organizer_user_id = app.request_user_id())))) OR app.is_platform_staff()));


--

--

CREATE POLICY document_types_read ON public.document_types FOR SELECT USING (((app.request_user_id() IS NOT NULL) OR app.is_platform_staff()));


--

--

CREATE POLICY documents_insert_own ON public.documents FOR INSERT WITH CHECK ((owner_user_id = app.request_user_id()));


--

--

CREATE POLICY documents_select ON public.documents FOR SELECT USING (((owner_user_id = app.request_user_id()) OR app.is_platform_staff()));


--

--

CREATE POLICY fees_select ON public.fees FOR SELECT USING (((EXISTS ( SELECT 1
   FROM public.contributions c
  WHERE ((c.id = fees.contribution_id) AND (c.user_id = app.request_user_id())))) OR app.is_platform_staff()));


--

--

CREATE POLICY idempotency_keys_select_own ON public.idempotency_keys FOR SELECT USING ((user_id = app.request_user_id()));


--

--

CREATE POLICY invitations_select ON public.invitations FOR SELECT USING (((ajo_id IN ( SELECT app.current_ajo_ids() AS current_ajo_ids)) OR (invited_by_user_id = app.request_user_id()) OR (EXISTS ( SELECT 1
   FROM public.users u
  WHERE ((u.id = app.request_user_id()) AND (u.email OPERATOR(public.=) invitations.email)))) OR app.is_platform_staff()));


--

--

CREATE POLICY ledger_postings_select_staff ON public.ledger_postings FOR SELECT USING (app.is_platform_staff());


--

--

CREATE POLICY ledger_transactions_select_staff ON public.ledger_transactions FOR SELECT USING (app.is_platform_staff());


--

--

CREATE POLICY notification_preferences_select_own ON public.notification_preferences FOR SELECT USING (((user_id = app.request_user_id()) OR app.is_platform_staff()));


--

--

CREATE POLICY notification_preferences_write_own ON public.notification_preferences USING ((user_id = app.request_user_id())) WITH CHECK ((user_id = app.request_user_id()));


--

--

CREATE POLICY notification_templates_read ON public.notification_templates FOR SELECT USING (((app.request_user_id() IS NOT NULL) OR app.is_platform_staff()));


--

--

CREATE POLICY notifications_select_own ON public.notifications FOR SELECT USING ((user_id = app.request_user_id()));


--

--

CREATE POLICY notifications_update_own ON public.notifications FOR UPDATE USING ((user_id = app.request_user_id())) WITH CHECK ((user_id = app.request_user_id()));


--

--

CREATE POLICY outbox_events_select_staff ON public.outbox_events FOR SELECT USING (app.is_platform_staff());


--

--

CREATE POLICY payment_channels_read ON public.payment_channels FOR SELECT USING (((app.request_user_id() IS NOT NULL) OR app.is_platform_staff()));


--

--

CREATE POLICY payments_select ON public.payments FOR SELECT USING (((EXISTS ( SELECT 1
   FROM public.contributions c
  WHERE ((c.id = payments.contribution_id) AND (c.user_id = app.request_user_id())))) OR app.is_platform_staff()));


--

--

CREATE POLICY payouts_select ON public.payouts FOR SELECT USING (((user_id = app.request_user_id()) OR app.is_platform_staff()));


--

--

CREATE POLICY platform_settings_read ON public.platform_settings FOR SELECT USING (((app.request_user_id() IS NOT NULL) OR app.is_platform_staff()));


--

--

CREATE POLICY profiles_select_shared_ajo ON public.profiles FOR SELECT USING (((user_id = app.request_user_id()) OR app.shares_ajo_with(user_id) OR app.is_platform_staff()));


--

--

CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE USING (((user_id = app.request_user_id()) AND (app.request_actor_type() = 'member'::text))) WITH CHECK ((user_id = app.request_user_id()));


--

--

CREATE POLICY reconciliation_runs_select_staff ON public.reconciliation_runs FOR SELECT USING (app.is_platform_staff());


--

--

CREATE POLICY risk_events_select_staff ON public.risk_events FOR SELECT USING (app.is_platform_staff());


--

--

CREATE POLICY role_assignments_select_own ON public.role_assignments FOR SELECT USING (((user_id = app.request_user_id()) OR app.is_platform_staff()));


--

--

CREATE POLICY roles_read ON public.roles FOR SELECT USING (((app.request_user_id() IS NOT NULL) OR app.is_platform_staff()));


--

--

CREATE POLICY rounds_select ON public.rounds FOR SELECT USING ((app.is_ajo_member(ajo_id) OR (EXISTS ( SELECT 1
   FROM public.ajos a
  WHERE ((a.id = rounds.ajo_id) AND (a.organizer_user_id = app.request_user_id())))) OR app.is_platform_staff()));


--

--

CREATE POLICY sessions_delete_own ON public.sessions FOR DELETE USING ((user_id = app.request_user_id()));


--

--

CREATE POLICY sessions_select_own ON public.sessions FOR SELECT USING (((user_id = app.request_user_id()) OR app.is_platform_staff()));


--

--

CREATE POLICY support_tickets_select ON public.support_tickets FOR SELECT USING (((user_id = app.request_user_id()) OR (assigned_to_user_id = app.request_user_id()) OR app.is_platform_staff()));


--

--

CREATE POLICY users_select_self_or_staff ON public.users FOR SELECT USING (((id = app.request_user_id()) OR app.is_platform_staff()));


--

--

CREATE POLICY users_update_own ON public.users FOR UPDATE USING (((id = app.request_user_id()) AND (app.request_actor_type() = 'member'::text))) WITH CHECK ((id = app.request_user_id()));


--

--

CREATE POLICY verification_check_types_read ON public.verification_check_types FOR SELECT USING (((app.request_user_id() IS NOT NULL) OR app.is_platform_staff()));


--

--

CREATE POLICY verification_checks_select ON public.verification_checks FOR SELECT USING (((user_id = app.request_user_id()) OR (user_id IN ( SELECT m.user_id
   FROM public.ajo_members m
  WHERE ((m.ajo_id IN ( SELECT app.current_ajo_ids() AS current_ajo_ids)) AND (m.status = ANY (ARRAY['active'::public.member_status, 'defaulted'::public.member_status])) AND (m.deleted_at IS NULL)))) OR app.is_platform_staff()));


--

--

CREATE POLICY webhook_events_select_staff ON public.webhook_events FOR SELECT USING (app.is_platform_staff());


--
-- PostgreSQL database dump complete
--

--

CREATE VIEW app.policy_coverage AS
 SELECT c.relname AS table_name,
    c.relrowsecurity AS rls_enabled,
    c.relforcerowsecurity AS rls_forced,
    count(p.polname) AS policy_count
   FROM ((pg_class c
     JOIN pg_namespace n ON ((n.oid = c.relnamespace)))
     LEFT JOIN pg_policy p ON (((p.polrelid = c.oid) AND (p.polcmd = ANY (ARRAY['r'::"char", 'a'::"char"])))))
  WHERE ((n.nspname = 'public'::name) AND (c.relkind = 'r'::"char") AND c.relrowsecurity)
  GROUP BY c.relname, c.relrowsecurity, c.relforcerowsecurity;


--

--

COMMENT ON CONSTRAINT ajos_enrollment_window_is_five_days ON public.ajos IS 'CANONICAL.md section 3. If every position is not filled by day 5 the Ajo cancels and contributions are refunded in full, so the window is a money-bearing deadline and is enforced by the database.';


--

--

COMMENT ON CONSTRAINT disputes_one_open_per_contribution ON public.disputes IS 'A member cannot open three disputes about the same contribution and have them worked in parallel. The exclusion constraint also covers the two other open states, because two rows with different open statuses are still two live disputes.';


--

--

COMMENT ON CONSTRAINT documents_no_duplicate_upload_per_user ON public.documents IS 'A person cannot attach the same file to two different checks. Two different people uploading the same file is allowed and is not a constraint violation.';


--

--

COMMENT ON CONSTRAINT notification_preferences_money_sms_consistent ON public.notification_preferences IS 'A member cannot opt into money-critical SMS while SMS is switched off, which would suppress payout.alerts without them meaning to.';


--

--

COMMENT ON CONSTRAINT payments_fee_rate_bps_check ON public.payments IS 'The 2% rate is pinned. CANONICAL.md section 1 fixes it and a member has already been shown the figure on a receipt. Changing it is a migration, a product decision and a legal review, never a configuration change.';


--

--

COMMENT ON CONSTRAINT payouts_amount_is_base_pool ON public.payouts IS 'CANONICAL.md section 1 and open decision D-01: the recipient receives the BASE pool. NGN 10,000.00, never NGN 10,200.00 and never NGN 9,800.00. The fee is charged to the member on the way in and never comes back out. This constraint is what makes that a property of the system rather than a rule.';


--

--

COMMENT ON CONSTRAINT verification_checks_review_consistent ON public.verification_checks IS 'An approved or rejected check must record who decided it and when. A pending check with a reviewer is a bug that would otherwise hide inside a support queue.';


--

--

COMMENT ON TRIGGER users_touch ON public.users IS 'version is bumped by the trigger, never by the caller. A partial UPDATE that forgets to increment it would otherwise pass an optimistic-concurrency check it has already lost (section 9.8).';


--

--

COMMENT ON VIEW app.policy_coverage IS 'Every RLS-enabled table in public, with its policy count. A row with policy_count = 0 is a table no request can read, and 9.14 requires this view to return no such row before a migration is marked applied.';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
