-- The Ajo lifecycle
--
-- Adopted from the `ajo` database, which held this schema with no
-- SQL source in version control. Generated by scripts/adopt_schema.py;
-- do not hand-edit, re-run the generator and commit the result.
--
-- 24 object(s). Tables: contribution_frequencies, payment_channels, ajos, ajo_positions, ajo_members, rounds, contribution_schedules.

SET check_function_bodies = false;

--

CREATE TABLE public.ajo_members (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    ajo_id uuid NOT NULL,
    user_id uuid NOT NULL,
    position_id uuid,
    invitation_id uuid,
    status public.member_status DEFAULT 'invited'::public.member_status NOT NULL,
    invited_at timestamp with time zone DEFAULT now() NOT NULL,
    joined_at timestamp with time zone,
    left_at timestamp with time zone,
    exit_reason text,
    replaced_by_membership_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT ajo_members_active_joined CHECK (((status <> ALL (ARRAY['active'::public.member_status, 'defaulted'::public.member_status, 'replaced'::public.member_status, 'exited'::public.member_status, 'removed'::public.member_status])) OR (joined_at IS NOT NULL)))
);


--

--

CREATE TABLE public.ajo_positions (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    ajo_id uuid NOT NULL,
    position_number smallint NOT NULL,
    status public.position_status DEFAULT 'open'::public.position_status NOT NULL,
    preference_rank smallint,
    locked_at timestamp with time zone,
    released_at timestamp with time zone,
    release_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT ajo_positions_locked_has_timestamp CHECK (((status <> 'locked'::public.position_status) OR (locked_at IS NOT NULL))),
    CONSTRAINT ajo_positions_position_number_check CHECK ((position_number >= 1)),
    CONSTRAINT ajo_positions_preference_rank_check CHECK (((preference_rank IS NULL) OR (preference_rank >= 1))),
    CONSTRAINT ajo_positions_released_has_reason CHECK (((released_at IS NULL) OR (release_reason IS NOT NULL)))
);


--

--

COMMENT ON TABLE public.ajo_positions IS 'The turn order. Occupancy is NOT held here -- ajo_members.position_id is the single source of truth, which removes a circular foreign key and means a position can be released without touching its own row. See section 8.2.';


--

--

CREATE TABLE public.ajos (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    reference text DEFAULT ('AJO-'::text || upper(substr(replace((app.uuidv7())::text, '-'::text, ''::text), 1, 12))) NOT NULL,
    name text NOT NULL,
    description text,
    status public.ajo_status DEFAULT 'draft'::public.ajo_status NOT NULL,
    organizer_user_id uuid NOT NULL,
    currency character(3) DEFAULT 'NGN'::bpchar NOT NULL,
    contribution_amount_kobo bigint NOT NULL,
    frequency_id uuid NOT NULL,
    preferred_channel_id uuid,
    position_count smallint NOT NULL,
    total_rounds smallint DEFAULT 2 NOT NULL,
    rounds_completed smallint DEFAULT 0 NOT NULL,
    enrollment_opens_at timestamp with time zone DEFAULT now() NOT NULL,
    enrollment_closes_at timestamp with time zone NOT NULL,
    activated_at timestamp with time zone,
    completed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    cancellation_reason text,
    frozen_at timestamp with time zone,
    freeze_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT ajos_activated_has_timestamp CHECK (((status <> ALL (ARRAY['active'::public.ajo_status, 'round_in_progress'::public.ajo_status, 'completed'::public.ajo_status])) OR (activated_at IS NOT NULL))),
    CONSTRAINT ajos_cancelled_has_reason CHECK (((status <> ALL (ARRAY['cancelled'::public.ajo_status, 'cancelling'::public.ajo_status])) OR (cancellation_reason IS NOT NULL))),
    CONSTRAINT ajos_check CHECK (((rounds_completed >= 0) AND (rounds_completed <= total_rounds))),
    CONSTRAINT ajos_completed_has_timestamp CHECK (((status <> 'completed'::public.ajo_status) OR (completed_at IS NOT NULL))),
    CONSTRAINT ajos_contribution_amount_kobo_check CHECK ((contribution_amount_kobo > 0)),
    CONSTRAINT ajos_currency_check CHECK ((currency = 'NGN'::bpchar)),
    CONSTRAINT ajos_enrollment_window_is_bounded CHECK ((enrollment_closes_at >= enrollment_opens_at)),
    CONSTRAINT ajos_enrollment_window_is_five_days CHECK ((enrollment_closes_at <= (enrollment_opens_at + '5 days'::interval))),
    CONSTRAINT ajos_frozen_has_reason CHECK (((status <> 'frozen'::public.ajo_status) OR ((frozen_at IS NOT NULL) AND (freeze_reason IS NOT NULL)))),
    CONSTRAINT ajos_name_check CHECK (((length(btrim(name)) >= 3) AND (length(btrim(name)) <= 80))),
    CONSTRAINT ajos_position_count_check CHECK ((position_count >= 2)),
    CONSTRAINT ajos_total_rounds_check CHECK ((total_rounds >= 2))
);


--

--

COMMENT ON COLUMN public.ajos.contribution_amount_kobo IS 'The base obligation, in kobo. A member owing NGN 1,000.00 has contribution_amount_kobo = 100000. The 2% fee is never added here: the fee is a charge on the member, not a change to what the pool receives.';


--

--

CREATE TABLE public.contribution_frequencies (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    interval_count smallint NOT NULL,
    interval_unit text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    sort_order smallint DEFAULT 100 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT contribution_frequencies_interval_count_check CHECK ((interval_count > 0)),
    CONSTRAINT contribution_frequencies_interval_unit_check CHECK ((interval_unit = ANY (ARRAY['day'::text, 'week'::text, 'month'::text])))
);


--

--

CREATE TABLE public.contribution_schedules (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    round_id uuid NOT NULL,
    ajo_id uuid NOT NULL,
    due_date date NOT NULL,
    expected_amount_kobo bigint NOT NULL,
    expected_member_count smallint NOT NULL,
    late_cutoff_at timestamp with time zone NOT NULL,
    grace_ends_at timestamp with time zone,
    status public.schedule_status DEFAULT 'draft'::public.schedule_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT contribution_schedules_expected_amount_kobo_check CHECK ((expected_amount_kobo > 0)),
    CONSTRAINT contribution_schedules_expected_member_count_check CHECK ((expected_member_count >= 0)),
    CONSTRAINT contribution_schedules_grace_after_cutoff CHECK (((grace_ends_at IS NULL) OR (grace_ends_at >= late_cutoff_at)))
);


--

--

CREATE TABLE public.payment_channels (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    provider text NOT NULL,
    provider_channel_code text NOT NULL,
    min_amount_kobo bigint DEFAULT 0 NOT NULL,
    max_amount_kobo bigint,
    requires_reference boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT payment_channels_check CHECK (((max_amount_kobo IS NULL) OR (max_amount_kobo >= min_amount_kobo))),
    CONSTRAINT payment_channels_min_amount_kobo_check CHECK ((min_amount_kobo >= 0))
);


--

--

CREATE TABLE public.rounds (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    ajo_id uuid NOT NULL,
    round_number smallint NOT NULL,
    status public.round_status DEFAULT 'scheduled'::public.round_status NOT NULL,
    due_date date NOT NULL,
    opens_at timestamp with time zone NOT NULL,
    closes_at timestamp with time zone NOT NULL,
    target_amount_kobo bigint NOT NULL,
    base_pool_kobo bigint DEFAULT 0 NOT NULL,
    fee_collected_kobo bigint DEFAULT 0 NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    held_at timestamp with time zone,
    held_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT rounds_base_pool_kobo_check CHECK ((base_pool_kobo >= 0)),
    CONSTRAINT rounds_completed_has_timestamp CHECK (((status <> 'completed'::public.round_status) OR (completed_at IS NOT NULL))),
    CONSTRAINT rounds_fee_collected_kobo_check CHECK ((fee_collected_kobo >= 0)),
    CONSTRAINT rounds_held_has_reason CHECK (((status <> 'held'::public.round_status) OR (held_reason IS NOT NULL))),
    CONSTRAINT rounds_round_number_check CHECK ((round_number >= 1)),
    CONSTRAINT rounds_target_amount_kobo_check CHECK ((target_amount_kobo > 0))
);


--

--

COMMENT ON COLUMN public.rounds.base_pool_kobo IS 'The exact sum of this round''s paid, non-superseded contributions. For a ten-member Ajo at NGN 1,000.00 this is 1000000 kobo = NGN 10,000.00, and it is the only figure that may be paid out. Maintained by a deferred trigger, so it cannot disagree with the contributions that produced it.';


--

--

ALTER TABLE ONLY public.ajo_members
    ADD CONSTRAINT ajo_members_ajo_user_unique UNIQUE (ajo_id, user_id);


--

--

ALTER TABLE ONLY public.ajo_members
    ADD CONSTRAINT ajo_members_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.ajo_positions
    ADD CONSTRAINT ajo_positions_number_unique UNIQUE (ajo_id, position_number);


--

--

ALTER TABLE ONLY public.ajo_positions
    ADD CONSTRAINT ajo_positions_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.ajos
    ADD CONSTRAINT ajos_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.ajos
    ADD CONSTRAINT ajos_reference_key UNIQUE (reference);


--

--

ALTER TABLE ONLY public.contribution_frequencies
    ADD CONSTRAINT contribution_frequencies_code_key UNIQUE (code);


--

--

ALTER TABLE ONLY public.contribution_frequencies
    ADD CONSTRAINT contribution_frequencies_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.contribution_schedules
    ADD CONSTRAINT contribution_schedules_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.contribution_schedules
    ADD CONSTRAINT contribution_schedules_round_id_key UNIQUE (round_id);


--

--

ALTER TABLE ONLY public.payment_channels
    ADD CONSTRAINT payment_channels_code_key UNIQUE (code);


--

--

ALTER TABLE ONLY public.payment_channels
    ADD CONSTRAINT payment_channels_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.rounds
    ADD CONSTRAINT rounds_ajo_number_unique UNIQUE (ajo_id, round_number);


--

--

ALTER TABLE ONLY public.rounds
    ADD CONSTRAINT rounds_pkey PRIMARY KEY (id);


--
