-- Disputes, risk, operations and the audit log
--
-- Adopted from the `ajo` database, which held this schema with no
-- SQL source in version control. Generated by scripts/adopt_schema.py;
-- do not hand-edit, re-run the generator and commit the result.
--
-- 23 object(s). Tables: dispute_reasons, disputes, dispute_messages, dispute_evidence, risk_events, reconciliation_runs, support_tickets, audit_logs, platform_settings.

SET check_function_bodies = false;

--

CREATE TABLE public.audit_logs (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    actor_user_id uuid,
    actor_role_code text,
    actor_type text NOT NULL,
    action text NOT NULL,
    subject_type public.subject_type,
    subject_id uuid,
    before_state jsonb,
    after_state jsonb,
    request_id text,
    ip_address inet,
    user_agent text,
    amount_kobo bigint,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT audit_logs_actor_type_check CHECK ((actor_type = ANY (ARRAY['user'::text, 'system'::text, 'service'::text, 'webhook'::text]))),
    CONSTRAINT audit_logs_amount_kobo_check CHECK (((amount_kobo IS NULL) OR (amount_kobo >= 0))),
    CONSTRAINT audit_logs_has_payload CHECK (((before_state IS NOT NULL) OR (after_state IS NOT NULL) OR (action ~~ '%.read'::text)))
);

ALTER TABLE ONLY public.audit_logs FORCE ROW LEVEL SECURITY;


--

--

COMMENT ON TABLE public.audit_logs IS 'Append-only, and the answer to most support questions. actor_role_code is the role held at the time of the action, not the role held now, because a role change must not retroactively change what somebody was permitted to do.';


--

--

CREATE TABLE public.dispute_evidence (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    dispute_id uuid NOT NULL,
    document_id uuid NOT NULL,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--

--

CREATE TABLE public.dispute_messages (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    dispute_id uuid NOT NULL,
    author_user_id uuid NOT NULL,
    body text NOT NULL,
    resulting_transaction_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT dispute_messages_body_check CHECK ((length(btrim(body)) > 0))
);

ALTER TABLE ONLY public.dispute_messages FORCE ROW LEVEL SECURITY;


--

--

COMMENT ON TABLE public.dispute_messages IS 'Append-only. Visible to the parties and to support; never to other members of the Ajo. See the row-level security policies in section 9.6.';


--

--

CREATE TABLE public.dispute_reasons (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--

--

CREATE TABLE public.disputes (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    ajo_id uuid NOT NULL,
    round_id uuid,
    contribution_id uuid,
    payout_id uuid,
    raised_by_user_id uuid NOT NULL,
    against_user_id uuid,
    reason_id uuid NOT NULL,
    category text NOT NULL,
    status public.dispute_status DEFAULT 'open'::public.dispute_status NOT NULL,
    description text NOT NULL,
    resolution text,
    resolved_at timestamp with time zone,
    resolved_by_user_id uuid,
    is_private boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT disputes_not_self_dispute CHECK (((against_user_id IS NULL) OR (against_user_id <> raised_by_user_id))),
    CONSTRAINT disputes_open_has_no_resolution CHECK (((status = ANY (ARRAY['resolved'::public.dispute_status, 'withdrawn'::public.dispute_status])) OR (resolution IS NULL))),
    CONSTRAINT disputes_resolved_consistent CHECK (((status <> ALL (ARRAY['resolved'::public.dispute_status, 'withdrawn'::public.dispute_status])) OR (resolved_at IS NOT NULL)))
);

ALTER TABLE ONLY public.disputes FORCE ROW LEVEL SECURITY;


--

--

CREATE TABLE public.platform_settings (
    key text NOT NULL,
    value jsonb NOT NULL,
    value_type text NOT NULL,
    description text NOT NULL,
    is_sensitive boolean DEFAULT false NOT NULL,
    updated_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT platform_settings_value_type_check CHECK ((value_type = ANY (ARRAY['string'::text, 'integer'::text, 'boolean'::text, 'json'::text])))
);


--

--

CREATE TABLE public.reconciliation_runs (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    run_type text NOT NULL,
    window_start timestamp with time zone NOT NULL,
    window_end timestamp with time zone NOT NULL,
    status public.reconciliation_status DEFAULT 'running'::public.reconciliation_status NOT NULL,
    expected_kobo bigint DEFAULT 0 NOT NULL,
    actual_kobo bigint DEFAULT 0 NOT NULL,
    variance_kobo bigint DEFAULT 0 NOT NULL,
    findings jsonb DEFAULT '{}'::jsonb NOT NULL,
    blocks_disbursement boolean DEFAULT true NOT NULL,
    triggered_by_user_id uuid,
    notes text,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT reconciliation_runs_actual_kobo_check CHECK ((actual_kobo >= 0)),
    CONSTRAINT reconciliation_runs_expected_kobo_check CHECK ((expected_kobo >= 0)),
    CONSTRAINT reconciliation_runs_finished_has_timestamp CHECK (((status = 'running'::public.reconciliation_status) OR (finished_at IS NOT NULL))),
    CONSTRAINT reconciliation_runs_run_type_check CHECK ((run_type = ANY (ARRAY['daily'::text, 'on_demand'::text, 'post_incident'::text, 'pre_disbursement'::text]))),
    CONSTRAINT reconciliation_runs_variance_is_consistent CHECK ((variance_kobo = (expected_kobo - actual_kobo))),
    CONSTRAINT reconciliation_runs_window_ordered CHECK ((window_end > window_start))
);


--

--

COMMENT ON TABLE public.reconciliation_runs IS 'A proof, over a window, that the internal ledger agrees with the provider and with the round expectations. This is the artefact a regulator or an auditor asks for, so it references a time window rather than the rows it checks: the proof must outlive the things it proves.';


--

--

CREATE TABLE public.risk_events (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    subject_type public.risk_subject_type NOT NULL,
    subject_id uuid NOT NULL,
    event_type text NOT NULL,
    severity public.risk_severity DEFAULT 'low'::public.risk_severity NOT NULL,
    status public.risk_event_status DEFAULT 'open'::public.risk_event_status NOT NULL,
    score smallint DEFAULT 0 NOT NULL,
    signals jsonb DEFAULT '{}'::jsonb NOT NULL,
    decision public.risk_decision,
    decision_note text,
    decided_by_user_id uuid,
    decided_at timestamp with time zone,
    assigned_to_user_id uuid,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT risk_events_decided_by_required CHECK (((decision IS NULL) OR (decided_by_user_id IS NOT NULL))),
    CONSTRAINT risk_events_decision_consistent CHECK (((status = ANY (ARRAY['decided'::public.risk_event_status, 'dismissed'::public.risk_event_status])) = (decision IS NOT NULL)))
);

ALTER TABLE ONLY public.risk_events FORCE ROW LEVEL SECURITY;


--

--

CREATE TABLE public.support_tickets (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    ajo_id uuid,
    category text NOT NULL,
    subject text NOT NULL,
    status public.support_ticket_status DEFAULT 'open'::public.support_ticket_status NOT NULL,
    priority public.support_ticket_priority DEFAULT 'normal'::public.support_ticket_priority NOT NULL,
    assigned_to_user_id uuid,
    thread jsonb DEFAULT '[]'::jsonb NOT NULL,
    resolved_at timestamp with time zone,
    first_response_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT support_tickets_resolved_consistent CHECK (((status <> ALL (ARRAY['resolved'::public.support_ticket_status, 'closed'::public.support_ticket_status])) OR (resolved_at IS NOT NULL))),
    CONSTRAINT support_tickets_thread_is_array CHECK ((jsonb_typeof(thread) = 'array'::text))
);


--

--

COMMENT ON TABLE public.support_tickets IS 'Deliberately has NO foreign key into payments, payouts, fees or the ledger. That is the structural expression of CANONICAL.md section 2: the support role can read all records and cannot move money. A table it cannot reach is an operation it cannot perform.';


--

--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pk PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.dispute_evidence
    ADD CONSTRAINT dispute_evidence_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.dispute_messages
    ADD CONSTRAINT dispute_messages_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.dispute_reasons
    ADD CONSTRAINT dispute_reasons_code_key UNIQUE (code);


--

--

ALTER TABLE ONLY public.dispute_reasons
    ADD CONSTRAINT dispute_reasons_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_one_open_per_contribution EXCLUDE USING gist (contribution_id WITH =, status WITH =) WHERE (((status = ANY (ARRAY['open'::public.dispute_status, 'under_review'::public.dispute_status, 'awaiting_member'::public.dispute_status, 'awaiting_organizer'::public.dispute_status, 'escalated'::public.dispute_status])) AND (contribution_id IS NOT NULL)));


--

--

ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.platform_settings
    ADD CONSTRAINT platform_settings_pkey PRIMARY KEY (key);


--

--

ALTER TABLE ONLY public.reconciliation_runs
    ADD CONSTRAINT reconciliation_runs_pkey PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.risk_events
    ADD CONSTRAINT risk_events_pkey PRIMARY KEY (id);


--
