-- The append-only double-entry ledger
--
-- Adopted from the `ajo` database, which held this schema with no
-- SQL source in version control. Generated by scripts/adopt_schema.py;
-- do not hand-edit, re-run the generator and commit the result.
--
-- 6 object(s). Tables: ledger_transactions, ledger_postings.

SET check_function_bodies = false;

--

CREATE TABLE public.ledger_postings (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    transaction_id uuid NOT NULL,
    account_kind public.ledger_account_kind NOT NULL,
    side public.ledger_side NOT NULL,
    amount_kobo bigint NOT NULL,
    signed_kobo bigint GENERATED ALWAYS AS (
CASE
    WHEN (side = 'debit'::public.ledger_side) THEN amount_kobo
    ELSE (- amount_kobo)
END) STORED,
    member_id uuid,
    round_id uuid,
    memo text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ledger_postings_amount_kobo_check CHECK ((amount_kobo > 0))
);

ALTER TABLE ONLY public.ledger_postings FORCE ROW LEVEL SECURITY;


--

--

COMMENT ON COLUMN public.ledger_postings.signed_kobo IS 'Generated. debit = +amount, credit = -amount, so every transaction sums to exactly zero and a drift of one kobo is a query away rather than an audit away. Enforced at COMMIT by app.assert_transaction_balanced().';


--

--

CREATE TABLE public.ledger_transactions (
    id uuid DEFAULT app.uuidv7() NOT NULL,
    kind public.ledger_entry_type NOT NULL,
    ajo_id uuid,
    round_id uuid,
    member_id uuid,
    payment_id uuid,
    payout_id uuid,
    idempotency_key text,
    reverses_transaction_id uuid,
    reversal_reason text,
    request_id text,
    actor_user_id uuid,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    memo text,
    CONSTRAINT ledger_transactions_fee_matches_kind CHECK (((kind <> 'fee.recognised'::public.ledger_entry_type) OR (payment_id IS NOT NULL))),
    CONSTRAINT ledger_transactions_not_self_reversing CHECK (((reverses_transaction_id IS NULL) OR (reverses_transaction_id <> id))),
    CONSTRAINT ledger_transactions_payout_matches_kind CHECK (((kind <> ALL (ARRAY['payout.recognized'::public.ledger_entry_type, 'payout.settled'::public.ledger_entry_type])) OR (payout_id IS NOT NULL))),
    CONSTRAINT ledger_transactions_reversal_has_reason CHECK (((reverses_transaction_id IS NULL) OR (length(btrim(reversal_reason)) > 0))),
    CONSTRAINT ledger_transactions_reversal_shape CHECK (((kind = 'reversal'::public.ledger_entry_type) = (reverses_transaction_id IS NOT NULL)))
);

ALTER TABLE ONLY public.ledger_transactions FORCE ROW LEVEL SECURITY;


--

--

COMMENT ON TABLE public.ledger_transactions IS 'Append-only. No UPDATE, no DELETE, at any privilege level, by anyone -- including super_admin, per CANONICAL.md section 2. A mistake is corrected by posting the exact mirror of the original as a reversal. See section 9.5.';


--

--

ALTER TABLE ONLY public.ledger_postings
    ADD CONSTRAINT ledger_postings_pk PRIMARY KEY (id);


--

--

ALTER TABLE ONLY public.ledger_transactions
    ADD CONSTRAINT ledger_transactions_pk PRIMARY KEY (id);


--
